include("${source}/test/config.cmake")
foreach(n2 RANGE 1 15)
  foreach(n3 RANGE 1 15)
    foreach(budget RANGE 1 24)
      set(expected 1)
      foreach(p2 RANGE 1 ${n2})
        math(EXPR remainder "${n2} % ${p2}")
        math(EXPR width "${n2} / ${p2}")
        if(NOT remainder EQUAL 0 OR (n2 GREATER 1 AND width LESS 2))
          continue()
        endif()
        foreach(p3 RANGE 1 ${n3})
          math(EXPR remainder "${n3} % ${p3}")
          math(EXPR width "${n3} / ${p3}")
          math(EXPR candidate "${p2} * ${p3}")
          if(remainder EQUAL 0 AND (n3 EQUAL 1 OR width GREATER_EQUAL 2)
              AND candidate LESS_EQUAL budget AND candidate GREATER expected)
            set(expected ${candidate})
          endif()
        endforeach()
      endforeach()
      max_mpi(${n2} ${n3} ${budget} actual)
      if(NOT actual EQUAL expected)
        message(FATAL_ERROR "max_mpi(${n2},${n3},${budget})=${actual}; oracle=${expected}")
      endif()
    endforeach()
  endforeach()
endforeach()
message(STATUS "5400 CMake partition cases passed")
