advec_prep_mpi_23 – GEMINI3D
advec_prep_mpi_23 Subroutine
97 statements
Source File
private subroutine advec_prep_mpi_23(isp, isperiodic, ns, rhovs1, vs1, vs2, vs3, rhoes, v1i, v2i, v3i)
COMPUTE INTERFACE VELOCITIES AND LOAD UP GHOST CELLS FOR FLUID STATE VARIABLES
Note that it is done on a per species basis 5/23/2015 - may need to be changed for 2D/1D sims which have only one element in the x2 direction...
v1i(lx1+1,:,:)=v1i(lx1,:,:)    !avoids issues with top boundary velocity spikes which may arise
    vadvx1(1,:,6)=mean(vadvx1(1,:,6));                          !for eq sims
FOR INTERNAL ENERGY we only need one ghost cell to compute interface velocities NOW DEAL WITH ADVECTION ALONG X3; FIRST IDENTIFY MY NEIGHBORS
PASS X3 VELOCITY BOUNDARY CONDITIONS WITH GENERIC HALOING ROUTINES we only need one ghost cell to compute interface velocities AFTER HALOING CAN COMPUTE THE X3 INTERFACE VELOCITIES NORMALLY
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: isp
logical, intent(in) :: isperiodic
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: rhovs1
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs3
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: rhoes
real(kind=wp), intent(out), dimension(1:size(vs1,1)-3,1:size(vs1,2)-4,1:size(vs1,3)-4) :: v1i
real(kind=wp), intent(out), dimension(1:size(vs1,1)-4,1:size(vs1,2)-3,1:size(vs1,3)-4) :: v2i
real(kind=wp), intent(out), dimension(1:size(vs1,1)-4,1:size(vs1,2)-4,1:size(vs1,3)-3) :: v3i
Calls
Called by
Contents
None
Call graph
advec_prep_mpi_23 calls halo
halo calls halo_23
halo_23 calls halo_23, mpi_isend, mpi_irecv, grid2id, mpi_waitall
advec_prep_mpi calls advec_prep_mpi_23
fluid_adv calls advec_prep_mpi