advec3D_MC_mpi_curv_23 – GEMINI3D
advec3D_MC_mpi_curv_23 Function
78 statements
Source File
private function advec3D_MC_mpi_curv_23(f, v1i, v2i, v3i, dt, x, frank, tagf)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-1:,-1:,-1:) :: f
real(kind=wp), intent(in), dimension(:,:,:) :: v1i
real(kind=wp), intent(in), dimension(:,:,:) :: v2i
real(kind=wp), intent(in), dimension(:,:,:) :: v3i
real(kind=wp), intent(in) :: dt
type(curvmesh), intent(in) :: x
integer, intent(in) :: frank
integer, intent(in) :: tagf
Return Value real(kind=wp), dimension(-1:size(f,1)-2,-1:size(f,2)-2,-1:size(f,3)-2)
Calls
Called by
Contents
None
Call graph
advec3d_mc_mpi_curv_23 calls advec1d_mc_curv, halo
advec1d_mc_curv calls minmod
halo calls halo_23
halo_23 calls halo_23, mpi_isend, mpi_irecv, grid2id, mpi_waitall
advec3d_mc_mpi calls advec3d_mc_mpi_curv_23
fluid_adv calls advec3d_mc_mpi