backEuler3D_curv – GEMINI3D
backEuler3D_curv Function
19 statements
Source File
private function backEuler3D_curv(f, A, B, C, D, E, dt, x)
SOLVE A 3D SEQUENCE OF 1D DIFFUSION PROBLEMS. GHOST CELLS ARE ACCOMODATED AS THEY PROVIDE A CONVENIENT MEMORY SPACE FOR BOUNDARY CONDITIONS.
inner ghost cells include boundary conditions
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-1:,-1:,-1:) :: f
real(kind=wp), intent(in), dimension(:,:,:) :: A
real(kind=wp), intent(in), dimension(:,:,:) :: B
real(kind=wp), intent(in), dimension(:,:,:) :: C
real(kind=wp), intent(in), dimension(:,:,:) :: D
real(kind=wp), intent(in), dimension(:,:,:) :: E
real(kind=wp), intent(in) :: dt
type(curvmesh), intent(in) :: x
Return Value real(kind=wp), dimension(-1:size(f,1)-2,-1:size(f,2)-2,-1:size(f,3)-2)
Calls
Called by
Contents
None
Call graph
backeuler3d_curv calls backeuler1d
backeuler1d calls gbsv
gbsv calls dgbsv, sgbsv
backeuler3d calls backeuler3d_curv