backEuler1D – GEMINI3D
backEuler1D Function
44 statements
Source File
public function backEuler1D(Ts, A, B, C, D, E, Tsminx1, Tsmaxx1, dt, dx1, dx1i)
MINX1 BOUNDARY FIRST INTERIOR GRID POINT INTERIOR GRID POINTS ix1-2 grid point, sub-diag. ix1+2 grid point LAST INTERIOR GRID POINT MAXX1 BOUNDARY ## DO SOME STUFF TO CALL LAPACK'S BANDED SOLVER
BANDED SOLVER (INPUT MATRIX MUST BE SHIFTED 'DOWN' BY KL ROWS)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: Ts
real(kind=wp), intent(in), dimension(:) :: A
real(kind=wp), intent(in), dimension(:) :: B
real(kind=wp), intent(in), dimension(:) :: C
real(kind=wp), intent(in), dimension(:) :: D
real(kind=wp), intent(in), dimension(:) :: E
real(kind=wp), intent(in) :: Tsminx1
real(kind=wp), intent(in) :: Tsmaxx1
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in), dimension(0:) :: dx1
real(kind=wp), intent(in), dimension(:) :: dx1i
Return Value real(kind=wp), dimension(size(Ts))
Calls
Called by
Contents
None
Call graph
backeuler1d calls gbsv
gbsv calls dgbsv, sgbsv
test_diffusion1d calls backeuler1d
backeuler3d_curv calls backeuler1d
backeuler3d calls backeuler3d_curv