bcast_recv3D_23 – GEMINI3D
bcast_recv3D_23 Module Procedure
7 statements
Source File
module procedure bcast_recv3D_23 module subroutine bcast_recv3D_23(paramtrim, tag) Interface →
THIS SUBROUTINE RECEIVES BROADCAST DATA FROM A FULL GRID ARRAY ON ROOT PROCESS TO WORKERS' SUB-GRID ARRAYS.
SUBROUTINE IS TO BE CALLED BY WORKERS TO DO A BROADCAST
THIS VERSION WORKS ON 3D ARRAYS WHICH DO NOT INCLUDE GHOST CELLS!
note here that paramtrim does not have ghost cells WORKERS RECEIVE THE IC DATA FROM ROOT
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(:,:,:) :: paramtrim
integer, intent(in) :: tag
Calls
Called by
Contents
None
Call graph
bcast_recv3d_23 calls mpi_recv, bcast_recv3d_23
bcast_recv calls bcast_recv3d_23
input_workers_mpi calls bcast_recv
input_workers_currents calls bcast_recv
potential_workers_mpi calls bcast_recv, potential_workers_mpi
read_grid_workers calls bcast_recv
input_plasma calls input_workers_mpi, input_plasma
input_plasma_currents calls input_workers_currents, input_plasma_currents
read_grid calls read_grid_workers, read_grid
electrodynamics_curv calls potential_workers_mpi
magcalc calls read_grid, input_plasma_currents
gemini3d calls read_grid, input_plasma, electrodynamics
electrodynamics calls electrodynamics_curv