bcast_recv3D_ghost_23 – GEMINI3D
bcast_recv3D_ghost_23 Module Procedure
7 statements
Source File
module procedure bcast_recv3D_ghost_23 module subroutine bcast_recv3D_ghost_23(param, tag) Interface →
THIS SUBROUTINE RECEIVES BROADCAST DATA FROM A FULL GRID ARRAY ON ROOT PROCESS TO WORKERS' SUB-GRID ARRAYS.
SUBROUTINE IS TO BE CALLED BY WORKERS TO DO A BROADCAST
THIS VERSION WORKS ON 3D ARRAYS WHICH DO NOT INCLUDE GHOST CELLS!
note here that param has ghost cells WORKERS RECEIVE THE IC DATA FROM ROOT
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(-1:,-1:,-1:) :: param
integer, intent(in) :: tag
Calls
Called by
Contents
None
Call graph
bcast_recv3d_ghost_23 calls mpi_recv, bcast_recv3d_ghost_23
bcast_recv3d_ghost calls bcast_recv3d_ghost_23
read_grid_workers calls bcast_recv3d_ghost
read_grid calls read_grid_workers, read_grid
magcalc calls read_grid
gemini3d calls read_grid