bcast_send3D_x2i_23 – GEMINI3D
bcast_send3D_x2i_23 Module Procedure
15 statements
Source File
module procedure bcast_send3D_x2i_23 module subroutine bcast_send3D_x2i_23(paramtrimall, tag, paramtrim) Interface →
+1 since this is an x3 interface quantity note the +1 since thes are interface quantities (and need to overlap b/t workers)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: paramtrimall
integer, intent(in) :: tag
real(kind=wp), intent(out), dimension(:,:,:) :: paramtrim
Calls
Called by
Contents
None
Call graph
bcast_send3d_x2i_23 calls mpi_send, slabinds, bcast_send3d_x2i_23
slabinds calls id2grid
bcast_send3d_x2i calls bcast_send3d_x2i_23
read_grid_root calls bcast_send3d_x2i
read_grid calls read_grid_root, read_grid
magcalc calls read_grid
gemini3d calls read_grid