bcast_send2D_23 – GEMINI3D
bcast_send2D_23 Module Procedure
14 statements
Source File
module procedure bcast_send2D_23 module subroutine bcast_send2D_23(paramtrimall, tag, paramtrim) Interface →
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: paramtrimall
integer, intent(in) :: tag
real(kind=wp), intent(out), dimension(:,:) :: paramtrim
Calls
Called by
Contents
None
Call graph
bcast_send2d_23 calls mpi_send, slabinds, bcast_send2d_23
slabinds calls id2grid
bcast_send calls bcast_send2d_23
input_root_mpi calls bcast_send, input_root_mpi
read_grid_root calls bcast_send
potential_root_mpi_curv calls bcast_send, potential_root_mpi_curv
input_root_currents calls bcast_send, input_root_currents
read_grid calls read_grid_root, read_grid
input_plasma calls input_root_mpi, input_plasma
potential_root_mpi calls potential_root_mpi_curv
input_plasma_currents calls input_root_currents, input_plasma_currents
gemini3d calls read_grid, input_plasma, electrodynamics
electrodynamics_curv calls potential_root_mpi
magcalc calls read_grid, input_plasma_currents
electrodynamics calls electrodynamics_curv