CCOR2 – GEMINI3D
CCOR2 Function
17 statements
Source File
function CCOR2(ALT, R, H1, ZH, H2)
Arguments
Type Intent Optional Attributes Name
real :: ALT
real :: R
real :: H1
real :: ZH
real :: H2
Return Value real
Called by
Contents
None
Call graph
gts7 calls ccor2
gtd7 calls gts7
gtd7d calls gtd7
ghp7 calls gtd7
neutral_atmos calls gtd7, neutral_atmos
gemini3d calls neutral_atmos