check_mumps_status – GEMINI3D
check_mumps_status Subroutine
12 statements
Source File
public subroutine check_mumps_status(p, name)
check if Mumps error occurred
Arguments
Type Intent Optional Attributes Name
type(MUMPS_STRUC), intent(in) :: p
character(len=*), intent(in) :: name
Called by
Contents
None
Call graph
elliptic2d_polarization calls check_mumps_status, elliptic2d_polarization
elliptic_workers calls check_mumps_status
elliptic2d_cart calls check_mumps_status, elliptic2d_cart
elliptic2d_polarization_periodic calls check_mumps_status, elliptic2d_polarization_periodic
elliptic3d_cart calls check_mumps_status, elliptic3d_cart
test_potential2d calls elliptic_workers, elliptic2d_cart, elliptic2d_polarization
potential_workers_mpi calls elliptic_workers, potential_workers_mpi
potential2d_polarization_periodic calls elliptic2d_polarization_periodic, potential2d_polarization_periodic
potential2d_polarization calls elliptic2d_polarization, potential2d_polarization
potential2d_fieldresolved calls elliptic2d_cart, potential2d_fieldresolved
potential3d_fieldresolved_decimate calls elliptic3d_cart
potential_root_mpi_curv calls potential3d_fieldresolved_decimate, potential2d_polarization_periodic, potential2d_fieldresolved, potential2d_polarization, potential_root_mpi_curv
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi
electrodynamics calls electrodynamics_curv
potential_root_mpi calls potential_root_mpi_curv
gemini3d calls electrodynamics