clear_unitvecs – GEMINI3D
clear_unitvecs Subroutine
4 statements
Source File
public subroutine clear_unitvecs(x)
DEALLOCATE GRID UNIT VECTORS, WHICH TAKE UP A LOT OF MEMORY
Arguments
Type Intent Optional Attributes Name
type(curvmesh), intent(inout) :: x
Called by
Contents
None
Call graph
gridproj_dneu3d calls clear_unitvecs
gridproj_dneu2d calls clear_unitvecs
neutral_perturb_cart calls gridproj_dneu2d
neutral_perturb_axisymm calls gridproj_dneu2d
neutral_perturb_3d calls gridproj_dneu3d
neutral_perturb calls neutral_perturb_cart, neutral_perturb_axisymm, neutral_perturb_3d
gemini3d calls neutral_perturb