create_outdir_aur – GEMINI3D
create_outdir_aur Module Procedure
4 statements
Source File
module procedure create_outdir_aur module subroutine create_outdir_aur(outdir) Interface →
CREATES OUTPUT DIRECTORY FOR Auroral CALCULATIONS
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: outdir
Calls
Called by
Contents
None
Call graph
create_outdir_aur calls mkdir, create_outdir_aur
mkdir calls mkdir