create_outdir – GEMINI3D
create_outdir Module Procedure
25 statements
Source File
module procedure create_outdir module subroutine create_outdir(outdir, infile, indatsize, indatgrid, flagdneu, sourcedir, flagprecfile, precdir, flagE0file, E0dir) Interface →
CREATES OUTPUT DIRECTORY, MOVES CONFIG FILES THERE AND GENERATES A GRID OUTPUT FILE
MAKE A COPY OF THE INPUT DATA IN THE OUTPUT DIRECTORY
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: outdir
character(len=*), intent(in) :: infile
character(len=*), intent(in) :: indatsize
character(len=*), intent(in) :: indatgrid
integer, intent(in) :: flagdneu
character(len=*), intent(in) :: sourcedir
integer, intent(in) :: flagprecfile
character(len=*), intent(in) :: precdir
integer, intent(in) :: flagE0file
character(len=*), intent(in) :: E0dir
Calls
Called by
Contents
None
Call graph
create_outdir calls realbits_log, mkdir, gitlog, compiler_log, copyfile, create_outdir
mkdir calls mkdir
copyfile calls copyfile
gemini3d calls create_outdir