create_outdir_mag – GEMINI3D
create_outdir_mag Module Procedure
6 statements
Source File
module procedure create_outdir_mag module subroutine create_outdir_mag(outdir, fieldpointfile) Interface →
CREATES OUTPUT DIRECTORY FOR MAGNETIC FIELD CALCULATIONS
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: outdir
character(len=*), intent(in) :: fieldpointfile
Calls
Called by
Contents
None
Call graph
create_outdir_mag calls mkdir, copyfile, create_outdir_mag
mkdir calls mkdir
copyfile calls copyfile
magcalc calls create_outdir_mag