dateinc – GEMINI3D
dateinc Subroutine
23 statements
Source File
public pure subroutine dateinc(dtsec, ymd, UTsec)
increment datetime by dtsec
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dtsec
seconds to increment
integer, intent(inout) :: ymd(3)
year, month, day of month
real(kind=wp), intent(inout) :: UTsec
seconds since midnight UTC
Calls
Called by
Contents
None
Call graph
dateinc calls day_wrap
day_wrap calls day_wrap, daysmonth
read_dneu2d calls dateinc
precipbcs_fileinput calls dateinc
gemini3d calls dateinc, neutral_perturb, electrodynamics
test_formats calls dateinc
potentialbcs2d_fileinput calls dateinc
read_dneu3d calls dateinc
test_dayrollover calls dateinc
magcalc calls dateinc
fluid_adv calls precipbcs_fileinput
neutral_perturb_axisymm calls read_dneu2d
potential_root_mpi_curv calls potentialbcs2d_fileinput, potential_root_mpi_curv
neutral_perturb_cart calls read_dneu2d
neutral_perturb_3d calls read_dneu3d
neutral_perturb calls neutral_perturb_axisymm, neutral_perturb_cart, neutral_perturb_3d
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv