day_wrap – GEMINI3D
day_wrap Subroutine
13 statements
Source File
public pure recursive subroutine day_wrap(year, month, day)
increment date if needed, according to day that is, if day is beyond month, increment month and year if needed wrap months wrap days
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: year
integer, intent(inout) :: month
integer, intent(inout) :: day
Calls
Called by
Contents
None
Call graph
day_wrap calls day_wrap, daysmonth
utsec2filestem calls day_wrap
dateinc calls day_wrap
test_dayrollover calls day_wrap, dateinc
read_dneu2d calls dateinc, date_filename
precipbcs_fileinput calls dateinc, date_filename
gemini3d calls dateinc, neutral_perturb, output_plasma, output_aur, electrodynamics
date_filename calls utsec2filestem
test_formats calls utsec2filestem, dateinc
potentialbcs2d_fileinput calls dateinc, date_filename
read_dneu3d calls dateinc, date_filename
magcalc calls dateinc, output_magfields, input_plasma_currents
output_magfields calls date_filename, output_magfields
output_aur_root calls date_filename, output_aur_root
neutral_perturb_3d calls read_dneu3d
fluid_adv calls precipbcs_fileinput
output_root_stream_mpi calls date_filename, output_root_stream_mpi
neutral_perturb_axisymm calls read_dneu2d
potential_root_mpi_curv calls potentialbcs2d_fileinput, potential_root_mpi_curv
input_root_currents calls date_filename, input_root_currents
neutral_perturb_cart calls read_dneu2d
neutral_perturb calls neutral_perturb_3d, neutral_perturb_axisymm, neutral_perturb_cart
output_plasma calls output_root_stream_mpi, output_plasma
output_aur calls output_aur_root, output_aur
input_plasma_currents calls input_root_currents, input_plasma_currents
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv