daysmonth – GEMINI3D
daysmonth Function
9 statements
Source File
private elemental function daysmonth(year, month) result(days)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: year
integer, intent(in) :: month
Return Value integer
Called by
Contents
None
Call graph
day_wrap calls daysmonth, day_wrap
doy_calc calls daysmonth
neutral_atmos calls doy_calc, neutral_atmos
sza calls doy_calc
dateinc calls day_wrap
ionrate_glow98 calls doy_calc
test_dayrollover calls day_wrap, doy_calc, dateinc
utsec2filestem calls day_wrap
read_dneu2d calls dateinc, date_filename
test_sza calls sza
fluid_adv calls sza, ionrate_glow98, precipbcs_fileinput
precipbcs_fileinput calls dateinc, date_filename
gemini3d calls dateinc, neutral_atmos, neutral_perturb, output_plasma, output_aur, electrodynamics
test_formats calls dateinc, utsec2filestem
potentialbcs2d_fileinput calls dateinc, date_filename
date_filename calls utsec2filestem
read_dneu3d calls dateinc, date_filename
magcalc calls dateinc, output_magfields, input_plasma_currents
output_magfields calls date_filename, output_magfields
output_aur_root calls date_filename, output_aur_root
neutral_perturb_3d calls read_dneu3d
output_root_stream_mpi calls date_filename, output_root_stream_mpi
neutral_perturb_axisymm calls read_dneu2d
potential_root_mpi_curv calls potentialbcs2d_fileinput, potential_root_mpi_curv
input_root_currents calls date_filename, input_root_currents
neutral_perturb_cart calls read_dneu2d
neutral_perturb calls neutral_perturb_3d, neutral_perturb_axisymm, neutral_perturb_cart
output_plasma calls output_root_stream_mpi, output_plasma
output_aur calls output_aur_root, output_aur
input_plasma_currents calls input_root_currents, input_plasma_currents
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv