DENSM – GEMINI3D
DENSM Function
68 statements
Source File
function DENSM(ALT, D0, XM, TZ, MN3, ZN3, TN3, TGN3, MN2, ZN2, TN2, TGN2)
Arguments
Type Intent Optional Attributes Name
real :: ALT
real :: D0
real :: XM
real :: TZ
integer :: MN3
real :: ZN3
real :: TN3
real :: TGN3
integer :: MN2
real :: ZN2
real :: TN2
real :: TGN2
Return Value real
Calls
Called by
Contents
Common Blocks
PARMB FIT LSQV
Common Blocks
common /PARMB/
Type Attributes Name Initial
real :: GSURF
real :: RE
common /FIT/
Type Attributes Name Initial
real :: TAF
common /LSQV/
Type Attributes Name Initial
integer :: MP
integer :: II
integer :: JG
integer :: LT
real :: QPB(50)
integer :: IERR
integer :: IFUN
integer :: N
integer :: J
real :: DV(60)
Call graph
densm calls spline, zeta, ys, splint, xs, splini, amax1
spline calls u
splini calls amin1
gtd7 calls densm
gtd7d calls gtd7
ghp7 calls gtd7
neutral_atmos calls gtd7, neutral_atmos
gemini3d calls neutral_atmos