doy_calc – GEMINI3D
doy_calc Function
10 statements
Source File
public elemental function doy_calc(year, month, day) result(doy)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: year
integer, intent(in) :: month
integer, intent(in) :: day
Return Value integer
Calls
Called by
Contents
None
Call graph
doy_calc calls daysmonth
sza calls doy_calc
ionrate_glow98 calls doy_calc
neutral_atmos calls doy_calc, neutral_atmos
test_dayrollover calls doy_calc
test_sza calls sza
fluid_adv calls sza, ionrate_glow98
gemini3d calls neutral_atmos