electrodynamics_curv – GEMINI3D
electrodynamics_curv Subroutine
90 statements
Source File
private subroutine electrodynamics_curv(it, t, dt, nn, vn2, vn3, Tn, sourcemlat, ns, Ts, vs1, B1, vs2, vs3, x, potsolve, flagcap, E1, E2, E3, J1, J2, J3, Phiall, flagE0file, dtE0, E0dir, ymd, UTsec)
THIS IS A WRAPPER FUNCTION FOR THE ELECTRODYANMICS PART OF THE MODEL. BOTH THE ROOT AND WORKER PROCESSES CALL THIS SAME SUBROUTINE, WHEN THEN BRANCHES INTO DIFFERENT TASKS FOR EACH AFTER ALL COMPUTE CONDUCTIVITIES AND INERTIAL CAPACITANCE.
NOTE THAT THE ALLOCATION STATUS OF THE ALL VARIABLES FOR THE WORKERS WILL BE UNALLOCATED. THIS code requires FORTRAN >= 2003 STANDARD.
To leading order the ion drifts do not include the polarization parts, otherwise it may mess up polarization convective term in the electrodynamics solver...
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: it
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in), dimension(:,:,:,:) :: nn
real(kind=wp), intent(in), dimension(:,:,:) :: vn2
real(kind=wp), intent(in), dimension(:,:,:) :: vn3
real(kind=wp), intent(in), dimension(:,:,:) :: Tn
real(kind=wp), intent(in) :: sourcemlat
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: Ts
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(in), dimension(-1:,-1:,-1:) :: B1
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs3
type(curvmesh), intent(in) :: x
integer, intent(in) :: potsolve
integer, intent(in) :: flagcap
real(kind=wp), intent(out), dimension(:,:,:) :: E1
real(kind=wp), intent(out), dimension(:,:,:) :: E2
real(kind=wp), intent(out), dimension(:,:,:) :: E3
real(kind=wp), intent(out), dimension(:,:,:) :: J1
real(kind=wp), intent(out), dimension(:,:,:) :: J2
real(kind=wp), intent(out), dimension(:,:,:) :: J3
real(kind=wp), intent(inout), dimension(:,:,:), allocatable :: Phiall
inout since it may not be allocated or deallocated in this procedure
integer, intent(in) :: flagE0file
real(kind=wp), intent(in) :: dtE0
character(len=*), intent(in) :: E0dir
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
Calls
Called by
Contents
None
Call graph
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi, capacitance, conductivities
potential_workers_mpi calls potential_workers_mpi, bcast_recv, elliptic_workers, mpi_recv, halo_pot, div3d, integral3d1_curv_alt, gather_send, integral3d1, grad3d2, grad3d1, grad3d3
potential_root_mpi calls potential_root_mpi_curv
conductivities calls maxwell_colln, coulomb_colln
potential_root_mpi_curv calls potential_root_mpi_curv, halo_pot, div3d, integral3d1_curv_alt, integral3d1, grad3d2, grad3d1, grad3d3, potential2d_polarization_periodic, potential3d_fieldresolved_decimate, potentialbcs2d, bcast_send, potential2d_fieldresolved, gather_recv, mpi_send, potentialbcs2d_fileinput, potential2d_polarization
bcast_recv calls bcast_recv2d_23, bcast_recv4d_23, bcast_recv3d_23, bcast_recv1d_23
elliptic_workers calls check_mumps_status, quiet_mumps, mumps_exec
halo_pot calls halo
div3d calls div3d_curv_23
integral3d1_curv_alt calls integral3d1_curv_alt
gather_send calls gather_send4d_23, gather_send2d_23, gather_send3d_23
integral3d1 calls integral3d1_curv
grad3d2 calls grad3d2_curv_23
grad3d1 calls grad3d1_curv_23
grad3d3 calls grad3d3_curv_23
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
potential2d_polarization_periodic calls potential2d_polarization_periodic, grad2d1_curv_alt, elliptic2d_polarization_periodic, grad2d3_curv_periodic
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
grad3d3_curv_23 calls grad3d3_curv_23
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
potential3d_fieldresolved_decimate calls grad3d2, grad3d1, grad3d3, interp1, elliptic3d_cart
bcast_send calls bcast_send1d_23, bcast_send2d_23, bcast_send4d_23, bcast_send3d_23
potential2d_fieldresolved calls potential2d_fieldresolved, elliptic2d_cart
gather_send4d_23 calls gather_send4d_23, mpi_send
grad3d1_curv_23 calls grad3d1_curv_23
gather_send2d_23 calls gather_send2d_23, mpi_send
gather_send3d_23 calls gather_send3d_23, mpi_send
gather_recv calls gather_recv4d_23, gather_recv3d_23, gather_recv2d_23
integral3d1_curv calls integral3d1_curv
grad3d2_curv_23 calls grad3d2_curv_23
potentialbcs2d_fileinput calls interp2, interp1, get_grid2, get_simsize2, date_filename, dateinc
halo calls halo_23
potential2d_polarization calls potential2d_polarization, grad2d1_curv_alt, elliptic2d_polarization, grad2d3
div3d_curv_23 calls div3d_curv_23
interp2 calls interp2
gather_recv4d_23 calls gather_recv4d_23, mpi_recv, slabinds
gather_recv3d_23 calls gather_recv3d_23, mpi_recv, slabinds
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
gather_recv2d_23 calls gather_recv2d_23, mpi_recv, slabinds
elliptic3d_cart calls elliptic3d_cart, check_mumps_status, quiet_mumps, mumps_exec, mumps_perm
get_grid2 calls get_grid2
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
halo_23 calls halo_23, mpi_irecv, grid2id, mpi_isend, mpi_waitall
get_simsize2 calls get_simsize2
date_filename calls utsec2filestem
dateinc calls day_wrap
elliptic2d_cart calls elliptic2d_cart, check_mumps_status, quiet_mumps, mumps_exec, mumps_perm
grad2d1_curv_alt calls grad2d1_curv_alt_23
elliptic2d_polarization calls elliptic2d_polarization, check_mumps_status, quiet_mumps, mumps_exec, mumps_perm
grad2d3 calls grad2d3_curv_23
elliptic2d_polarization_periodic calls elliptic2d_polarization_periodic, check_mumps_status, quiet_mumps, mumps_exec, mumps_perm
day_wrap calls day_wrap, daysmonth
utsec2filestem calls day_wrap
slabinds calls id2grid
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics