elliptic_workers – GEMINI3D
elliptic_workers Subroutine
14 statements
Source File
public subroutine elliptic_workers()
ALLOWS WORKERS TO ENTER MUMPS SOLVES
Arguments
None
Calls
Called by
Contents
None
Call graph
elliptic_workers calls mumps_exec, check_mumps_status, quiet_mumps
test_potential2d calls elliptic_workers
potential_workers_mpi calls elliptic_workers, potential_workers_mpi
electrodynamics_curv calls potential_workers_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics