elliptic2D_polarization – GEMINI3D
elliptic2D_polarization Module Procedure
267 statements
Source File
module procedure elliptic2D_polarization module function elliptic2D_polarization(srcterm, SigP2, SigP3, SigH, gradSigH2, gradSigH3, Cm, v2, v3, Vminx2, Vmaxx2, Vminx3, Vmaxx3, dt, dx1, dx1i, dx2all, dx2iall, dx3all, dx3iall, Phi0, perflag, it) Interface →
interior+boundary-x3_adj-x2_adj. Note that are 3 sets of entries for each adjacent point note the different conductiances here ot be associated with derivatives in different directions BOTTOM GRID POINTS + CORNER TOP GRID POINTS + CORNER LEFT BOUNDARY RIGHT BOUNDARY INTERIOR LOCATION ix2-1,ix3-2 grid point ix2,ix3-2 grid point bit of intentional code duplication here and in the following sections to keep things organized in a way I can debug... ix2+1,ix3-2 grid point ix2-2,ix3-1 !ix2,ix3-1 grid point in ix2,ix3 equation add in polarziation terms that include previous time step potential at this grid point
ix2+2,ix3-1 grid point ix2-2,ix3 grid point d/dx2(Cmv2d^2/dx2^2(Phi)) term
ix2-1,ix3 grid point !ix2,ix3 grid point (main diagonal) !ix2+1,ix3 grid point !ix2,ix3+1 grid point
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: srcterm
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: SigP2
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: SigP3
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: SigH
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: gradSigH2
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: gradSigH3
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: Cm
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: v2
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: v3
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:) :: Vminx2
real(kind=wp), intent(in), dimension(:) :: Vmaxx2
real(kind=wp), intent(in), dimension(:) :: Vminx3
real(kind=wp), intent(in), dimension(:) :: Vmaxx3
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in), dimension(0:) :: dx1
real(kind=wp), intent(in), dimension(:) :: dx1i
real(kind=wp), intent(in), dimension(0:) :: dx2all
real(kind=wp), intent(in), dimension(:) :: dx2iall
real(kind=wp), intent(in), dimension(0:) :: dx3all
real(kind=wp), intent(in), dimension(:) :: dx3iall
real(kind=wp), intent(in), dimension(:,:) :: Phi0
logical, intent(in) :: perflag
integer, intent(in) :: it
Return Value real(kind=wp), dimension(size(SigP2,1),size(SigP2,2))
Calls
Called by
Contents
None
Call graph
elliptic2d_polarization calls mumps_exec, check_mumps_status, mumps_perm, quiet_mumps, elliptic2d_polarization
test_potential2d calls elliptic2d_polarization
potential2d_polarization calls elliptic2d_polarization, potential2d_polarization
potential_root_mpi_curv calls potential2d_polarization, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics