fang2008 – GEMINI3D
fang2008 Function
18 statements
Source File
public elemental function fang2008(Q0_keV, E0_keV, Tn, massden_gcm3, meanmass_g, g_ms2) result(Qtot)
COMPUTE IONIZATION RATES PER THE FANG 2008 SEMI-EMPIRICAL METHOD. https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2008JA013384
Total Ionization Rate by Precipitating Electrons With a Maxwellian Energy and Isotropic Pitch Angle Distribution
H_cm [centimeters]
Equation (4) Ci COEFFS and SHAPE FUNCTION Equation (7) Equation (6) energy deposition "f" Equation (2) total electron impact ionization rate [cm^-3 s^-1]
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: Q0_keV
real(kind=wp), intent(in) :: E0_keV
real(kind=wp), intent(in) :: Tn
real(kind=wp), intent(in) :: massden_gcm3
real(kind=wp), intent(in) :: meanmass_g
real(kind=wp), intent(in) :: g_ms2
Return Value real(kind=wp)
Called by
Contents
None
Call graph
ionrate_fang08 calls fang2008
ionization_fang2008 calls fang2008
fluid_adv calls ionrate_fang08
test_fang calls ionization_fang2008