fluid_adv – GEMINI3D
fluid_adv Subroutine
221 statements
Source File
public subroutine fluid_adv(ns, vs1, Ts, vs2, vs3, J1, E1, Teinf, t, dt, x, nn, vn1, vn2, vn3, Tn, iver, f107, f107a, ymd, UTsec, flagprecfile, dtprec, precdir, flagglow, dtglow)
now add in photoionization sources enforce minimum production rate to preserve conditioning for species that rely on constant production testing should probably be done to see what the best choice is...
thermal electron heating rate from Swartz and Nisbet, (1978)
photoion ionrate and heating calculated seperately, added together with ionrate and heating from Fang or GLOW
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: Ts
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs3
real(kind=wp), intent(in), dimension(:,:,:) :: J1
real(kind=wp), intent(inout), dimension(:,:,:) :: E1
real(kind=wp), intent(in) :: Teinf
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in) :: dt
type(curvmesh), intent(in) :: x
real(kind=wp), intent(in), dimension(:,:,:,:) :: nn
real(kind=wp), intent(in), dimension(:,:,:) :: vn1
real(kind=wp), intent(in), dimension(:,:,:) :: vn2
real(kind=wp), intent(in), dimension(:,:,:) :: vn3
real(kind=wp), intent(in), dimension(:,:,:) :: Tn
real(kind=wp), intent(out), dimension(:,:,:) :: iver
real(kind=wp), intent(in) :: f107
real(kind=wp), intent(in) :: f107a
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
integer, intent(in) :: flagprecfile
real(kind=wp), intent(in) :: dtprec
character(len=*), intent(in) :: precdir
integer, intent(in) :: flagglow
real(kind=wp), intent(in) :: dtglow
Calls
Contents
None
Call graph
fluid_adv calls etd_uncoupled, srcsmomentum, rk2_prep_mpi, advec_prep_mpi, clean_param, precipbcs_fileinput, ionrate_fang08, eheating, sza, srcscontinuity, div3d, srcsenergy, ionrate_glow98, photoionization, trbdf23d, advec3d_mc_mpi, precipbcs
srcsmomentum calls srcsmomentum_curv
rk2_prep_mpi calls rk2_prep_mpi, halo
advec_prep_mpi calls advec_prep_mpi_23
precipbcs_fileinput calls mpi_recv, interp1, get_grid2, get_simsize2, mpi_send, date_filename, interp2, dateinc
ionrate_fang08 calls fang2008
sza calls doy_calc
div3d calls div3d_curv_23
srcsenergy calls maxwell_colln, coulomb_colln
ionrate_glow98 calls doy_calc
photoionization calls mpi_recv, mpi_send
trbdf23d calls trbdf23d_curv
advec3d_mc_mpi calls advec3d_mc_mpi_curv_23
div3d_curv_23 calls div3d_curv_23
advec_prep_mpi_23 calls halo
get_grid2 calls get_grid2
get_simsize2 calls get_simsize2
doy_calc calls daysmonth
date_filename calls utsec2filestem
interp2 calls interp2
dateinc calls day_wrap
trbdf23d_curv calls trbdf21d
srcsmomentum_curv calls maxwell_colln, coulomb_colln, grad3d1
advec3d_mc_mpi_curv_23 calls advec1d_mc_curv, halo
advec1d_mc_curv calls minmod
day_wrap calls day_wrap, daysmonth
trbdf21d calls gbsv
halo calls halo_23
utsec2filestem calls day_wrap
grad3d1 calls grad3d1_curv_23
halo_23 calls halo_23, mpi_isend, mpi_irecv, grid2id, mpi_waitall
gbsv calls dgbsv, sgbsv
grad3d1_curv_23 calls grad3d1_curv_23