gather_recv4D_23 – GEMINI3D
gather_recv4D_23 Module Procedure
17 statements
Source File
module procedure gather_recv4D_23 module subroutine gather_recv4D_23(param, tag, paramall) Interface →
root records his own piece of the grid into full grid variable
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: param
integer, intent(in) :: tag
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: paramall
Calls
Called by
Contents
None
Call graph
gather_recv4d_23 calls slabinds, mpi_recv, gather_recv4d_23
slabinds calls id2grid
gather_recv calls gather_recv4d_23
output_aur_root calls gather_recv, output_aur_root
output_root_stream_mpi calls gather_recv, output_root_stream_mpi
potential_root_mpi_curv calls gather_recv, potential_root_mpi_curv
output_plasma calls output_root_stream_mpi, output_plasma
output_aur calls output_aur_root, output_aur
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
gemini3d calls output_plasma, output_aur, electrodynamics
electrodynamics calls electrodynamics_curv