gbsv – GEMINI3D
gbsv Subroutine
38 statements
Source File
public subroutine gbsv(A, B, KL, IPIV, INFO)
Arguments
Type Intent Optional Attributes Name
class(*), intent(inout), dimension(:,:) :: A
class(*), intent(inout), dimension(:) :: B
integer, intent(in), optional :: KL
integer, intent(out), optional dimension(:), target :: IPIV
integer, intent(out), optional :: INFO
Calls
Called by
Contents
None
Call graph
gbsv calls dgbsv, sgbsv
backeuler1d calls gbsv
trbdf21d calls gbsv
test_diffusion1d calls backeuler1d, trbdf21d
trbdf23d_curv calls trbdf21d
backeuler3d_curv calls backeuler1d
backeuler3d calls backeuler3d_curv
trbdf23d calls trbdf23d_curv
fluid_adv calls trbdf23d