GLOBE7 – GEMINI3D
GLOBE7 Function
135 statements
Source File
function GLOBE7(YRD, SEC, LAT, LONG, TLOC, F107A, F107, AP, P)
Arguments
Type Intent Optional Attributes Name
real :: YRD
real :: SEC
real :: LAT
real :: LONG
real :: TLOC
real :: F107A
real :: F107
real :: AP
real :: P
Return Value real
Calls
Called by
Contents
Common Blocks
TTEST CSW LPOLY
Common Blocks
common /TTEST/
Type Attributes Name Initial
real :: TINF
real :: GB
real :: ROUT
real :: T(15)
common /CSW/
Type Attributes Name Initial
real :: SW(25)
integer :: ISW
real :: SWC(25)
common /LPOLY/
Type Attributes Name Initial
real :: PLG(9,4)
real :: CTLOC
real :: STLOC
real :: C2TLOC
real :: S2TLOC
real :: C3TLOC
real :: S3TLOC
integer :: IYR
real :: DAY
real :: DF
real :: DFA
real :: APD
real :: APDF
real :: APT(4)
real :: XLONG
Call graph
globe7 calls sw, plg, swc, apt, sumex, sg0, g0, t
gts7 calls globe7
gtd7 calls gts7
gtd7d calls gtd7
ghp7 calls gtd7
neutral_atmos calls gtd7, neutral_atmos
gemini3d calls neutral_atmos