GLOB7S – GEMINI3D
GLOB7S Function
58 statements
Source File
function GLOB7S(P)
Arguments
Type Intent Optional Attributes Name
real :: P
Return Value real
Calls
Called by
Contents
Common Blocks
LPOLY CSW
Common Blocks
common /LPOLY/
Type Attributes Name Initial
real :: PLG(9,4)
real :: CTLOC
real :: STLOC
real :: C2TLOC
real :: S2TLOC
real :: C3TLOC
real :: S3TLOC
integer :: IYR
real :: DAY
real :: DF
real :: DFA
real :: APD
real :: APDF
real :: APT(4)
integer :: LONG
common /CSW/
Type Attributes Name Initial
real :: SW(25)
integer :: ISW
real :: SWC(25)
Call graph
glob7s calls sw, plg, swc, apt, t
gtd7 calls glob7s, gts7
gts7 calls glob7s
gtd7d calls gtd7
ghp7 calls gtd7
neutral_atmos calls gtd7, neutral_atmos
gemini3d calls neutral_atmos