glow_run – GEMINI3D
glow_run Procedure
64 statements
Source File
module procedure glow_run module procedure glow_run()
Set electron energy grid:
Set Maxwellian distribution into phitop array
Hard coded solution, future = pass ec and ef array to maxt assuming > 2 populations Set variables given from GEMINI Convert densities and altitudes into
Call GLOW to calculate ionized and excited species, and airglow emission rates:
Arguments
None
Calls
Contents
None
Call graph
glow_run calls glow, phiwmwm2, w0, zz, ionrate, ztn, zte, egrid, ze, zti, zxden, ts, zo2, alt, ns, sion, znd, zn2, nn, tn, cglow_init, zno, zo, zns