grad3D2_curv_23 – GEMINI3D
grad3D2_curv_23 Module Procedure
32 statements
Source File
module procedure grad3D2_curv_23 module function grad3D2_curv_23(f, x, lbnd1, ubnd1, lbnd2, ubnd2, lbnd3, ubnd3) Interface →
just bail on it and let the user figure it out if a larger dimension was specified for x3 then assume that we are differentiating over x2all and x3all
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: f
type(curvmesh), intent(in) :: x
integer, intent(in) :: lbnd1
integer, intent(in) :: ubnd1
integer, intent(in) :: lbnd2
integer, intent(in) :: ubnd2
integer, intent(in) :: lbnd3
integer, intent(in) :: ubnd3
Return Value real(kind=wp), dimension(1:size(f,1),1:size(f,2),1:size(f,3))
Called by
Contents
None
Call graph
grad3d2_curv_23 calls grad3d2_curv_23
grad3d2 calls grad3d2_curv_23
potential_root_mpi_curv calls grad3d2, potential3d_fieldresolved_decimate, potential_root_mpi_curv
potential_workers_mpi calls grad3d2, potential_workers_mpi
potential3d_fieldresolved_decimate calls grad3d2
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics