gravity_accel – GEMINI3D
gravity_accel Function
4 statements
Source File
public elemental function gravity_accel(alt_km)
computes gravitational acceleration normal to Earth, where up is positive acceleration [m s^-2]
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: alt_km
Return Value real(kind=wp)
Called by
Contents
None
Call graph
ionization_fang2010 calls gravity_accel
ionization_fang2008 calls gravity_accel
test_fang calls ionization_fang2010, ionization_fang2008