grid2ID – GEMINI3D
grid2ID Function
5 statements
Source File
public function grid2ID(i2, i3)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i2
integer, intent(in) :: i3
Return Value integer
Called by
Contents
None
Call graph
halo_23 calls grid2id, halo_23
halo_end_23 calls grid2id, halo_end_23
halo_end calls halo_end_23
halo calls halo_23
halo_pot calls halo
advec_prep_mpi_3 calls halo
advec_prep_mpi_23 calls halo
rk2_prep_mpi calls halo, rk2_prep_mpi
magcalc calls halo_end
advec3d_mc_mpi_curv_23 calls halo
advec_prep_mpi calls advec_prep_mpi_23
potential_root_mpi_curv calls halo_pot, potential_root_mpi_curv
potential_workers_mpi calls halo_pot, potential_workers_mpi
advec3d_mc_mpi calls advec3d_mc_mpi_curv_23
fluid_adv calls rk2_prep_mpi, advec_prep_mpi, advec3d_mc_mpi
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics