gridproj_dneu3D – GEMINI3D
gridproj_dneu3D Subroutine
185 statements
Source File
private subroutine gridproj_dneu3D(dxn, dyn, dzn, meanlat, meanlong, neudir, x)
COMPUTE DISTANCES - ZZZ possibly superfluous for 3D case???
ZZZ end possibly superfluous block of code...
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dxn
real(kind=wp), intent(in) :: dyn
real(kind=wp), intent(in) :: dzn
real(kind=wp), intent(in) :: meanlat
real(kind=wp), intent(in) :: meanlong
character(len=*), intent(in) :: neudir
type(curvmesh), intent(inout) :: x
Calls
Called by
Contents
None
Call graph
gridproj_dneu3d calls mpi_recv, mpi_send, get_simsize3, clear_unitvecs, slabrange
get_simsize3 calls get_simsize3, lx
neutral_perturb_3d calls gridproj_dneu3d
neutral_perturb calls neutral_perturb_3d
gemini3d calls neutral_perturb