gridproj_dneu2D – GEMINI3D
gridproj_dneu2D Subroutine
163 statements
Source File
private subroutine gridproj_dneu2D(dhorzn, dzn, meanlat, meanlong, neudir, flagcart, x)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dhorzn
real(kind=wp), intent(in) :: dzn
real(kind=wp), intent(in) :: meanlat
real(kind=wp), intent(in) :: meanlong
character(len=*), intent(in) :: neudir
logical, intent(in) :: flagcart
type(curvmesh), intent(inout) :: x
Calls
Called by
Contents
None
Call graph
gridproj_dneu2d calls mpi_send, mpi_recv, get_simsize3, clear_unitvecs
get_simsize3 calls get_simsize3, lx
neutral_perturb_cart calls gridproj_dneu2d
neutral_perturb_axisymm calls gridproj_dneu2d
neutral_perturb calls neutral_perturb_cart, neutral_perturb_axisymm
gemini3d calls neutral_perturb