grid_size – GEMINI3D
grid_size Subroutine
40 statements
Source File
public subroutine grid_size(indatsize)
CHECK THE SIZE OF THE GRID TO BE LOADED AND SET SIZES IN THIS MODULE (NOT IN STRUCTURE THOUGH)
DETERMINE THE SIZE OF THE GRID TO BE LOADED check correct number of MPI images. Help avoid confusing errors or bad simulations
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: indatsize
Calls
Called by
Contents
None
Call graph
grid_size calls mpi_send, get_simsize3, mpi_recv
get_simsize3 calls get_simsize3, lx
magcalc calls grid_size
gemini3d calls grid_size