GTD7D – GEMINI3D
GTD7D Subroutine
9 statements
Source File
subroutine GTD7D(IYD, SEC, ALT, GLAT, GLONG, STL, F107A, F107, AP, MASS, D, T)
Arguments
Type Intent Optional Attributes Name
integer :: IYD
real :: SEC
real :: ALT
real :: GLAT
real :: GLONG
real :: STL
real :: F107A
real :: F107
real :: AP
integer :: MASS
real :: D
real :: T
Calls
Contents
Common Blocks
METSEL
Common Blocks
common /METSEL/
Type Attributes Name Initial
integer :: IMR
Call graph
gtd7d calls gtd7
gtd7 calls tgn3, pma, tn1, sw, glob7s, densm, pavgm, glatf, tn3, pdm, vtst7, gts7, tgn2, tgn1, tn2
glob7s calls sw, swc, apt, plg, t
densm calls splini, splint, xs, amax1, spline, zeta, ys
vtst7 calls sw, glatl, stll, swl, fl, fal, swc, secl, apl, gll, iydl, swcl
gts7 calls pma, tn1, sw, glob7s, pdm, vtst7, tgn1, pt, alog, ccor, mt, alpha, ptl, densu, zn1, dnet, scalh, altl, ptm, amod, ps, pd, globe7, ccor2, pdl
splini calls amin1
densu calls splini, splint, xs, amax1, spline, zeta, ys
dnet calls alog
spline calls u
globe7 calls sw, swc, apt, plg, t, sg0, g0, sumex