GTD7 – GEMINI3D
GTD7 Subroutine
114 statements
Source File
subroutine GTD7(IYD, SEC, ALT, GLAT, GLONG, STL, F107A, F107, AP, MASS, D, T)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: IYD
real, intent(in) :: SEC
real, intent(in) :: ALT
real, intent(in) :: GLAT
real, intent(in) :: GLONG
real, intent(in) :: STL
real, intent(in) :: F107A
real, intent(in) :: F107
real, intent(in) :: AP(7)
integer, intent(in) :: MASS
real, intent(out) :: D(9)
real, intent(out) :: T(2)
Calls
Called by
Contents
Common Blocks
GTS3C MESO7 LOWER7 PARM7 DATIM7 DATIME CSW MAVG7 DMIX PARMB METSEL
Common Blocks
common /GTS3C/
Type Attributes Name Initial
real :: TLB
real :: S
real :: DB04
real :: DB16
real :: DB28
real :: DB32
real :: DB40
real :: DB48
real :: DB01
real :: ZA
real :: T0
real :: Z0
real :: G0
real :: RL
real :: DD
real :: DB14
real :: TR12
common /MESO7/
Type Attributes Name Initial
real :: TN1(5)
real :: TN2(4)
real :: TN3(5)
real :: TGN1(2)
real :: TGN2(2)
real :: TGN3(2)
common /LOWER7/
Type Attributes Name Initial
real :: PTM(10)
real :: PDM(10,8)
common /PARM7/
Type Attributes Name Initial
real :: PT(150)
real :: PD(150,9)
real :: PS(150)
real :: PDL(25,2)
real :: PTL(100,4)
real :: PMA(100,10)
real :: SAM(100)
common /DATIM7/
Type Attributes Name Initial
integer :: ISD
integer :: IST
integer :: NAM
common /DATIME/
Type Attributes Name Initial
integer :: ISDATE
integer :: ISTIME
integer :: NAME
common /CSW/
Type Attributes Name Initial
real :: SW(25)
integer :: ISW
real :: SWC(25)
common /MAVG7/
Type Attributes Name Initial
real :: PAVGM(10)
common /DMIX/
Type Attributes Name Initial
real :: DM04
real :: DM16
real :: DM28
real :: DM32
real :: DM40
real :: DM01
real :: DM14
common /PARMB/
Type Attributes Name Initial
real :: GSURF
real :: RE
common /METSEL/
Type Attributes Name Initial
integer :: IMR
Call graph
gtd7 calls tgn3, pma, tn1, sw, glob7s, densm, pavgm, glatf, tn3, pdm, vtst7, gts7, tgn2, tgn1, tn2
glob7s calls sw, swc, apt, plg, t
densm calls splini, splint, xs, amax1, spline, zeta, ys
vtst7 calls sw, glatl, stll, swl, fl, fal, swc, secl, apl, gll, iydl, swcl
gts7 calls pma, tn1, sw, glob7s, pdm, vtst7, tgn1, pt, alog, ccor, mt, alpha, ptl, densu, zn1, dnet, scalh, altl, ptm, amod, ps, pd, globe7, ccor2, pdl
splini calls amin1
densu calls splini, splint, xs, amax1, spline, zeta, ys
dnet calls alog
spline calls u
globe7 calls sw, swc, apt, plg, t, sg0, g0, sumex
gtd7d calls gtd7
ghp7 calls gtd7
neutral_atmos calls gtd7, neutral_atmos
gemini3d calls neutral_atmos