GTS7 – GEMINI3D
GTS7 Subroutine
234 statements
Source File
subroutine GTS7(IYD, SEC, ALT, GLAT, GLONG, STL, F107A, F107, AP, MASS, D, T)
Arguments
Type Intent Optional Attributes Name
integer :: IYD
real :: SEC
real :: ALT
real :: GLAT
real :: GLONG
real :: STL
real :: F107A
real :: F107
real :: AP
integer :: MASS
real :: D
real :: T
Calls
Called by
Contents
Common Blocks
GTS3C MESO7 LOWER7 PARM7 CSW TTEST DMIX METSEL
Common Blocks
common /GTS3C/
Type Attributes Name Initial
real :: TLB
real :: S
real :: DB04
real :: DB16
real :: DB28
real :: DB32
real :: DB40
real :: DB48
real :: DB01
real :: ZA
real :: T0
real :: Z0
real :: G0
real :: RL
real :: DD
real :: DB14
real :: TR12
common /MESO7/
Type Attributes Name Initial
real :: TN1(5)
real :: TN2(4)
real :: TN3(5)
real :: TGN1(2)
real :: TGN2(2)
real :: TGN3(2)
common /LOWER7/
Type Attributes Name Initial
real :: PTM(10)
real :: PDM(10,8)
common /PARM7/
Type Attributes Name Initial
real :: PT(150)
real :: PD(150,9)
real :: PS(150)
real :: PDL(25,2)
real :: PTL(100,4)
real :: PMA(100,10)
real :: SAM(100)
common /CSW/
Type Attributes Name Initial
real :: SW(25)
integer :: ISW
real :: SWC(25)
common /TTEST/
Type Attributes Name Initial
real :: TINFG
real :: GB
real :: ROUT
real :: TT(15)
common /DMIX/
Type Attributes Name Initial
real :: DM04
real :: DM16
real :: DM28
real :: DM32
real :: DM40
real :: DM01
real :: DM14
common /METSEL/
Type Attributes Name Initial
integer :: IMR
Call graph
gts7 calls pma, pt, sw, glob7s, alog, ccor, mt, alpha, ptl, densu, zn1, dnet, tn1, scalh, altl, ptm, amod, pdm, ps, pd, tgn1, globe7, ccor2, pdl, vtst7
glob7s calls sw, swc, apt, plg, t
densu calls splini, splint, xs, amax1, spline, zeta, ys
dnet calls alog
globe7 calls sw, sumex, swc, apt, sg0, plg, g0, t
vtst7 calls sw, glatl, stll, swl, fl, fal, swc, secl, apl, gll, iydl, swcl
splini calls amin1
spline calls u
gtd7 calls gts7
gtd7d calls gtd7
ghp7 calls gtd7
neutral_atmos calls gtd7, neutral_atmos
gemini3d calls neutral_atmos