halo_end_23 – GEMINI3D
halo_end_23 Module Procedure
77 statements
Source File
module procedure halo_end_23 module subroutine halo_end_23(param, paramend, paramtop, tag) Interface →
GENERIC HALOING ROUTINE WHICH PASSES THE BEGINNING OF THE SLAB TO ITS LEFTWARD (IN X3) NEIGHBOR SO THAT X3 INTEGRATIONS CAN BE DONE PROPERLY. PRESENTLY THIS IS JUST USED IN MAGCALC
make sure we actually need to pass in this direction, viz. we aren't both the beginning and thend
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(:,:,:) :: param
real(kind=wp), intent(out), dimension(:,:) :: paramend
real(kind=wp), intent(out), dimension(:,:) :: paramtop
integer, intent(in) :: tag
Calls
Called by
Contents
None
Call graph
halo_end_23 calls mpi_irecv, grid2id, mpi_waitall, mpi_isend, halo_end_23
halo_end calls halo_end_23
magcalc calls halo_end