halo_pot – GEMINI3D
halo_pot Subroutine
40 statements
Source File
public subroutine halo_pot(parmhalo, tagcurrent, flagper, flagdegrade)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:) :: parmhalo
integer, intent(in) :: tagcurrent
logical, intent(in) :: flagper
logical, intent(in) :: flagdegrade
Calls
Called by
Contents
None
Call graph
halo_pot calls halo
halo calls halo_23
halo_23 calls halo_23, mpi_isend, mpi_irecv, grid2id, mpi_waitall
potential_root_mpi_curv calls halo_pot, potential_root_mpi_curv
potential_workers_mpi calls halo_pot, potential_workers_mpi
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics