ID2grid – GEMINI3D
ID2grid Function
6 statements
Source File
public function ID2grid(ID)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ID
Return Value integer, dimension(2)
Called by
Contents
None
Call graph
bcast_send1d_23_3 calls id2grid, bcast_send1d_23_3
mpi_manualgrid calls id2grid
slabinds calls id2grid
bcast_send1d_23_2 calls id2grid, bcast_send1d_23_2
mpigrid calls id2grid
bcast_send3d_x3i_23 calls slabinds, bcast_send3d_x3i_23
gather_recv3d_23 calls slabinds, gather_recv3d_23
gemini3d calls mpi_manualgrid, mpigrid, read_grid, input_plasma, output_plasma, output_aur, electrodynamics
gather_recv4d_23 calls slabinds, gather_recv4d_23
bcast_send4d_23 calls slabinds, bcast_send4d_23
bcast_send3d_23 calls slabinds, bcast_send3d_23
bcast_send2d_23 calls slabinds, bcast_send2d_23
bcast_send3d_x2i_23 calls slabinds, bcast_send3d_x2i_23
gather_recv2d_23 calls slabinds, gather_recv2d_23
magcalc calls mpi_manualgrid, mpigrid, read_grid, input_plasma_currents
bcast_send3d_ghost_23 calls slabinds, bcast_send3d_ghost_23
bcast_send1d_3 calls bcast_send1d_23_3
bcast_send1d_2 calls bcast_send1d_23_2
gather_recv calls gather_recv3d_23, gather_recv2d_23, gather_recv4d_23
bcast_send3d_x2i calls bcast_send3d_x2i_23
bcast_send calls bcast_send3d_23, bcast_send2d_23, bcast_send4d_23
read_grid_root calls bcast_send1d_3, bcast_send1d_2, bcast_send3d_x2i, bcast_send, bcast_send3d_x3i, bcast_send3d_ghost
bcast_send3d_x3i calls bcast_send3d_x3i_23
bcast_send3d_ghost calls bcast_send3d_ghost_23
output_aur_root calls gather_recv, output_aur_root
input_root_mpi calls bcast_send, input_root_mpi
output_root_stream_mpi calls gather_recv, output_root_stream_mpi
potential_root_mpi_curv calls gather_recv, bcast_send, potential_root_mpi_curv
input_root_currents calls bcast_send, input_root_currents
read_grid calls read_grid_root, read_grid
input_plasma calls input_root_mpi, input_plasma
output_aur calls output_aur_root, output_aur
potential_root_mpi calls potential_root_mpi_curv
output_plasma calls output_root_stream_mpi, output_plasma
input_plasma_currents calls input_root_currents, input_plasma_currents
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv