input_root_mpi – GEMINI3D
input_root_mpi Module Procedure
66 statements
Source File
module procedure input_root_mpi module subroutine input_root_mpi(x1, x2all, x3all, indatsize, ns, vs1, Ts) Interface →
READ INPUT FROM FILE AND DISTRIBUTE TO WORKERS. STATE VARS ARE EXPECTED INCLUDE GHOST CELLS. NOTE ALSO THAT RECORD-BASED INPUT IS USED SO NO FILES > 2GB DUE TO GFORTRAN BUG WHICH DISALLOWS 8 BYTE INTEGER RECORD LENGTHS.
so that random values (including NaN) don't show up in Ghost cells SYSTEM SIZES READ IN FROM FILE, AS OF CURVILINEAR BRANCH THIS IS NOW THE ONLY INPUT OPTION NOTE: workaround for intel 2020 segfault--may be a compiler bug end workaround permute the dimensions so that 2D runs are parallelized Sanity checks USER SUPPLIED FUNCTION TO TAKE A REFERENCE PROFILE AND CREATE INITIAL CONDITIONS FOR ENTIRE GRID. ASSUMING THAT THE INPUT DATA ARE EXACTLY THE CORRECT SIZE (AS IS THE CASE WITH FILE INPUT) THIS IS NOW SUPERFLUOUS ROOT BROADCASTS IC DATA TO WORKERS
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-1:) :: x1
real(kind=wp), intent(in), dimension(-1:) :: x2all
real(kind=wp), intent(in), dimension(-1:) :: x3all
character(len=*), intent(in) :: indatsize
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: Ts
Calls
Called by
Contents
None
Call graph
input_root_mpi calls tmp, get_simsize3, bcast_send, input_root_mpi
get_simsize3 calls get_simsize3, lx
bcast_send calls bcast_send3d_23, bcast_send2d_23, bcast_send4d_23, bcast_send1d_23
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
slabinds calls id2grid
input_plasma calls input_root_mpi, input_plasma
gemini3d calls input_plasma