input_workers_currents – GEMINI3D
input_workers_currents Subroutine
6 statements
Source File
subroutine input_workers_currents(J1, J2, J3)
WORKER INPUT FUNCTIONS FOR GETTING CURRENT DENSITIES
ALL WE HAVE TO DO IS WAIT TO RECEIVE OUR PIECE OF DATA FROM ROOT
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(:,:,:) :: J1
real(kind=wp), intent(out), dimension(:,:,:) :: J2
real(kind=wp), intent(out), dimension(:,:,:) :: J3
Calls
Called by
Contents
None
Call graph
input_workers_currents calls bcast_recv
bcast_recv calls bcast_recv1d_23, bcast_recv4d_23, bcast_recv3d_23, bcast_recv2d_23
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
input_plasma_currents calls input_workers_currents, input_plasma_currents
magcalc calls input_plasma_currents