input_workers_mpi – GEMINI3D
input_workers_mpi Subroutine
12 statements
Source File
subroutine input_workers_mpi(ns, vs1, Ts)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: Ts
Calls
Called by
Contents
None
Call graph
input_workers_mpi calls bcast_recv
bcast_recv calls bcast_recv1d_23, bcast_recv4d_23, bcast_recv3d_23, bcast_recv2d_23
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
input_plasma calls input_workers_mpi, input_plasma
gemini3d calls input_plasma