input_plasma_currents – GEMINI3D
input_plasma_currents Module Procedure
8 statements
Source File
module procedure input_plasma_currents module subroutine input_plasma_currents(outdir, flagoutput, ymd, UTsec, J1, J2, J3) Interface →
READS, AS INPUT, A FILE GENERATED BY THE GEMINI.F90 PROGRAM. THIS SUBROUTINE IS A WRAPPER FOR SEPARATE ROOT/WORKER CALLS
ROOT FINDS/CALCULATES INITIAL CONDITIONS AND SENDS TO WORKERS WORKERS RECEIVE THE IC DATA FROM ROOT
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: outdir
integer, intent(in) :: flagoutput
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
real(kind=wp), intent(out), dimension(:,:,:) :: J1
real(kind=wp), intent(out), dimension(:,:,:) :: J2
real(kind=wp), intent(out), dimension(:,:,:) :: J3
Calls
Called by
Contents
None
Call graph
input_plasma_currents calls input_root_currents, input_workers_currents, input_plasma_currents
input_root_currents calls input_root_currents, bcast_send, date_filename
input_workers_currents calls bcast_recv
bcast_recv calls bcast_recv4d_23, bcast_recv3d_23, bcast_recv2d_23, bcast_recv1d_23
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
bcast_send calls bcast_send3d_23, bcast_send2d_23, bcast_send4d_23, bcast_send1d_23
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
date_filename calls utsec2filestem
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
utsec2filestem calls day_wrap
day_wrap calls day_wrap, daysmonth
slabinds calls id2grid
magcalc calls input_plasma_currents