input_root_currents – GEMINI3D
input_root_currents Module Procedure
32 statements
Source File
module procedure input_root_currents module subroutine input_root_currents(outdir, flagoutput, ymd, UTsec, J1, J2, J3) Interface →
READS, AS INPUT, A FILE GENERATED BY THE GEMINI.F90 PROGRAM
CHECK TO MAKE SURE WE ACTUALLY HAVE THE DATA WE NEED TO DO THE MAG COMPUTATIONS.
FORM THE INPUT FILE NAME LOAD THE DATA PERMUTE THE ARRAYS IF NECESSARY no need to permute dimensions for 3D simulations DISTRIBUTE DATA TO WORKERS AND TAKE A PIECE FOR ROOT
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: outdir
integer, intent(in) :: flagoutput
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
real(kind=wp), intent(out), dimension(:,:,:) :: J1
real(kind=wp), intent(out), dimension(:,:,:) :: J2
real(kind=wp), intent(out), dimension(:,:,:) :: J3
Calls
Called by
Contents
None
Call graph
input_root_currents calls date_filename, bcast_send, input_root_currents
date_filename calls utsec2filestem
bcast_send calls bcast_send3d_23, bcast_send2d_23, bcast_send4d_23, bcast_send1d_23
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
utsec2filestem calls day_wrap
day_wrap calls day_wrap, daysmonth
slabinds calls id2grid
input_plasma_currents calls input_root_currents, input_plasma_currents
magcalc calls input_plasma_currents