input_plasma – GEMINI3D
input_plasma Module Procedure
7 statements
Source File
module procedure input_plasma module subroutine input_plasma(x1, x2, x3all, indatsize, ns, vs1, Ts) Interface →
A BASIC WRAPPER FOR THE ROOT AND WORKER INPUT FUNCTIONS BOTH ROOT AND WORKERS CALL THIS PROCEDURE SO UNALLOCATED VARIABLES MUST BE DECLARED AS ALLOCATABLE, INTENT(INOUT)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-1:) :: x1
real(kind=wp), intent(in), dimension(-1:) :: x2
real(kind=wp), intent(in), dimension(-1:) :: x3all
character(len=*), intent(in) :: indatsize
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(out), dimension(-1:,-1:,-1:,:) :: Ts
Calls
Called by
Contents
None
Call graph
input_plasma calls input_workers_mpi, input_root_mpi, input_plasma
input_workers_mpi calls bcast_recv
input_root_mpi calls input_root_mpi, tmp, bcast_send, get_simsize3
bcast_recv calls bcast_recv4d_23, bcast_recv3d_23, bcast_recv2d_23, bcast_recv1d_23
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
bcast_send calls bcast_send3d_23, bcast_send2d_23, bcast_send4d_23, bcast_send1d_23
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
get_simsize3 calls get_simsize3, lx
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
slabinds calls id2grid
gemini3d calls input_plasma