interp1 – GEMINI3D
interp1 Function
42 statements
Source File
public pure function interp1(x1, f, x1i)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x1
real(kind=wp), intent(in), dimension(:) :: f
real(kind=wp), intent(in), dimension(:) :: x1i
Return Value real(kind=wp)
Called by
Contents
None
Call graph
potentialbcs2d_fileinput calls interp1
precipbcs_fileinput calls interp1
potential3d_fieldresolved_decimate calls interp1
test_interp1 calls interp1
potential_root_mpi_curv calls potentialbcs2d_fileinput, potential3d_fieldresolved_decimate, potential_root_mpi_curv
fluid_adv calls precipbcs_fileinput
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics