interp2 – GEMINI3D
interp2 Module Procedure
66 statements
Source File
module procedure interp2 pure module function interp2(x1, x2, f, x1i, x2i) Interface →
A 2D BILINEAR INTERPOLATION FUNCTION. THIS VERSION ASSUMES THAT THE LIST OF OUTPUT POINTS IS A 'FLAT LIST' RATHER THAN DESCRIPTIVE OF A 2D MESHGRID.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x1
real(kind=wp), intent(in), dimension(:) :: x2
real(kind=wp), intent(in), dimension(:,:) :: f
real(kind=wp), intent(in), dimension(:) :: x1i
real(kind=wp), intent(in), dimension(:) :: x2i
Return Value real(kind=wp) (1:size(x1i,1))
Called by
Contents
None
Call graph
interp2 calls interp2
potentialbcs2d_fileinput calls interp2
precipbcs_fileinput calls interp2
spaceinterp_dneu2d calls interp2
test_interp2 calls interp2
neutral_perturb_cart calls spaceinterp_dneu2d
neutral_perturb_axisymm calls spaceinterp_dneu2d
potential_root_mpi_curv calls potentialbcs2d_fileinput, potential_root_mpi_curv
fluid_adv calls precipbcs_fileinput
neutral_perturb calls neutral_perturb_cart, neutral_perturb_axisymm
potential_root_mpi calls potential_root_mpi_curv
gemini3d calls neutral_perturb, electrodynamics
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv