interp3 – GEMINI3D
interp3 Function
99 statements
Source File
public pure function interp3(x1, x2, x3, f, x1i, x2i, x3i)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x1
real(kind=wp), intent(in), dimension(:) :: x2
real(kind=wp), intent(in), dimension(:) :: x3
real(kind=wp), intent(in), dimension(:,:,:) :: f
real(kind=wp), intent(in), dimension(:) :: x1i
real(kind=wp), intent(in), dimension(:) :: x2i
real(kind=wp), intent(in), dimension(:) :: x3i
Return Value real(kind=wp)
Called by
Contents
None
Call graph
spaceinterp_dneu3d calls interp3
testinterp3 calls interp3
neutral_perturb_3d calls spaceinterp_dneu3d
neutral_perturb calls neutral_perturb_3d
gemini3d calls neutral_perturb