ionization_fang2008 – GEMINI3D
ionization_fang2008 Function
15 statements
Source File
public impure elemental function ionization_fang2008(Q0_erg, E0_keV, alt_km, f107, f107a, Ap, glat, glon, doy, UTsec) result(Qtot)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: Q0_erg
real(kind=wp), intent(in) :: E0_keV
real(kind=wp), intent(in) :: alt_km
real(kind=wp), intent(in) :: f107
real(kind=wp), intent(in) :: f107a
real(kind=wp), intent(in) :: Ap
real(kind=wp), intent(in) :: glat
real(kind=wp), intent(in) :: glon
integer, intent(in) :: doy
real(kind=wp), intent(in) :: UTsec
Return Value real(kind=wp)
Calls
Called by
Contents
None
Call graph
ionization_fang2008 calls meters, gravity_accel, fang2008, tselec
tselec calls sw, sav, swc, svv, amod
test_fang calls ionization_fang2008