maxwell_colln – GEMINI3D
maxwell_colln Subroutine
41 statements
Source File
public subroutine maxwell_colln(isp, isp2, nn, Tn, Ts, nusn)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: isp
integer, intent(in) :: isp2
real(kind=wp), intent(in), dimension(:,:,:,:) :: nn
real(kind=wp), intent(in), dimension(:,:,:) :: Tn
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: Ts
real(kind=wp), intent(out), dimension(1:size(Tn,1),1:size(Tn,2),1:size(Tn,3)) :: nusn
Called by
Contents
None
Call graph
srcsenergy calls maxwell_colln
srcsmomentum_curv calls maxwell_colln
conductivities calls maxwell_colln
srcsmomentum calls srcsmomentum_curv
electrodynamics_curv calls conductivities
fluid_adv calls srcsenergy, srcsmomentum
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics