minmod – GEMINI3D
minmod Function
10 statements
Source File
private elemental function minmod(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a
real(kind=wp), intent(in) :: b
Return Value real(kind=wp)
Called by
Contents
None
Call graph
advec1d_mc_curv calls minmod
advec3d_mc_mpi_curv_23 calls advec1d_mc_curv
advec3d_mc_mpi_curv_3 calls advec1d_mc_curv
advec3d_mc_mpi calls advec3d_mc_mpi_curv_23
fluid_adv calls advec3d_mc_mpi