minmod – GEMINI3D
minmod Function
10 statements
Source File
public elemental function minmod(a, b)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a
real(kind=wp), intent(in) :: b
Return Value real(kind=wp)
Called by
Contents
None
Call graph
advec1d_mc calls minmod
advec3d_mc calls advec1d_mc
mhd1d_snd calls advec1d_mc
mhd1d_saw calls advec1d_mc
advec2d_mc calls advec1d_mc
mhd1d_shock calls advec1d_mc