neutral_perturb – GEMINI3D
neutral_perturb Subroutine
22 statements
Source File
public subroutine neutral_perturb(interptype, dt, dtneu, t, ymd, UTsec, neudir, dxn, drhon, dzn, meanlat, meanlong, x, nn, Tn, vn1, vn2, vn3)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: interptype
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in) :: dtneu
real(kind=wp), intent(in) :: t
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
character(len=*), intent(in) :: neudir
real(kind=wp), intent(in) :: dxn
real(kind=wp), intent(in) :: drhon
real(kind=wp), intent(in) :: dzn
real(kind=wp), intent(in) :: meanlat
real(kind=wp), intent(in) :: meanlong
type(curvmesh), intent(inout) :: x
real(kind=wp), intent(out), dimension(:,:,:,:) :: nn
real(kind=wp), intent(out), dimension(:,:,:) :: Tn
real(kind=wp), intent(out), dimension(:,:,:) :: vn1
real(kind=wp), intent(out), dimension(:,:,:) :: vn2
real(kind=wp), intent(out), dimension(:,:,:) :: vn3
Calls
Called by
Contents
None
Call graph
neutral_perturb calls neutral_perturb_cart, neutral_perturb_axisymm, neutral_perturb_3d
neutral_perturb_cart calls timeinterp_dneu, spaceinterp_dneu2d, gridproj_dneu2d, read_dneu2d
neutral_perturb_axisymm calls timeinterp_dneu, spaceinterp_dneu2d, gridproj_dneu2d, read_dneu2d
neutral_perturb_3d calls timeinterp_dneu, gridproj_dneu3d, spaceinterp_dneu3d, read_dneu3d
gridproj_dneu3d calls mpi_recv, mpi_send, get_simsize3, clear_unitvecs, slabrange
spaceinterp_dneu3d calls interp3
spaceinterp_dneu2d calls interp2
read_dneu3d calls mpi_recv, date_filename, dateinc
gridproj_dneu2d calls mpi_recv, mpi_send, get_simsize3, clear_unitvecs
read_dneu2d calls mpi_recv, mpi_send, date_filename, dateinc
interp2 calls interp2
date_filename calls utsec2filestem
dateinc calls day_wrap
get_simsize3 calls get_simsize3, lx
day_wrap calls day_wrap, daysmonth
utsec2filestem calls day_wrap
gemini3d calls neutral_perturb