neutral_atmos – GEMINI3D
neutral_atmos Module Procedure
50 statements
Source File
module procedure neutral_atmos module subroutine neutral_atmos(ymd, UTsecd, glat, glon, alt, activ, nn, Tn) Interface →
subroutine neutral_atmos(ymd,UTsecd,glat,glon,alt,activ,nn,Tn) CALL NRL-MSISE-00 AND ORGANIZE THE RESULTS. APPEND OTHER AUXILIARY NEUTRAL DENSITY DATA USED BY MAIN CODE
CONVERT DATE INFO INTO EXPECTED FORM AND KIND ITERATED LAT, LON, ALT DATA UPDATE THE REFERENCE ATMOSPHERE VALUES
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ymd(3)
real(kind=wp), intent(in) :: UTsecd
real(kind=wp), intent(in), dimension(:,:,:) :: glat
real(kind=wp), intent(in), dimension(:,:,:) :: glon
real(kind=wp), intent(in), dimension(:,:,:) :: alt
real(kind=wp), intent(in) :: activ(3)
real(kind=wp), intent(out), dimension(1:size(alt,1),1:size(alt,2),1:size(alt,3),lnchem) :: nn
real(kind=wp), intent(out), dimension(1:size(alt,1),1:size(alt,2),1:size(alt,3)) :: Tn
Calls
Called by
Contents
None
Call graph
neutral_atmos calls meters, gtd7, doy_calc, neutral_atmos
gtd7 calls tgn3, pma, tn1, sw, glob7s, densm, pavgm, glatf, tn3, pdm, vtst7, gts7, tgn2, tgn1, tn2
doy_calc calls daysmonth
glob7s calls sw, swc, apt, plg, t
densm calls splini, splint, xs, amax1, spline, zeta, ys
vtst7 calls sw, glatl, stll, swl, fl, fal, swc, secl, apl, gll, iydl, swcl
gts7 calls pma, tn1, sw, glob7s, pdm, vtst7, tgn1, pt, alog, ccor, mt, alpha, ptl, densu, zn1, dnet, scalh, altl, ptm, amod, ps, pd, globe7, ccor2, pdl
splini calls amin1
densu calls splini, splint, xs, amax1, spline, zeta, ys
dnet calls alog
spline calls u
globe7 calls sw, swc, apt, plg, t, sg0, g0, sumex
gemini3d calls neutral_atmos