neutral_perturb_axisymm – GEMINI3D
neutral_perturb_axisymm Subroutine
48 statements
Source File
private subroutine neutral_perturb_axisymm(dt, dtneu, t, ymd, UTsec, neudir, drhon, dzn, meanlat, meanlong, x, nn, Tn, vn1, vn2, vn3)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in) :: dtneu
real(kind=wp), intent(in) :: t
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
character(len=*), intent(in) :: neudir
real(kind=wp), intent(in) :: drhon
real(kind=wp), intent(in) :: dzn
real(kind=wp), intent(in) :: meanlat
real(kind=wp), intent(in) :: meanlong
type(curvmesh), intent(inout) :: x
real(kind=wp), intent(out), dimension(:,:,:,:) :: nn
real(kind=wp), intent(out), dimension(:,:,:) :: Tn
real(kind=wp), intent(out), dimension(:,:,:) :: vn1
real(kind=wp), intent(out), dimension(:,:,:) :: vn2
real(kind=wp), intent(out), dimension(:,:,:) :: vn3
Calls
Called by
Contents
None
Call graph
neutral_perturb_axisymm calls timeinterp_dneu, spaceinterp_dneu2d, read_dneu2d, gridproj_dneu2d
spaceinterp_dneu2d calls interp2
read_dneu2d calls mpi_recv, date_filename, mpi_send, dateinc
gridproj_dneu2d calls mpi_recv, mpi_send, get_simsize3, clear_unitvecs
date_filename calls utsec2filestem
interp2 calls interp2
dateinc calls day_wrap
get_simsize3 calls get_simsize3, lx
utsec2filestem calls day_wrap
day_wrap calls day_wrap, daysmonth
neutral_perturb calls neutral_perturb_axisymm
gemini3d calls neutral_perturb