neutral_perturb_3D – GEMINI3D
neutral_perturb_3D Subroutine
68 statements
Source File
private subroutine neutral_perturb_3D(dt, dtneu, t, ymd, UTsec, neudir, dxn, dyn, dzn, meanlat, meanlong, x, nn, Tn, vn1, vn2, vn3)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in) :: dtneu
real(kind=wp), intent(in) :: t
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
character(len=*), intent(in) :: neudir
real(kind=wp), intent(in) :: dxn
real(kind=wp), intent(in) :: dyn
real(kind=wp), intent(in) :: dzn
real(kind=wp), intent(in) :: meanlat
real(kind=wp), intent(in) :: meanlong
type(curvmesh), intent(inout) :: x
real(kind=wp), intent(out), dimension(:,:,:,:) :: nn
real(kind=wp), intent(out), dimension(:,:,:) :: Tn
real(kind=wp), intent(out), dimension(:,:,:) :: vn1
real(kind=wp), intent(out), dimension(:,:,:) :: vn2
real(kind=wp), intent(out), dimension(:,:,:) :: vn3
Calls
Called by
Contents
None
Call graph
neutral_perturb_3d calls spaceinterp_dneu3d, timeinterp_dneu, gridproj_dneu3d, read_dneu3d
spaceinterp_dneu3d calls interp3
gridproj_dneu3d calls mpi_recv, mpi_send, get_simsize3, clear_unitvecs, slabrange
read_dneu3d calls mpi_recv, date_filename, dateinc
date_filename calls utsec2filestem
dateinc calls day_wrap
get_simsize3 calls get_simsize3, lx
day_wrap calls day_wrap, daysmonth
utsec2filestem calls day_wrap
neutral_perturb calls neutral_perturb_3d
gemini3d calls neutral_perturb