output_plasma – GEMINI3D
output_plasma Module Procedure
7 statements
Source File
module procedure output_plasma module subroutine output_plasma(outdir, flagoutput, ymd, UTsec, vs2, vs3, ns, vs1, Ts, Phiall, J1, J2, J3) Interface →
A BASIC WRAPPER FOR THE ROOT AND WORKER OUTPUT FUNCTIONS BOTH ROOT AND WORKERS CALL THIS PROCEDURE SO UNALLOCATED VARIABLES MUST BE DECLARED AS ALLOCATABLE, INTENT(INOUT)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: outdir
integer, intent(in) :: flagoutput
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs3
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: Ts
real(kind=wp), intent(inout), dimension(:,:,:), allocatable :: Phiall
real(kind=wp), intent(in), dimension(:,:,:) :: J1
real(kind=wp), intent(in), dimension(:,:,:) :: J2
real(kind=wp), intent(in), dimension(:,:,:) :: J3
Calls
Called by
Contents
None
Call graph
output_plasma calls output_root_stream_mpi, output_workers_mpi, output_plasma
output_root_stream_mpi calls output_root_stream_mpi, gather_recv, date_filename
output_workers_mpi calls gather_send
gather_send calls gather_send4d_23, gather_send2d_23, gather_send3d_23
gather_recv calls gather_recv3d_23, gather_recv2d_23, gather_recv4d_23
gather_send4d_23 calls gather_send4d_23, mpi_send
date_filename calls utsec2filestem
gather_send2d_23 calls gather_send2d_23, mpi_send
gather_send3d_23 calls gather_send3d_23, mpi_send
gather_recv3d_23 calls gather_recv3d_23, slabinds, mpi_recv
gather_recv2d_23 calls gather_recv2d_23, slabinds, mpi_recv
gather_recv4d_23 calls gather_recv4d_23, slabinds, mpi_recv
utsec2filestem calls day_wrap
day_wrap calls day_wrap, daysmonth
slabinds calls id2grid
gemini3d calls output_plasma