output_aur_root – GEMINI3D
output_aur_root Procedure
27 statements
Source File
module procedure output_aur_root module procedure output_aur_root()
COLLECT COMPLETE DATA FROM WORKERS AND PROCESS FOR OUTPUT. NO GHOST CELLS (I HOPE)
create an output file write data to file
Arguments
None
Calls
Contents
None
Call graph
output_aur_root calls date_filename, iver, gather_recv
date_filename calls utsec2filestem
gather_recv calls gather_recv3d_23, gather_recv2d_23, gather_recv4d_23
utsec2filestem calls day_wrap
gather_recv3d_23 calls gather_recv3d_23, slabinds, mpi_recv
gather_recv2d_23 calls gather_recv2d_23, slabinds, mpi_recv
gather_recv4d_23 calls gather_recv4d_23, slabinds, mpi_recv
day_wrap calls day_wrap, daysmonth
slabinds calls id2grid