output_workers_mpi – GEMINI3D
output_workers_mpi Subroutine
21 statements
Source File
subroutine output_workers_mpi(vs2, vs3, ns, vs1, Ts, J1, J2, J3)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs3
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: Ts
real(kind=wp), intent(in), dimension(:,:,:) :: J1
real(kind=wp), intent(in), dimension(:,:,:) :: J2
real(kind=wp), intent(in), dimension(:,:,:) :: J3
Calls
Called by
Contents
None
Call graph
output_workers_mpi calls gather_send
gather_send calls gather_send3d_23, gather_send4d_23, gather_send2d_23
gather_send3d_23 calls gather_send3d_23, mpi_send
gather_send4d_23 calls gather_send4d_23, mpi_send
gather_send2d_23 calls gather_send2d_23, mpi_send
output_plasma calls output_workers_mpi, output_plasma
gemini3d calls output_plasma