output_root_stream_mpi – GEMINI3D
output_root_stream_mpi Procedure
125 statements
Source File
module procedure output_root_stream_mpi module procedure output_root_stream_mpi()
COLLECT OUTPUT FROM WORKERS AND WRITE TO A FILE USING STREAM I/O. STATE VARS ARE EXPECTED INCLUDE GHOST CELLS
RADD--- NEED TO ALSO GATHER FULL GRID ELECTRODYANMICS PARAMTERS FROM WORKERS 2D simulation for which arrays were permuted
Arguments
None
Calls
Contents
None
Call graph
output_root_stream_mpi calls gather_recv, ns, date_filename, vs3, vs2, phiall
gather_recv calls gather_recv3d_23, gather_recv2d_23, gather_recv4d_23
date_filename calls utsec2filestem
utsec2filestem calls day_wrap
gather_recv3d_23 calls gather_recv3d_23, slabinds, mpi_recv
gather_recv2d_23 calls gather_recv2d_23, slabinds, mpi_recv
gather_recv4d_23 calls gather_recv4d_23, slabinds, mpi_recv
day_wrap calls day_wrap, daysmonth
slabinds calls id2grid