output_aur_root – GEMINI3D
output_aur_root Module Procedure
26 statements
Source File
module procedure output_aur_root module subroutine output_aur_root(outdir, flagglow, ymd, UTsec, iver) Interface →
COLLECT COMPLETE DATA FROM WORKERS AND PROCESS FOR OUTPUT. NO GHOST CELLS (I HOPE)
create an output file write data to file
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: outdir
integer, intent(in) :: flagglow
integer, intent(in) :: ymd(3)
real(kind=wp), intent(in) :: UTsec
real(kind=wp), intent(in), dimension(:,:,:) :: iver
Calls
Called by
Contents
None
Call graph
output_aur_root calls date_filename, gather_recv, output_aur_root
date_filename calls utsec2filestem
gather_recv calls gather_recv3d_23, gather_recv2d_23, gather_recv4d_23
utsec2filestem calls day_wrap
gather_recv3d_23 calls gather_recv3d_23, slabinds, mpi_recv
gather_recv2d_23 calls gather_recv2d_23, slabinds, mpi_recv
gather_recv4d_23 calls gather_recv4d_23, slabinds, mpi_recv
day_wrap calls day_wrap, daysmonth
slabinds calls id2grid
output_aur calls output_aur_root, output_aur
gemini3d calls output_aur