output_aur_workers – GEMINI3D
output_aur_workers Module Procedure
9 statements
Source File
module procedure output_aur_workers module subroutine output_aur_workers(iver) Interface →
SEND COMPLETE DATA FROM WORKERS TO ROOT PROCESS FOR OUTPUT. NO GHOST CELLS (I HOPE) The mpi'd dimensions are 2 and 3 so lwave needs to be permuted to the first dimension for the canned routines to work.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: iver
Calls
Called by
Contents
None
Call graph
output_aur_workers calls gather_send, output_aur_workers
gather_send calls gather_send3d_23, gather_send4d_23, gather_send2d_23
gather_send3d_23 calls gather_send3d_23, mpi_send
gather_send4d_23 calls gather_send4d_23, mpi_send
gather_send2d_23 calls gather_send2d_23, mpi_send
output_aur calls output_aur_workers, output_aur
gemini3d calls output_aur