output_aur – GEMINI3D
output_aur Module Procedure
7 statements
Source File
module procedure output_aur module subroutine output_aur(outdir, flagglow, ymd, UTsec, iver) Interface →
A BASIC WRAPPER FOR THE ROOT AND WORKER OUTPUT FUNCTIONS BOTH ROOT AND WORKERS CALL THIS PROCEDURE SO UNALLOCATED VARIABLES MUST BE DECLARED AS ALLOCATABLE, INTENT(INOUT)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: outdir
integer, intent(in) :: flagglow
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
real(kind=wp), intent(in), dimension(:,:,:) :: iver
Calls
Called by
Contents
None
Call graph
output_aur calls output_aur_workers, output_aur_root, output_aur
output_aur_workers calls output_aur_workers, gather_send
output_aur_root calls output_aur_root, date_filename, gather_recv
date_filename calls utsec2filestem
gather_recv calls gather_recv3d_23, gather_recv2d_23, gather_recv4d_23
gather_send calls gather_send4d_23, gather_send2d_23, gather_send3d_23
gather_recv3d_23 calls gather_recv3d_23, slabinds, mpi_recv
gather_send4d_23 calls gather_send4d_23, mpi_send
gather_recv2d_23 calls gather_recv2d_23, slabinds, mpi_recv
gather_recv4d_23 calls gather_recv4d_23, slabinds, mpi_recv
gather_send2d_23 calls gather_send2d_23, mpi_send
utsec2filestem calls day_wrap
gather_send3d_23 calls gather_send3d_23, mpi_send
day_wrap calls day_wrap, daysmonth
slabinds calls id2grid
gemini3d calls output_aur