output_root_stream_mpi – GEMINI3D
output_root_stream_mpi Module Procedure
108 statements
Source File
module procedure output_root_stream_mpi module subroutine output_root_stream_mpi(outdir, flagoutput, ymd, UTsec, vs2, vs3, ns, vs1, Ts, Phiall, J1, J2, J3) Interface →
COLLECT OUTPUT FROM WORKERS AND WRITE TO A FILE USING STREAM I/O. STATE VARS ARE EXPECTED INCLUDE GHOST CELLS
RADD--- NEED TO ALSO GATHER FULL GRID ELECTRODYANMICS PARAMTERS FROM WORKERS FIGURE OUT THE FILENAME 2D simulation NOTE: J3,J2 and V3, V2 are swapped in name like this Check for any NaN before proceeding to next time step
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: outdir
integer, intent(in) :: flagoutput
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs3
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: Ts
real(kind=wp), intent(in), dimension(:,:,:) :: Phiall
real(kind=wp), intent(in), dimension(:,:,:) :: J1
real(kind=wp), intent(in), dimension(:,:,:) :: J2
real(kind=wp), intent(in), dimension(:,:,:) :: J3
Calls
Called by
Contents
None
Call graph
output_root_stream_mpi calls date_filename, gather_recv, output_root_stream_mpi
date_filename calls utsec2filestem
gather_recv calls gather_recv3d_23, gather_recv2d_23, gather_recv4d_23
utsec2filestem calls day_wrap
gather_recv3d_23 calls gather_recv3d_23, slabinds, mpi_recv
gather_recv2d_23 calls gather_recv2d_23, slabinds, mpi_recv
gather_recv4d_23 calls gather_recv4d_23, slabinds, mpi_recv
day_wrap calls day_wrap, daysmonth
slabinds calls id2grid
output_plasma calls output_root_stream_mpi, output_plasma
gemini3d calls output_plasma