potential_workers_mpi – GEMINI3D
potential_workers_mpi Module Procedure
248 statements
Source File
module procedure potential_workers_mpi module subroutine potential_workers_mpi(it, t, dt, sig0, sigP, sigH, incap, vs2, vs3, vn2, vn3, sourcemlat, B1, x, potsolve, flagcap, E1, E2, E3, J1, J2, J3) Interface →
ROOT MPI COMM./SOLVE ROUTINE FOR POTENTIAL. THIS VERSION INCLUDES THE POLARIZATION CURRENT TIME DERIVATIVE PART AND CONVECTIVE PARTS IN MATRIX SOLUTION. STATE VARIABLES VS2,3 INCLUDE GHOST CELLS. FOR NOW THE POLARIZATION TERMS ARE PASSED BACK TO MAIN FN, EVEN THOUGH THEY ARE NOT USED (THEY MAY BE IN THE FUTURE)
wind x2 current, note that all workers already have a copy of this. wind x3 current wind x2 current wind x3 current !!!!!!
Neumann conditions; incorporate a source term and execute the solve
workers don't have access to boundary conditions, unless root sends
need to pick out the ExB drift here (i.e. the drifts from highest altitudes); but this is only valid for Cartesian, so it's okay for the foreseeable future
Dirichlet conditions - since this is field integrated we just copy BCs specified by user to other locations along field line
ZZZ - conductivities need to be properly scaled here... So does the source term... Maybe leave as broken for now since I don't really plan to use this code
!!!!!!!
STORE PREVIOUS TIME TOTAL FIELDS BEFORE UPDATING THE ELECTRIC FIELDS WITH NEW POTENTIAL (OLD FIELDS USED TO CALCULATE POLARIZATION CURRENT) causes major memory leak. maybe from arithmetic statement argument? Left here as a 'lesson learned' (or is it a gfortran bug...)
print *, 'Max E2,3 BG and response values are:  ',maxval(abs(E02)), maxval(abs(E03)), maxval(abs(E2)),maxval(abs(E3))
!!!!!!
Neumann conditions, this is boundary location-agnostic since both bottom and top FACs are known - they have to be loaded into VVmaxx1 and Vminx1. For numerical purposes we prefer to integrate from the location of nonzero current (usually highest altitude in open grid). for a cartesian grid in the northern hemisphere (assumed) we have the x1-direction being against the magnetic field...
Dirichlet conditions - we need to integrate from the lowest altitude (where FAC is known to be zero, note this is not necessarilty the logical bottom of the grid), upwards (to where it isn't) !!!!!!!
ZZZ - this rey needsz to be current at the "top"
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: it
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in), dimension(:,:,:) :: sig0
real(kind=wp), intent(in), dimension(:,:,:) :: sigP
real(kind=wp), intent(in), dimension(:,:,:) :: sigH
real(kind=wp), intent(in), dimension(:,:,:) :: incap
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs3
real(kind=wp), intent(in), dimension(:,:,:) :: vn2
real(kind=wp), intent(in), dimension(:,:,:) :: vn3
real(kind=wp), intent(in) :: sourcemlat
real(kind=wp), intent(in), dimension(-1:,-1:,-1:) :: B1
type(curvmesh), intent(in) :: x
integer, intent(in) :: potsolve
integer, intent(in) :: flagcap
real(kind=wp), intent(out), dimension(:,:,:) :: E1
real(kind=wp), intent(out), dimension(:,:,:) :: E2
real(kind=wp), intent(out), dimension(:,:,:) :: E3
real(kind=wp), intent(out), dimension(:,:,:) :: J1
real(kind=wp), intent(out), dimension(:,:,:) :: J2
real(kind=wp), intent(out), dimension(:,:,:) :: J3
Calls
Called by
Contents
None
Call graph
potential_workers_mpi calls bcast_recv, elliptic_workers, mpi_recv, halo_pot, div3d, integral3d1_curv_alt, gather_send, integral3d1, grad3d2, grad3d1, grad3d3, potential_workers_mpi
bcast_recv calls bcast_recv4d_23, bcast_recv3d_23, bcast_recv2d_23, bcast_recv1d_23
elliptic_workers calls mumps_exec, check_mumps_status, quiet_mumps
halo_pot calls halo
div3d calls div3d_curv_23
integral3d1_curv_alt calls integral3d1_curv_alt
gather_send calls gather_send4d_23, gather_send2d_23, gather_send3d_23
integral3d1 calls integral3d1_curv
grad3d2 calls grad3d2_curv_23
grad3d1 calls grad3d1_curv_23
grad3d3 calls grad3d3_curv_23
div3d_curv_23 calls div3d_curv_23
integral3d1_curv calls integral3d1_curv
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
grad3d3_curv_23 calls grad3d3_curv_23
gather_send4d_23 calls gather_send4d_23, mpi_send
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
gather_send2d_23 calls gather_send2d_23, mpi_send
grad3d2_curv_23 calls grad3d2_curv_23
grad3d1_curv_23 calls grad3d1_curv_23
halo calls halo_23
gather_send3d_23 calls gather_send3d_23, mpi_send
halo_23 calls halo_23, mpi_isend, mpi_irecv, grid2id, mpi_waitall
electrodynamics_curv calls potential_workers_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics