potential2D_polarization – GEMINI3D
potential2D_polarization Module Procedure
10 statements
Source File
module procedure potential2D_polarization module function potential2D_polarization(srcterm, SigP2, SigP3, SigH, Cm, v2, v3, Vminx2, Vmaxx2, Vminx3, Vmaxx3, dt, x, Phi0, perflag, it) Interface →
SOLVE IONOSPHERIC POTENTIAL EQUATION IN 2D USING MUMPS INCLUDES FULL OF POLARIZATION CURRENT, INCLUDING CONVECTIVE TERMS. VELOCITIES SHOULD BE TRIMMED (WITHOUT GHOST CELLS). THIS VERSION OF THE INTEGRATED POTENTIAL SOLVER OBVIATES ALL OTHERS SINCE A PURELY ELECTRSTATIC FORM CAN BE RECOVERED BY ZEROING OUT THE INERTIAL CAPACITANCE.
THIS FORM IS INTENDED TO WORK WITH CURVILINEAR MESHES. NOTE THAT THE FULL GRID VARIABLES (X%DX3ALL, ETC.) MUST BE USED HERE!!!
note the alt since we need to use dx2 as differential... Tricky bug/feature awkward way of handling this special case derivative which uses x3 as the differential to operate on a 2D array.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: srcterm
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: SigP2
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: SigP3
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: SigH
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: Cm
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: v2
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:,:) :: v3
ZZZ - THESE WILL NEED TO BE MODIFIED CONDUCTIVITIES, AND WE'LL NEED THREE OF THEM
real(kind=wp), intent(in), dimension(:) :: Vminx2
real(kind=wp), intent(in), dimension(:) :: Vmaxx2
real(kind=wp), intent(in), dimension(:) :: Vminx3
real(kind=wp), intent(in), dimension(:) :: Vmaxx3
real(kind=wp), intent(in) :: dt
type(curvmesh), intent(in) :: x
real(kind=wp), intent(in), dimension(:,:) :: Phi0
logical, intent(in) :: perflag
integer, intent(in) :: it
Return Value real(kind=wp), dimension(size(SigP2,1),size(SigP2,2))
Calls
Called by
Contents
None
Call graph
potential2d_polarization calls grad2d1_curv_alt, grad2d3, elliptic2d_polarization, potential2d_polarization
grad2d1_curv_alt calls grad2d1_curv_alt_23
grad2d3 calls grad2d3_curv_23
elliptic2d_polarization calls elliptic2d_polarization, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
potential_root_mpi_curv calls potential2d_polarization, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics