potential3D_fieldresolved_decimate – GEMINI3D
potential3D_fieldresolved_decimate Function
107 statements
Source File
public function potential3D_fieldresolved_decimate(srcterm, sig0, sigP, sigH, Vminx1, Vmaxx1, Vminx2, Vmaxx2, Vminx3, Vmaxx3, x, flagdirich, perflag, it)
SOLVE IONOSPHERIC POTENTIAL EQUATION IN 3D USING MUMPS ASSUME THAT WE ARE RESOLVING THE POTENTIAL ALONG THE FIELD LINE. THIS IS MOSTLY INEFFICIENT/UNWORKABLE FOR MORE THAN 1M GRID POINTS.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: srcterm
real(kind=wp), intent(in), dimension(:,:,:) :: sig0
real(kind=wp), intent(in), dimension(:,:,:) :: sigP
real(kind=wp), intent(in), dimension(:,:,:) :: sigH
real(kind=wp), intent(in), dimension(:,:) :: Vminx1
real(kind=wp), intent(in), dimension(:,:) :: Vmaxx1
real(kind=wp), intent(in), dimension(:,:) :: Vminx2
real(kind=wp), intent(in), dimension(:,:) :: Vmaxx2
real(kind=wp), intent(in), dimension(:,:) :: Vminx3
real(kind=wp), intent(in), dimension(:,:) :: Vmaxx3
type(curvmesh), intent(in) :: x
integer, intent(in) :: flagdirich
logical, intent(in) :: perflag
integer, intent(in) :: it
Return Value real(kind=wp), dimension(size(srcterm,1),size(srcterm,2),size(srcterm,3))
Calls
Called by
Contents
None
Call graph
potential3d_fieldresolved_decimate calls interp1, elliptic3d_cart, grad3d2, grad3d1, grad3d3
elliptic3d_cart calls elliptic3d_cart, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
grad3d2 calls grad3d2_curv_23
grad3d1 calls grad3d1_curv_23
grad3d3 calls grad3d3_curv_23
grad3d3_curv_23 calls grad3d3_curv_23
grad3d1_curv_23 calls grad3d1_curv_23
grad3d2_curv_23 calls grad3d2_curv_23
potential_root_mpi_curv calls potential3d_fieldresolved_decimate, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics