potentialBCs2D – GEMINI3D
potentialBCs2D Subroutine
44 statements
Source File
public subroutine potentialBCs2D(t, x, Vminx1, Vmaxx1, Vminx2, Vmaxx2, Vminx3, Vmaxx3, E01all, E02all, E03all, flagdirich)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
type(curvmesh), intent(in) :: x
real(kind=wp), intent(out), dimension(:,:), target :: Vminx1
real(kind=wp), intent(out), dimension(:,:), target :: Vmaxx1
real(kind=wp), intent(out), dimension(:,:) :: Vminx2
real(kind=wp), intent(out), dimension(:,:) :: Vmaxx2
real(kind=wp), intent(out), dimension(:,:) :: Vminx3
real(kind=wp), intent(out), dimension(:,:) :: Vmaxx3
real(kind=wp), intent(out), dimension(:,:,:) :: E01all
real(kind=wp), intent(out), dimension(:,:,:) :: E02all
real(kind=wp), intent(out), dimension(:,:,:) :: E03all
integer, intent(out) :: flagdirich
Called by
Contents
None
Call graph
potential_root_mpi_curv calls potentialbcs2d, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics