potential2D_polarization_periodic – GEMINI3D
potential2D_polarization_periodic Module Procedure
9 statements
Source File
module procedure potential2D_polarization_periodic module function potential2D_polarization_periodic(srcterm, SigP, SigH, Cm, v2, v3, Vminx2, Vmaxx2, Vminx3, Vmaxx3, dt, x, Phi0, perflag, it) Interface →
SOLVE IONOSPHERIC POTENTIAL EQUATION IN 2D USING MUMPS INCLUDES FULL OF POLARIZATION CURRENT, INCLUDING CONVECTIVE TERMS. VELOCITIES SHOULD BE TRIMMED (WITHOUT GHOST CELLS). THIS VERSION OF THE INTEGRATED POTENTIAL SOLVER OBVIATES ALL OTHERS SINCE A PURELY ELECTRSTATIC FORM CAN BE RECOVERED BY ZEROING OUT THE INERTIAL CAPACITANCE.
THIS FORM IS INTENDED TO WORK WITH CARTESIAN MESHES ONLY. NOTE THAT THE FULL GRID VARIABLES (X%DX3ALL, ETC.) MUST BE USED HERE!!!
THIS FUNCTION WORKS ON A PERIODIC MESH BY USING A CIRCULANT MATRIX
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: srcterm
real(kind=wp), intent(in), dimension(:,:) :: SigP
real(kind=wp), intent(in), dimension(:,:) :: SigH
real(kind=wp), intent(in), dimension(:,:) :: Cm
real(kind=wp), intent(in), dimension(:,:) :: v2
real(kind=wp), intent(in), dimension(:,:) :: v3
real(kind=wp), intent(in), dimension(:) :: Vminx2
real(kind=wp), intent(in), dimension(:) :: Vmaxx2
real(kind=wp), intent(in), dimension(:) :: Vminx3
real(kind=wp), intent(in), dimension(:) :: Vmaxx3
real(kind=wp), intent(in) :: dt
type(curvmesh), intent(in) :: x
real(kind=wp), intent(in), dimension(:,:) :: Phi0
logical, intent(in) :: perflag
integer, intent(in) :: it
Return Value real(kind=wp), dimension(size(SigP,1),size(SigP,2))
Calls
Called by
Contents
None
Call graph
potential2d_polarization_periodic calls elliptic2d_polarization_periodic, grad2d1_curv_alt, grad2d3_curv_periodic, potential2d_polarization_periodic
elliptic2d_polarization_periodic calls elliptic2d_polarization_periodic, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
grad2d1_curv_alt calls grad2d1_curv_alt_23
potential_root_mpi_curv calls potential2d_polarization_periodic, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics