potential_root_mpi_curv – GEMINI3D
potential_root_mpi_curv Module Procedure
335 statements
Source File
module procedure potential_root_mpi_curv module subroutine potential_root_mpi_curv(it, t, dt, sig0, sigP, sigH, incap, vs2, vs3, vn2, vn3, sourcemlat, B1, x, potsolve, flagcap, E1, E2, E3, J1, J2, J3, Phiall, flagE0file, dtE0, E0dir, ymd, UTsec) Interface →
ROOT MPI COMM./SOLVE ROUTINE FOR POTENTIAL. THIS VERSION INCLUDES THE POLARIZATION CURRENT TIME DERIVATIVE PART AND CONVECTIVE PARTS IN MATRIX SOLUTION. STATE VARIABLES VS2,3 INCLUDE GHOST CELLS. FOR NOW THE POLARIZATION TERMS ARE PASSED BACK TO MAIN FN, EVEN THOUGH THEY ARE NOT USED (THEY MAY BE IN THE FUTURE)
POPULATE BACKGROUND AND BOUNDARY CONDITION ARRAYS - IDEALLY ROOT ONLY SINCE IT INVOLVES FILE INPUT, ALTHOUGH THE INTERPOLATION MAY BE SLOW... wind x2 current, note that all workers already have a copy of this. wind x3 current wind x2 current wind x3 current !!!!!!
INTEGRATE CONDUCTANCES AND CAPACITANCES FOR SOLVER COEFFICIENTS PRODUCE A FIELD-INTEGRATED SOURCE TERM workers don't have access to boundary conditions, unless root sends
need to pick out the ExB drift here (i.e. the drifts from highest altitudes); but this is only valid for Cartesian, so it's okay for the foreseeable future
note tha this solver is only valid for cartesian meshes, unless the inertial capacitance is set to zero !note that either sigPint2 or 3 will work since this must be cartesian... Dirichlet conditions - since this is field integrated we just copy BCs specified by user to other locations along field line
potential is whatever user specifies, since we assume equipotential field lines, it doesn't really matter whether we use Vmaxx1 or Vminx1. Note however, tha thte boundary conditions subroutines should explicitly set these to be equal with Dirichlet conditions, for consistency. copy the potential across the ix1 direction; past this point there is no real difference with 3D, note that this is still valid in curvilinear form resolved 3D solve ZZZ - conductivities need to be properly scaled here... So does the source term... Maybe leave as broken for now since I don't really plan to use this code in a 2D solve negate this due to it being a cross produce and the fact that we've permuted the 2 and 3 dimensions. ZZZ - NOT JUST THIS WORKS WITH BACKGROUND FIELDS???
EXECUTE THE SOLVE WITH MUMPS AND SCALED TERMS NOTE THE LACK OF A SPECIAL CASE HERE TO CHANGE THE POTENTIAL PROBLEM - ONLY THE HALL TERM CHANGES (SINCE RELATED TO EXB) BUT THAT DOESN'T APPEAR IN THIS EQN! !!!!!!!
STORE PREVIOUS TIME TOTAL FIELDS BEFORE UPDATING THE ELECTRIC FIELDS WITH NEW POTENTIAL (OLD FIELDS USED TO CALCULATE POLARIZATION CURRENT) causes major memory leak. maybe from arithmetic statement argument? Left here as a 'lesson learned' (or is it a gfortran bug...)
ZZZ this is really bad needs to be a global test rather than having each worker test since there is message passing embedded in here and everyone needs to do the same thing!!! !!!!!!
Neumann conditions, this is boundary location-agnostic since both bottom and top FACs are known - they have to be loaded into VVmaxx1 and Vminx1 Dirichlet conditions - we need to integrate from the lowest altitude (where FAC is known to be zero, note this is not necessarilty the logical bottom of the grid), upwards (to where it isn't) !!!!!!!
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: it
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in), dimension(:,:,:) :: sig0
real(kind=wp), intent(in), dimension(:,:,:) :: sigP
real(kind=wp), intent(in), dimension(:,:,:) :: sigH
real(kind=wp), intent(in), dimension(:,:,:) :: incap
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs3
real(kind=wp), intent(in), dimension(:,:,:) :: vn2
real(kind=wp), intent(in), dimension(:,:,:) :: vn3
real(kind=wp), intent(in) :: sourcemlat
real(kind=wp), intent(in), dimension(-1:,-1:,-1:) :: B1
type(curvmesh), intent(in) :: x
integer, intent(in) :: potsolve
integer, intent(in) :: flagcap
real(kind=wp), intent(out), dimension(:,:,:) :: E1
real(kind=wp), intent(out), dimension(:,:,:) :: E2
real(kind=wp), intent(out), dimension(:,:,:) :: E3
real(kind=wp), intent(out), dimension(:,:,:) :: J1
real(kind=wp), intent(out), dimension(:,:,:) :: J2
real(kind=wp), intent(out), dimension(:,:,:) :: J3
real(kind=wp), intent(inout), dimension(:,:,:) :: Phiall
integer, intent(in) :: flagE0file
real(kind=wp), intent(in) :: dtE0
character(len=*), intent(in) :: E0dir
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
Calls
Called by
Contents
None
Call graph
potential_root_mpi_curv calls potential2d_polarization_periodic, gather_recv, halo_pot, bcast_send, potential2d_fieldresolved, potentialbcs2d, mpi_send, potentialbcs2d_fileinput, div3d, integral3d1_curv_alt, integral3d1, grad3d2, grad3d1, potential2d_polarization, potential3d_fieldresolved_decimate, grad3d3, potential_root_mpi_curv
potential2d_polarization_periodic calls potential2d_polarization_periodic, grad2d1_curv_alt, elliptic2d_polarization_periodic, grad2d3_curv_periodic
gather_recv calls gather_recv4d_23, gather_recv3d_23, gather_recv2d_23
halo_pot calls halo
bcast_send calls bcast_send1d_23, bcast_send2d_23, bcast_send4d_23, bcast_send3d_23
potential2d_fieldresolved calls potential2d_fieldresolved, elliptic2d_cart
potentialbcs2d_fileinput calls interp2, interp1, get_grid2, get_simsize2, date_filename, dateinc
div3d calls div3d_curv_23
integral3d1_curv_alt calls integral3d1_curv_alt
integral3d1 calls integral3d1_curv
grad3d2 calls grad3d2_curv_23
grad3d1 calls grad3d1_curv_23
potential2d_polarization calls potential2d_polarization, grad2d1_curv_alt, elliptic2d_polarization, grad2d3
potential3d_fieldresolved_decimate calls grad3d2, grad3d1, grad3d3, interp1, elliptic3d_cart
grad3d3 calls grad3d3_curv_23
interp2 calls interp2
gather_recv4d_23 calls gather_recv4d_23, mpi_recv, slabinds
gather_recv3d_23 calls gather_recv3d_23, mpi_recv, slabinds
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
grad3d3_curv_23 calls grad3d3_curv_23
gather_recv2d_23 calls gather_recv2d_23, mpi_recv, slabinds
get_grid2 calls get_grid2
elliptic3d_cart calls elliptic3d_cart, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
grad3d1_curv_23 calls grad3d1_curv_23
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
integral3d1_curv calls integral3d1_curv
get_simsize2 calls get_simsize2
grad3d2_curv_23 calls grad3d2_curv_23
date_filename calls utsec2filestem
dateinc calls day_wrap
halo calls halo_23
div3d_curv_23 calls div3d_curv_23
elliptic2d_cart calls elliptic2d_cart, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
grad2d1_curv_alt calls grad2d1_curv_alt_23
elliptic2d_polarization calls elliptic2d_polarization, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
grad2d3 calls grad2d3_curv_23
elliptic2d_polarization_periodic calls elliptic2d_polarization_periodic, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
day_wrap calls day_wrap, daysmonth
halo_23 calls halo_23, mpi_irecv, grid2id, mpi_isend, mpi_waitall
utsec2filestem calls day_wrap
slabinds calls id2grid
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics