potentialBCs2D_fileinput – GEMINI3D
potentialBCs2D_fileinput Subroutine
283 statements
Source File
public subroutine potentialBCs2D_fileinput(dt, dtE0, t, ymd, UTsec, E0dir, x, Vminx1, Vmaxx1, Vminx2, Vmaxx2, Vminx3, Vmaxx3, E01all, E02all, E03all, flagdirich)
A FILE INPUT BASED BOUNDARY CONDITIONS FOR ELECTRIC POTENTIAL OR FIELD-ALIGNED CURRENT. NOTE: THIS IS ONLY CALLED BY THE ROOT PROCESS
COMPUTE SOURCE/FORCING TERMS FROM BACKGROUND FIELDS, ETC. do not allow a background parallel field
bit of code duplication with worker code block below...
IF WE HAVE SINGLETON DIMENSION, ALLOCATE SOME SPACE FOR TEMP ARRAY INPUT TO INTERP1 NOW READ THE GRID
SPACE TO STORE INPUT DATA these need to be initialized so that something sensible happens at the beginning by default the code uses 300km altitude as a reference location, using the center x2,x3 point GRID INFORMATION EXISTS AT THIS POINT SO START READING IN PRECIP DATA read in the data from file get the date for "next" params
will work even for 2D grids, just repeats the data in the lon direction both min and max need to be read in from file and interpolated Note: for 2D simulations we don't use Vmaxx2p, etc. data read in from the input file - these BC's will be set later source data is 2D UPDATE OUR CONCEPT OF PREVIOUS AND NEXT TIMES INTERPOLATE IN TIME (LINEAR) make sure to set solve type every time step, as it does not persiste between function calls full 3D grid need to also handle lateral boundaries SOME BASIC DIAGNOSTICS LOAD POTENTIAL SOLVER INPUT ARRAYS, FIRST MAP THE ELECTRIC FIELDS define a reference metric factor for a given field line NOW THE BOUNDARY CONDITIONS full 3D grid
some type of 2D grid, lateral boundary will be overwritten Dirichlet: needs to be the same as the top corner grid points Neumann in x1: sides are grounded...
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in) :: dtE0
real(kind=wp), intent(in) :: t
integer, intent(in), dimension(3) :: ymd
real(kind=wp), intent(in) :: UTsec
character(len=*), intent(in) :: E0dir
type(curvmesh), intent(in) :: x
real(kind=wp), intent(out), dimension(:,:), target :: Vminx1
real(kind=wp), intent(out), dimension(:,:), target :: Vmaxx1
real(kind=wp), intent(out), dimension(:,:) :: Vminx2
real(kind=wp), intent(out), dimension(:,:) :: Vmaxx2
real(kind=wp), intent(out), dimension(:,:) :: Vminx3
real(kind=wp), intent(out), dimension(:,:) :: Vmaxx3
real(kind=wp), intent(out), dimension(:,:,:) :: E01all
real(kind=wp), intent(out), dimension(:,:,:) :: E02all
real(kind=wp), intent(out), dimension(:,:,:) :: E03all
integer, intent(out) :: flagdirich
Calls
Called by
Contents
None
Call graph
potentialbcs2d_fileinput calls interp1, get_grid2, get_simsize2, date_filename, interp2, dateinc
get_grid2 calls get_grid2
get_simsize2 calls get_simsize2
date_filename calls utsec2filestem
interp2 calls interp2
dateinc calls day_wrap
day_wrap calls day_wrap, daysmonth
utsec2filestem calls day_wrap
potential_root_mpi_curv calls potentialbcs2d_fileinput, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics