precipBCs_fileinput – GEMINI3D
precipBCs_fileinput Subroutine
160 statements
Source File
public subroutine precipBCs_fileinput(dt, dtprec, t, ymd, UTsec, precdir, x, W0, PhiWmWm2)
these need to be initialized so that something sensible happens at the beginning
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in) :: dtprec
real(kind=wp), intent(in) :: t
integer, intent(in), dimension(3) :: ymd
date for which we wish to calculate perturbations
real(kind=wp), intent(in) :: UTsec
character(len=*), intent(in) :: precdir
directory where neutral simulation data is kept
type(curvmesh) :: x
real(kind=wp), intent(out), dimension(:,:,:) :: W0
last dimension is the number of particle populations
real(kind=wp), intent(out), dimension(:,:,:) :: PhiWmWm2
last dimension is the number of particle populations
Calls
Called by
Contents
None
Call graph
precipbcs_fileinput calls mpi_recv, interp1, get_grid2, get_simsize2, mpi_send, date_filename, interp2, dateinc
get_grid2 calls get_grid2
get_simsize2 calls get_simsize2
date_filename calls utsec2filestem
interp2 calls interp2
dateinc calls day_wrap
day_wrap calls day_wrap, daysmonth
utsec2filestem calls day_wrap
fluid_adv calls precipbcs_fileinput