read_grid_root – GEMINI3D
read_grid_root Subroutine
216 statements
Source File
subroutine read_grid_root(indatsize, indatgrid, x)
ADJUST THE SIZES OF THE VARIABLES IF LX3ALL==1, SO THAT THE ALLOCATIONS ARE THE CORRECT SIZE use total number of processes since we only divide in one direction here... should divide evenly if generated from mpigrid COMMUNICATE THE GRID SIZE TO THE WORKERS SO THAT THEY CAN ALLOCATE SPACE if this is a root-only simulation we don't want to error out need to also pass the lx2all size to all workers to they know
normal (i.e. full 3D) grid ordering, or a 2D grid with 1 element naturally in the second dimension this is apparently a 2D grid, so the x2 and x3 dimensions have been/need to be swapped MZ - may need to change lx2-->lx2all??? Note there that the fortran arrays are the correct size, but the input data are not!!! This means tmp variable and permutes...
ALLOCATE SPACE FOR ROOTS SUBGRID GRAVITATIONAL FIELD SEND FULL X1 AND X2 GRIDS TO EACH WORKER (ONLY X3-DIM. IS INVOLVED IN THE MPI workers may need a copy of this, e.g. for boudnary conditions
NOW SEND THE INFO THAT DEPENDS ON X3 SLAB SIZE
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: indatsize
character(len=*), intent(in) :: indatgrid
type(curvmesh), intent(inout) :: x
Calls
Called by
Contents
None
Call graph
read_grid_root calls g1, bcast_send3d_x2i, bcast_send, bcast_send3d_x3i, mpi_send, g3, bcast_send1d_3, bcast_send3d_ghost, g2, bcast_send1d_2, get_grid3
bcast_send3d_x2i calls bcast_send3d_x2i_23
bcast_send calls bcast_send3d_23, bcast_send2d_23, bcast_send4d_23, bcast_send1d_23
bcast_send3d_x3i calls bcast_send3d_x3i_23
bcast_send1d_3 calls bcast_send1d_23_3
bcast_send3d_ghost calls bcast_send3d_ghost_23
bcast_send1d_2 calls bcast_send1d_23_2
get_grid3 calls get_grid3, htmp
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
bcast_send1d_23_2 calls bcast_send1d_23_2, id2grid
bcast_send3d_x2i_23 calls bcast_send3d_x2i_23, mpi_send, slabinds
bcast_send3d_ghost_23 calls bcast_send3d_ghost_23, mpi_send, slabinds
bcast_send3d_x3i_23 calls bcast_send3d_x3i_23, mpi_send, slabinds
bcast_send1d_23_3 calls bcast_send1d_23_3, id2grid
slabinds calls id2grid
read_grid calls read_grid_root, read_grid
magcalc calls read_grid
gemini3d calls read_grid