read_dneu3D – GEMINI3D
read_dneu3D Subroutine
76 statements
Source File
private subroutine read_dneu3D(tprev, tnext, t, dtneu, dt, neudir, ymdtmp, UTsectmp)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: tprev
real(kind=wp), intent(in) :: tnext
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in) :: dtneu
real(kind=wp), intent(in) :: dt
character(len=*), intent(in) :: neudir
integer, intent(out), dimension(3) :: ymdtmp
real(kind=wp), intent(out) :: UTsectmp
Calls
Called by
Contents
None
Call graph
read_dneu3d calls date_filename, dateinc, mpi_recv
date_filename calls utsec2filestem
dateinc calls day_wrap
day_wrap calls day_wrap, daysmonth
utsec2filestem calls day_wrap
neutral_perturb_3d calls read_dneu3d
neutral_perturb calls neutral_perturb_3d
gemini3d calls neutral_perturb