read_configfile – GEMINI3D
read_configfile Module Procedure
160 statements
Source File
module procedure read_configfile module subroutine read_configfile(infile, ymd, UTsec0, tdur, dtout, activ, tcfl, Teinf, potsolve, flagperiodic, flagoutput, flagcap, indatsize, indatgrid, flagdneu, interptype, sourcemlat, sourcemlon, dtneu, dxn, drhon, dzn, sourcedir, flagprecfile, dtprec, precdir, flagE0file, dtE0, E0dir, flagglow, dtglow, dtglowout) Interface →
READS THE INPUT CONFIGURAITON FILE, ASSIGNS VARIABLES FOR FILENAMES, SIZES, ETC. READ CONFIG FILE FOR THIS SIMULATION format specifier needed, else it reads just one character PRINT SOME DIAGNOSIC INFO FROM ROOT NEUTRAL PERTURBATION INPUT INFORMATION defaults have to allocate, even when not used, to avoid runtime errors with pickier compilers
PRECIPITATION FILE INPUT INFORMATION defaults get the location of the precipitation input files have to allocate, even when not used, to avoid runtime errors with pickier compilers
ELECTRIC FIELD FILE INPUT INFORMATION defaults get the location of the precipitation input files have to allocate, even when not used, to avoid runtime errors with pickier compilers
GLOW ELECTRON TRANSPORT INFORMATION defaults
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: infile
integer, intent(out), dimension(3) :: ymd
real(kind=wp), intent(out) :: UTsec0
real(kind=wp), intent(out) :: tdur
real(kind=wp), intent(out) :: dtout
real(kind=wp), intent(out), dimension(3) :: activ
real(kind=wp), intent(out) :: tcfl
real(kind=wp), intent(out) :: Teinf
integer, intent(out) :: potsolve
integer, intent(out) :: flagperiodic
integer, intent(out) :: flagoutput
integer, intent(out) :: flagcap
character(len=:), intent(out), allocatable :: indatsize
character(len=:), intent(out), allocatable :: indatgrid
integer, intent(out) :: flagdneu
integer, intent(out) :: interptype
real(kind=wp), intent(out) :: sourcemlat
real(kind=wp), intent(out) :: sourcemlon
real(kind=wp), intent(out) :: dtneu
real(kind=wp), intent(out) :: dxn
real(kind=wp), intent(out) :: drhon
real(kind=wp), intent(out) :: dzn
character(len=:), intent(out), allocatable :: sourcedir
integer, intent(out) :: flagprecfile
real(kind=wp), intent(out) :: dtprec
character(len=:), intent(out), allocatable :: precdir
integer, intent(out) :: flagE0file
real(kind=wp), intent(out) :: dtE0
character(len=:), intent(out), allocatable :: E0dir
integer, intent(out) :: flagglow
real(kind=wp), intent(out) :: dtglow
real(kind=wp), intent(out) :: dtglowout
Calls
Called by
Contents
None
Call graph
read_configfile calls assert_file_exists, check_nml_io, assert_directory_exists, check_ini_io, expanduser, read_configfile
assert_directory_exists calls assert_directory_exists
expanduser calls home
magcalc calls read_configfile
gemini3d calls read_configfile