read_grid_workers – GEMINI3D
read_grid_workers Subroutine
151 statements
Source File
subroutine read_grid_workers(x)
COMPUTE DIFFERENTIAL DISTANCES ALONG EACH DIRECTION
Arguments
Type Intent Optional Attributes Name
type(curvmesh), intent(inout) :: x
Calls
Called by
Contents
None
Call graph
read_grid_workers calls bcast_recv1d_2, bcast_recv, g1, bcast_recv3d_ghost, mpi_recv, bcast_recv3d_x3i, g3, bcast_recv3d_x2i, g2, bcast_recv1d_3
bcast_recv1d_2 calls bcast_recv1d_23_2
bcast_recv calls bcast_recv4d_23, bcast_recv3d_23, bcast_recv2d_23, bcast_recv1d_23
bcast_recv3d_ghost calls bcast_recv3d_ghost_23
bcast_recv3d_x3i calls bcast_recv3d_x3i_23
bcast_recv3d_x2i calls bcast_recv3d_x2i_23
bcast_recv1d_3 calls bcast_recv1d_23_3
bcast_recv1d_23_2 calls bcast_recv1d_23_2, mpi_recv
bcast_recv1d_23_3 calls bcast_recv1d_23_3, mpi_recv
bcast_recv3d_ghost_23 calls bcast_recv3d_ghost_23, mpi_recv
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
bcast_recv3d_x2i_23 calls bcast_recv3d_x2i_23, mpi_recv
bcast_recv3d_x3i_23 calls bcast_recv3d_x3i_23, mpi_recv
read_grid calls read_grid_workers, read_grid
magcalc calls read_grid
gemini3d calls read_grid