read_dneu2D – GEMINI3D
read_dneu2D Subroutine
60 statements
Source File
private subroutine read_dneu2D(tprev, tnext, t, dtneu, dt, neudir, ymdtmp, UTsectmp, flagcart)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: tprev
real(kind=wp), intent(in) :: tnext
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in) :: dtneu
real(kind=wp), intent(in) :: dt
character(len=*), intent(in) :: neudir
integer, intent(out), dimension(3) :: ymdtmp
real(kind=wp), intent(out) :: UTsectmp
logical, intent(in) :: flagcart
Calls
Called by
Contents
None
Call graph
read_dneu2d calls date_filename, mpi_send, dateinc, mpi_recv
date_filename calls utsec2filestem
dateinc calls day_wrap
day_wrap calls day_wrap, daysmonth
utsec2filestem calls day_wrap
neutral_perturb_cart calls read_dneu2d
neutral_perturb_axisymm calls read_dneu2d
neutral_perturb calls neutral_perturb_cart, neutral_perturb_axisymm
gemini3d calls neutral_perturb