read_grid – GEMINI3D
read_grid Module Procedure
19 statements
Source File
module procedure read_grid module subroutine read_grid(indatsize, indatgrid, flagperiodic, x) Interface →
READS GRID INFORMATION FROM A BBINARY FILE AND ALLOCATES GRID STRUCTURE. NOTE THAT THE INPUT FILE DOES NOT, BY DEFAULT INCLUDE THE GHOST CELLS. THIS FUNCTION IS A WRAPPER WHICH PASSES WORK OFF TO APPROPRIATE SUBROUTINE DEPENDING ON WHETHER IT IS CALLED BY ROOT OR NOT. THIS SUBRoutINE ALSO CLASSIFIES THE GRID.
READ IN THE GRID DATA
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: indatsize
character(len=*), intent(in) :: indatgrid
integer, intent(in) :: flagperiodic
type(curvmesh), intent(inout) :: x
Calls
Called by
Contents
None
Call graph
read_grid calls read_grid_root, read_grid_workers, read_grid
read_grid_root calls g1, bcast_send3d_x2i, bcast_send, bcast_send3d_x3i, mpi_send, g3, bcast_send1d_3, bcast_send3d_ghost, g2, bcast_send1d_2, get_grid3
read_grid_workers calls bcast_recv1d_2, bcast_recv, g1, mpi_recv, bcast_recv3d_ghost, bcast_recv3d_x3i, bcast_recv1d_3, g3, bcast_recv3d_x2i, g2
bcast_recv1d_2 calls bcast_recv1d_23_2
bcast_recv calls bcast_recv2d_23, bcast_recv4d_23, bcast_recv3d_23, bcast_recv1d_23
bcast_recv3d_ghost calls bcast_recv3d_ghost_23
bcast_send3d_x2i calls bcast_send3d_x2i_23
bcast_send calls bcast_send1d_23, bcast_send2d_23, bcast_send4d_23, bcast_send3d_23
bcast_recv3d_x3i calls bcast_recv3d_x3i_23
bcast_recv1d_3 calls bcast_recv1d_23_3
bcast_send3d_x3i calls bcast_send3d_x3i_23
bcast_recv3d_x2i calls bcast_recv3d_x2i_23
bcast_send1d_3 calls bcast_send1d_23_3
bcast_send3d_ghost calls bcast_send3d_ghost_23
bcast_send1d_2 calls bcast_send1d_23_2
get_grid3 calls get_grid3, htmp
bcast_recv1d_23_3 calls bcast_recv1d_23_3, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
bcast_recv3d_x2i_23 calls bcast_recv3d_x2i_23, mpi_recv
bcast_send1d_23_3 calls bcast_send1d_23_3, id2grid
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_send1d_23_2 calls bcast_send1d_23_2, id2grid
bcast_send3d_x2i_23 calls bcast_send3d_x2i_23, mpi_send, slabinds
bcast_recv3d_x3i_23 calls bcast_recv3d_x3i_23, mpi_recv
bcast_recv1d_23_2 calls bcast_recv1d_23_2, mpi_recv
bcast_recv3d_ghost_23 calls bcast_recv3d_ghost_23, mpi_recv
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
bcast_send3d_ghost_23 calls bcast_send3d_ghost_23, mpi_send, slabinds
bcast_send3d_x3i_23 calls bcast_send3d_x3i_23, mpi_send, slabinds
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
slabinds calls id2grid
magcalc calls read_grid
gemini3d calls read_grid