RK2_prep_mpi – GEMINI3D
RK2_prep_mpi Module Procedure
45 statements
Source File
module procedure RK2_prep_mpi module subroutine RK2_prep_mpi(isp, isperiodic, vs1, vs2, vs3) Interface →
PASS BOUNDARY CELLS FOR COMPUTING COMPRESSION. DONE ON A PER-SPECIES BASIS. ION PARAMETER ARGUMENTS SHOULD INCLUDE GHOST CELLS. DO WE NEED TO PASS V1,2 VARIABLES FOR DIV?
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: isp
logical, intent(in) :: isperiodic
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:,:) :: vs3
Calls
Called by
Contents
None
Call graph
rk2_prep_mpi calls halo, rk2_prep_mpi
halo calls halo_23
halo_23 calls halo_23, mpi_isend, mpi_irecv, grid2id, mpi_waitall
fluid_adv calls rk2_prep_mpi