spaceinterp_dneu2D – GEMINI3D
spaceinterp_dneu2D Subroutine
93 statements
Source File
private subroutine spaceinterp_dneu2D(flagcart)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: flagcart
Calls
Called by
Contents
None
Call graph
spaceinterp_dneu2d calls interp2
interp2 calls interp2
neutral_perturb_cart calls spaceinterp_dneu2d
neutral_perturb_axisymm calls spaceinterp_dneu2d
neutral_perturb calls neutral_perturb_cart, neutral_perturb_axisymm
gemini3d calls neutral_perturb