SPLINI – GEMINI3D
SPLINI Subroutine
22 statements
Source File
subroutine SPLINI(XA, YA, Y2A, N, X, YI)
Arguments
Type Intent Optional Attributes Name
real :: XA
real :: YA
real :: Y2A
integer :: N
real :: X
real :: YI
Calls
Called by
Contents
None
Call graph
splini calls amin1
densm calls splini
densu calls splini
gtd7 calls densm, gts7
gts7 calls densu
gtd7d calls gtd7
ghp7 calls gtd7
neutral_atmos calls gtd7, neutral_atmos
gemini3d calls neutral_atmos