srcsMomentum_curv – GEMINI3D
srcsMomentum_curv Subroutine
58 statements
Source File
private subroutine srcsMomentum_curv(nn, vn1, Tn, ns, vs1, vs2, vs3, Ts, E1, Q, x, Pr, Lo)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:,:) :: nn
real(kind=wp), intent(in), dimension(:,:,:) :: vn1
real(kind=wp), intent(in), dimension(:,:,:) :: Tn
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: ns
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs1
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs2
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: vs3
real(kind=wp), intent(in), dimension(-1:,-1:,-1:,:) :: Ts
real(kind=wp), intent(in), dimension(:,:,:) :: E1
real(kind=wp), intent(in), dimension(:,:,:,:) :: Q
type(curvmesh), intent(in) :: x
real(kind=wp), intent(out), dimension(size(Ts,1)-4,size(Ts,2)-4,size(Ts,3)-4,lsp) :: Pr
real(kind=wp), intent(out), dimension(size(Ts,1)-4,size(Ts,2)-4,size(Ts,3)-4,lsp) :: Lo
Calls
Called by
Contents
None
Call graph
srcsmomentum_curv calls maxwell_colln, grad3d1, coulomb_colln
grad3d1 calls grad3d1_curv_23
grad3d1_curv_23 calls grad3d1_curv_23
srcsmomentum calls srcsmomentum_curv
fluid_adv calls srcsmomentum