sza – GEMINI3D
sza Function
17 statements
Source File
public elemental function sza(year, month, day, UTsec, glat, glon)
computes sza in radians CALCULATE SOLAR ZENITH ANGLE OVER A GIVEN GET OF LAT/LON
SOLAR DECLINATION ANGLE HOUR ANGLE SOLAR ZENITH ANGLE
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: year
integer, intent(in) :: month
integer, intent(in) :: day
real(kind=wp), intent(in) :: UTsec
real(kind=wp), intent(in) :: glat
real(kind=wp), intent(in) :: glon
Return Value real(kind=wp)
Calls
Called by
Contents
None
Call graph
sza calls doy_calc
doy_calc calls daysmonth
test_sza calls sza
fluid_adv calls sza