timeinterp_dneu – GEMINI3D
timeinterp_dneu Subroutine
36 statements
Source File
private subroutine timeinterp_dneu(t, dt, dNOinow, dnN2inow, dnO2inow, dvn1inow, dvn2inow, dvn3inow, dTninow)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: t
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(out), dimension(:,:,:) :: dNOinow
real(kind=wp), intent(out), dimension(:,:,:) :: dnN2inow
real(kind=wp), intent(out), dimension(:,:,:) :: dnO2inow
real(kind=wp), intent(out), dimension(:,:,:) :: dvn1inow
real(kind=wp), intent(out), dimension(:,:,:) :: dvn2inow
real(kind=wp), intent(out), dimension(:,:,:) :: dvn3inow
real(kind=wp), intent(out), dimension(:,:,:) :: dTninow
Called by
Contents
None
Call graph
neutral_perturb_cart calls timeinterp_dneu
neutral_perturb_axisymm calls timeinterp_dneu
neutral_perturb_3d calls timeinterp_dneu
neutral_perturb calls neutral_perturb_cart, neutral_perturb_axisymm, neutral_perturb_3d
gemini3d calls neutral_perturb