TSELEC – GEMINI3D
TSELEC Subroutine
20 statements
Source File
subroutine TSELEC(SV)
Arguments
Type Intent Optional Attributes Name
real :: SV
Calls
Called by
Contents
Common Blocks
CSW
Common Blocks
common /CSW/
Type Attributes Name Initial
real :: SW(25)
integer :: ISW
real :: SWC(25)
Call graph
tselec calls sw, sav, swc, svv, amod
ionization_fang2010 calls tselec
ionization_fang2008 calls tselec
test_fang calls ionization_fang2010, ionization_fang2008