utsec2filestem – GEMINI3D
utsec2filestem Function
35 statements
Source File
public pure function utsec2filestem(ymd, UTsec) result(fn)
file stem is exactly 21 characters long, per Matt Z's de facto spec. FIXME: until we go to integer UTsec (microsec) we round to nearest microsecond FIXME: This corner case is from not using integers for microseconds
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ymd(3)
class(*), intent(in) :: UTsec
UTC second: real [0.0 .. 86400.0)
Return Value character(len=21)
Calls
Called by
Contents
None
Call graph
utsec2filestem calls day_wrap
day_wrap calls day_wrap, daysmonth
date_filename calls utsec2filestem
test_formats calls utsec2filestem
output_magfields calls date_filename, output_magfields
output_aur_root calls date_filename, output_aur_root
output_root_stream_mpi calls date_filename, output_root_stream_mpi
precipbcs_fileinput calls date_filename
input_root_currents calls date_filename, input_root_currents
potentialbcs2d_fileinput calls date_filename
read_dneu3d calls date_filename
read_dneu2d calls date_filename
fluid_adv calls precipbcs_fileinput
potential_root_mpi_curv calls potentialbcs2d_fileinput, potential_root_mpi_curv
neutral_perturb_axisymm calls read_dneu2d
neutral_perturb_cart calls read_dneu2d
neutral_perturb_3d calls read_dneu3d
magcalc calls output_magfields, input_plasma_currents
neutral_perturb calls neutral_perturb_axisymm, neutral_perturb_cart, neutral_perturb_3d
output_aur calls output_aur_root, output_aur
output_plasma calls output_root_stream_mpi, output_plasma
input_plasma_currents calls input_root_currents, input_plasma_currents
gemini3d calls neutral_perturb, output_plasma, output_aur, electrodynamics
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv