VTST7 – GEMINI3D
VTST7 Function
42 statements
Source File
function VTST7(IYD, SEC, GLAT, GLONG, STL, F107A, F107, AP, IC)
Arguments
Type Intent Optional Attributes Name
integer :: IYD
real :: SEC
real :: GLAT
real :: GLONG
real :: STL
real :: F107A
real :: F107
real :: AP
integer :: IC
Return Value real
Calls
Called by
Contents
Common Blocks
CSW
Common Blocks
common /CSW/
Type Attributes Name Initial
real :: SW(25)
integer :: ISW
real :: SWC(25)
Call graph
vtst7 calls gll, sw, glatl, iydl, stll, swl, fl, fal, swc, secl, swcl, apl
gtd7 calls vtst7, gts7
gts7 calls vtst7
gtd7d calls gtd7
ghp7 calls gtd7
neutral_atmos calls gtd7, neutral_atmos
gemini3d calls neutral_atmos