name: Install CMake
description: Install CMake for Linux

runs:

  using: composite

  steps:
  - name: Install CMake ${{ matrix.cmake_version }}
    shell: bash
    run: cmake -Dversion=${{ matrix.cmake_version }} -P .github/actions/composite-cmake/install_cmake.cmake

  - name: CMake path
    shell: bash
    run: echo "CMAKE=$GITHUB_WORKSPACE/cmake-${{ matrix.cmake_version }}-linux-x86_64/bin/cmake" >> $GITHUB_ENV
