advec3D_MC_mpi – GEMINI3D
advec3D_MC_mpi Interface
3 statements
Source File
public interface advec3D_MC_mpi
OVERLOAD ADVECTION TO DEAL WITH THE CURVILINEAR GRID/MESH STRUCTURE. NOTE THAT THE LOWER-LEVEL CALLS ARE DISTINCT, NOT-OVERLOADED PROCEDURES.
Calls
Called by
Contents
Module Procedures
advec3D_MC_mpi_curv_23
Module Procedures
private function advec3D_MC_mpi_curv_23(f, v1i, v2i, v3i, dt, x, frank, tagf)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-1:,-1:,-1:) :: f
real(kind=wp), intent(in), dimension(:,:,:) :: v1i
real(kind=wp), intent(in), dimension(:,:,:) :: v2i
real(kind=wp), intent(in), dimension(:,:,:) :: v3i
real(kind=wp), intent(in) :: dt
type(curvmesh), intent(in) :: x
integer, intent(in) :: frank
integer, intent(in) :: tagf
Return Value real(kind=wp), dimension(-1:size(f,1)-2,-1:size(f,2)-2,-1:size(f,3)-2)
Call graph
advec3d_mc_mpi calls advec3d_mc_mpi_curv_23
advec3d_mc_mpi_curv_23 calls advec1d_mc_curv, halo
advec1d_mc_curv calls minmod
halo calls halo_23
halo_23 calls halo_23, mpi_isend, mpi_irecv, grid2id, mpi_waitall
fluid_adv calls advec3d_mc_mpi