bcast_send – GEMINI3D
bcast_send Interface
3 statements
Source File
public interface bcast_send
Calls
Called by
Contents
Module Procedures
bcast_send1D_23 bcast_send2D_23 bcast_send3D_23 bcast_send4D_23
Module Procedures
public interface bcast_send1D_23()
Arguments
None
public interface bcast_send2D_23()
Arguments
None
public interface bcast_send3D_23()
Arguments
None
public interface bcast_send4D_23()
Arguments
None
Call graph
bcast_send calls bcast_send3d_23, bcast_send2d_23, bcast_send4d_23, bcast_send1d_23
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
slabinds calls id2grid
input_root_mpi calls bcast_send, input_root_mpi
read_grid_root calls bcast_send
potential_root_mpi_curv calls bcast_send, potential_root_mpi_curv
input_root_currents calls bcast_send, input_root_currents
read_grid calls read_grid_root, read_grid
input_plasma calls input_root_mpi, input_plasma
potential_root_mpi calls potential_root_mpi_curv
input_plasma_currents calls input_root_currents, input_plasma_currents
gemini3d calls read_grid, input_plasma, electrodynamics
electrodynamics_curv calls potential_root_mpi
magcalc calls read_grid, input_plasma_currents
electrodynamics calls electrodynamics_curv