bcast_send3D_x3i_23 – GEMINI3D
bcast_send3D_x3i_23 Interface
59 statements
Source File
interface
Calls
Called by
public module subroutine bcast_send3D_x3i_23(paramtrimall, tag, paramtrim) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: paramtrimall
integer, intent(in) :: tag
real(kind=wp), intent(out), dimension(:,:,:) :: paramtrim
Call graph
bcast_send3d_x3i_23 calls bcast_send3d_x3i_23, mpi_send, slabinds
slabinds calls id2grid
bcast_send3d_x3i calls bcast_send3d_x3i_23
read_grid_root calls bcast_send3d_x3i
read_grid calls read_grid_root, read_grid
magcalc calls read_grid
gemini3d calls read_grid