bcast_recv – GEMINI3D
bcast_recv Interface
3 statements
Source File
public interface bcast_recv
Calls
Called by
Contents
Module Procedures
bcast_recv1D_23 bcast_recv2D_23 bcast_recv3D_23 bcast_recv4D_23
Module Procedures
public interface bcast_recv1D_23()
Arguments
None
public interface bcast_recv2D_23()
Arguments
None
public interface bcast_recv3D_23()
Arguments
None
public interface bcast_recv4D_23()
Arguments
None
Call graph
bcast_recv calls bcast_recv1d_23, bcast_recv4d_23, bcast_recv3d_23, bcast_recv2d_23
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
input_workers_mpi calls bcast_recv
input_workers_currents calls bcast_recv
potential_workers_mpi calls bcast_recv, potential_workers_mpi
read_grid_workers calls bcast_recv
input_plasma calls input_workers_mpi, input_plasma
input_plasma_currents calls input_workers_currents, input_plasma_currents
read_grid calls read_grid_workers, read_grid
electrodynamics_curv calls potential_workers_mpi
magcalc calls read_grid, input_plasma_currents
gemini3d calls read_grid, input_plasma, electrodynamics
electrodynamics calls electrodynamics_curv