bcast_send3D_ghost – GEMINI3D
bcast_send3D_ghost Interface
3 statements
Source File
public interface bcast_send3D_ghost
Calls
Called by
Contents
Module Procedures
bcast_send3D_ghost_23
Module Procedures
public interface bcast_send3D_ghost_23()
Arguments
None
Call graph
bcast_send3d_ghost calls bcast_send3d_ghost_23
bcast_send3d_ghost_23 calls bcast_send3d_ghost_23, mpi_send, slabinds
slabinds calls id2grid
read_grid_root calls bcast_send3d_ghost
read_grid calls read_grid_root, read_grid
magcalc calls read_grid
gemini3d calls read_grid