bcast_send3D_x3i – GEMINI3D
bcast_send3D_x3i Interface
3 statements
Source File
public interface bcast_send3D_x3i
Calls
Called by
Contents
Module Procedures
bcast_send3D_x3i_23
Module Procedures
public interface bcast_send3D_x3i_23()
Arguments
None
Call graph
bcast_send3d_x3i calls bcast_send3d_x3i_23
bcast_send3d_x3i_23 calls bcast_send3d_x3i_23, mpi_send, slabinds
slabinds calls id2grid
read_grid_root calls bcast_send3d_x3i
read_grid calls read_grid_root, read_grid
magcalc calls read_grid
gemini3d calls read_grid