copyfile – GEMINI3D
copyfile Interface
8 statements
Source File
interface
Calls
Called by
public module function copyfile(source, dest) result(istat) Implementation →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: source
character(len=*), intent(in) :: dest
Return Value integer
Call graph
copyfile calls copyfile
create_outdir_mag calls copyfile, create_outdir_mag
create_outdir calls copyfile, create_outdir
magcalc calls create_outdir_mag
gemini3d calls create_outdir