div3D – GEMINI3D
div3D Interface
3 statements
Source File
public interface div3D
Calls
Called by
Contents
Module Procedures
div3D_curv_23
Module Procedures
private interface div3D_curv_23()
Arguments
None
Call graph
div3d calls div3d_curv_23
div3d_curv_23 calls div3d_curv_23
potential_root_mpi_curv calls div3d, potential_root_mpi_curv
potential_workers_mpi calls div3d, potential_workers_mpi
fluid_adv calls div3d
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics