div3D_curv_23 – GEMINI3D
div3D_curv_23 Interface
14 statements
Source File
interface
Calls
Called by
private module function div3D_curv_23(f1, f2, f3, x, lbnd1, ubnd1, lbnd2, ubnd2, lbnd3, ubnd3) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: f1
regardless of what has been passed into the function here, we assume these start at 1
real(kind=wp), intent(in), dimension(:,:,:) :: f2
regardless of what has been passed into the function here, we assume these start at 1
real(kind=wp), intent(in), dimension(:,:,:) :: f3
regardless of what has been passed into the function here, we assume these start at 1
type(curvmesh), intent(in) :: x
integer, intent(in) :: lbnd1
integer, intent(in) :: ubnd1
integer, intent(in) :: lbnd2
integer, intent(in) :: ubnd2
integer, intent(in) :: lbnd3
integer, intent(in) :: ubnd3
Return Value real(kind=wp), dimension(1:size(f1,1),1:size(f1,2),1:size(f1,3))
Call graph
div3d_curv_23 calls div3d_curv_23
div3d calls div3d_curv_23
potential_root_mpi_curv calls div3d, potential_root_mpi_curv
potential_workers_mpi calls div3d, potential_workers_mpi
fluid_adv calls div3d
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics