elliptic3D_cart – GEMINI3D
elliptic3D_cart Interface
18 statements
Source File
interface
Calls
Called by
public module function elliptic3D_cart(srcterm, Ac, Bc, Cc, Dc, Ec, Fc, Vminx1, Vmaxx1, Vminx2, Vmaxx2, Vminx3, Vmaxx3, dx1, dx1i, dx2all, dx2iall, dx3all, dx3iall, flagdirich, perflag, it) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: srcterm
real(kind=wp), intent(in), dimension(:,:,:) :: Ac
real(kind=wp), intent(in), dimension(:,:,:) :: Bc
real(kind=wp), intent(in), dimension(:,:,:) :: Cc
real(kind=wp), intent(in), dimension(:,:,:) :: Dc
real(kind=wp), intent(in), dimension(:,:,:) :: Ec
real(kind=wp), intent(in), dimension(:,:,:) :: Fc
real(kind=wp), intent(in), dimension(:,:) :: Vminx1
real(kind=wp), intent(in), dimension(:,:) :: Vmaxx1
real(kind=wp), intent(in), dimension(:,:) :: Vminx2
real(kind=wp), intent(in), dimension(:,:) :: Vmaxx2
real(kind=wp), intent(in), dimension(:,:) :: Vminx3
real(kind=wp), intent(in), dimension(:,:) :: Vmaxx3
real(kind=wp), intent(in), dimension(0:) :: dx1
real(kind=wp), intent(in), dimension(:) :: dx1i
real(kind=wp), intent(in), dimension(0:) :: dx2all
real(kind=wp), intent(in), dimension(:) :: dx2iall
real(kind=wp), intent(in), dimension(0:) :: dx3all
real(kind=wp), intent(in), dimension(:) :: dx3iall
integer, intent(in) :: flagdirich
logical, intent(in) :: perflag
integer, intent(in) :: it
Return Value real(kind=wp), dimension(size(srcterm,1),size(srcterm,2),size(srcterm,3))
Call graph
elliptic3d_cart calls elliptic3d_cart, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
potential3d_fieldresolved_decimate calls elliptic3d_cart
potential_root_mpi_curv calls potential3d_fieldresolved_decimate, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics