elliptic2D_polarization_periodic – GEMINI3D
elliptic2D_polarization_periodic Interface
48 statements
Source File
interface
Calls
Called by
public module function elliptic2D_polarization_periodic(srcterm, SigP, SigH, gradSigH2, gradSigH3, Cm, v2, v3, Vminx2, Vmaxx2, Vminx3, Vmaxx3, dt, dx1, dx1i, dx2all, dx2iall, dx3all, dx3iall, Phi0, perflag, it) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: srcterm
real(kind=wp), intent(in), dimension(:,:) :: SigP
real(kind=wp), intent(in), dimension(:,:) :: SigH
real(kind=wp), intent(in), dimension(:,:) :: gradSigH2
real(kind=wp), intent(in), dimension(:,:) :: gradSigH3
real(kind=wp), intent(in), dimension(:,:) :: Cm
real(kind=wp), intent(in), dimension(:,:) :: v2
real(kind=wp), intent(in), dimension(:,:) :: v3
real(kind=wp), intent(in), dimension(:) :: Vminx2
real(kind=wp), intent(in), dimension(:) :: Vmaxx2
real(kind=wp), intent(in), dimension(:) :: Vminx3
real(kind=wp), intent(in), dimension(:) :: Vmaxx3
real(kind=wp), intent(in) :: dt
real(kind=wp), intent(in), dimension(0:) :: dx1
real(kind=wp), intent(in), dimension(:) :: dx1i
real(kind=wp), intent(in), dimension(0:) :: dx2all
real(kind=wp), intent(in), dimension(:) :: dx2iall
real(kind=wp), intent(in), dimension(0:) :: dx3all
real(kind=wp), intent(in), dimension(:) :: dx3iall
real(kind=wp), intent(in), dimension(:,:) :: Phi0
logical, intent(in) :: perflag
integer, intent(in) :: it
Return Value real(kind=wp), dimension(size(SigP,1),size(SigP,2))
Call graph
elliptic2d_polarization_periodic calls elliptic2d_polarization_periodic, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
potential2d_polarization_periodic calls elliptic2d_polarization_periodic, potential2d_polarization_periodic
potential_root_mpi_curv calls potential2d_polarization_periodic, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics