gather_send3D_23 – GEMINI3D
gather_send3D_23 Interface
59 statements
Source File
interface
Calls
Called by
public module subroutine gather_send3D_23(paramtrim, tag) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: paramtrim
integer, intent(in) :: tag
Call graph
gather_send3d_23 calls gather_send3d_23, mpi_send
gather_send calls gather_send3d_23
output_aur_workers calls gather_send, output_aur_workers
potential_workers_mpi calls gather_send, potential_workers_mpi
output_workers_mpi calls gather_send
output_plasma calls output_workers_mpi, output_plasma
output_aur calls output_aur_workers, output_aur
electrodynamics_curv calls potential_workers_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls output_plasma, electrodynamics, output_aur