get_simsize3 – GEMINI3D
get_simsize3 Interface
33 statements
Source File
interface
Calls
Called by
public module subroutine get_simsize3(path, lx1, lx2all, lx3all) Implementation →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
integer, intent(out) :: lx1
integer, intent(out) :: lx2all
integer, intent(out), optional :: lx3all
Call graph
get_simsize3 calls get_simsize3, lx
input_root_mpi calls get_simsize3, input_root_mpi
gridproj_dneu3d calls get_simsize3
gridproj_dneu2d calls get_simsize3
grid_size calls get_simsize3
neutral_perturb_cart calls gridproj_dneu2d
neutral_perturb_axisymm calls gridproj_dneu2d
magcalc calls grid_size
gemini3d calls grid_size, neutral_perturb, input_plasma
neutral_perturb_3d calls gridproj_dneu3d
input_plasma calls input_root_mpi, input_plasma
neutral_perturb calls neutral_perturb_cart, neutral_perturb_axisymm, neutral_perturb_3d