get_grid2 – GEMINI3D
get_grid2 Interface
33 statements
Source File
interface
Calls
Called by
public module subroutine get_grid2(path, mlonp, mlatp) Implementation →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
real(kind=wp), intent(out), dimension(:) :: mlonp
real(kind=wp), intent(out), dimension(:) :: mlatp
Call graph
get_grid2 calls get_grid2
potentialbcs2d_fileinput calls get_grid2
precipbcs_fileinput calls get_grid2
potential_root_mpi_curv calls potentialbcs2d_fileinput, potential_root_mpi_curv
fluid_adv calls precipbcs_fileinput
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics