get_grid3 – GEMINI3D
get_grid3 Interface
10 statements
Source File
interface
Calls
Called by
module subroutine get_grid3(path, flagswap, x, g1all, g2all, g3all, altall, glatall, glonall, Bmagall, Incall, nullptsall, e1all, e2all, e3all, erall, ethetaall, ephiall, rall, thetaall, phiall) Implementation →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
integer, intent(in) :: flagswap
type(curvmesh), intent(inout) :: x
real(kind=wp), intent(out), dimension(:,:,:) :: g1all
real(kind=wp), intent(out), dimension(:,:,:) :: g2all
real(kind=wp), intent(out), dimension(:,:,:) :: g3all
real(kind=wp), intent(out), dimension(:,:,:) :: altall
real(kind=wp), intent(out), dimension(:,:,:) :: glatall
real(kind=wp), intent(out), dimension(:,:,:) :: glonall
real(kind=wp), intent(out), dimension(:,:,:) :: Bmagall
real(kind=wp), intent(out), dimension(:,:) :: Incall
real(kind=wp), intent(out), dimension(:,:,:) :: nullptsall
real(kind=wp), intent(out), dimension(:,:,:,:) :: e1all
real(kind=wp), intent(out), dimension(:,:,:,:) :: e2all
real(kind=wp), intent(out), dimension(:,:,:,:) :: e3all
real(kind=wp), intent(out), dimension(:,:,:,:) :: erall
real(kind=wp), intent(out), dimension(:,:,:,:) :: ethetaall
real(kind=wp), intent(out), dimension(:,:,:,:) :: ephiall
real(kind=wp), intent(out), dimension(:,:,:) :: rall
real(kind=wp), intent(out), dimension(:,:,:) :: thetaall
real(kind=wp), intent(out), dimension(:,:,:) :: phiall
Call graph
get_grid3 calls get_grid3, htmp
read_grid_root calls get_grid3
read_grid calls read_grid_root, read_grid
magcalc calls read_grid
gemini3d calls read_grid