grad3D1_curv_23 – GEMINI3D
grad3D1_curv_23 Interface
38 statements
Source File
interface
Calls
Called by
private module function grad3D1_curv_23(f, x, lbnd1, ubnd1, lbnd2, ubnd2, lbnd3, ubnd3) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: f
type(curvmesh), intent(in) :: x
integer, intent(in) :: lbnd1
integer, intent(in) :: ubnd1
integer, intent(in) :: lbnd2
integer, intent(in) :: ubnd2
integer, intent(in) :: lbnd3
integer, intent(in) :: ubnd3
Return Value real(kind=wp), dimension(1:size(f,1),1:size(f,2),1:size(f,3))
Call graph
grad3d1_curv_23 calls grad3d1_curv_23
grad3d1 calls grad3d1_curv_23
srcsmomentum_curv calls grad3d1
potential_root_mpi_curv calls grad3d1, potential3d_fieldresolved_decimate, potential_root_mpi_curv
potential_workers_mpi calls grad3d1, potential_workers_mpi
potential3d_fieldresolved_decimate calls grad3d1
srcsmomentum calls srcsmomentum_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi
fluid_adv calls srcsmomentum
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics