grad3D2 – GEMINI3D
grad3D2 Interface
3 statements
Source File
public interface grad3D2
Calls
Called by
Contents
Module Procedures
grad3D2_curv_23
Module Procedures
private interface grad3D2_curv_23()
Arguments
None
Call graph
grad3d2 calls grad3d2_curv_23
grad3d2_curv_23 calls grad3d2_curv_23
potential_root_mpi_curv calls grad3d2, potential3d_fieldresolved_decimate, potential_root_mpi_curv
potential_workers_mpi calls grad3d2, potential_workers_mpi
potential3d_fieldresolved_decimate calls grad3d2
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics