grad2D1_curv_alt – GEMINI3D
grad2D1_curv_alt Interface
3 statements
Source File
public interface grad2D1_curv_alt
Calls
Called by
Contents
Module Procedures
grad2D1_curv_alt_23
Module Procedures
private function grad2D1_curv_alt_23(f, x, lbnd, ubnd)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: f
type(curvmesh), intent(in) :: x
integer, intent(in) :: lbnd
integer, intent(in) :: ubnd
Return Value real(kind=wp), dimension(1:size(f,1),1:size(f,2))
Call graph
grad2d1_curv_alt calls grad2d1_curv_alt_23
potential2d_polarization_periodic calls grad2d1_curv_alt, potential2d_polarization_periodic
potential2d_polarization calls grad2d1_curv_alt, potential2d_polarization
potential_root_mpi_curv calls potential2d_polarization_periodic, potential2d_polarization, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics