halo_23 – GEMINI3D
halo_23 Interface
14 statements
Source File
interface
Calls
Called by
public module subroutine halo_23(param, lhalo, tag, isperiodic) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(-1:,-1:,-1:) :: param
integer, intent(in) :: lhalo
integer, intent(in) :: tag
logical, intent(in) :: isperiodic
Call graph
halo_23 calls halo_23, mpi_isend, mpi_irecv, grid2id, mpi_waitall
halo calls halo_23
halo_pot calls halo
advec_prep_mpi_3 calls halo
advec_prep_mpi_23 calls halo
rk2_prep_mpi calls halo, rk2_prep_mpi
advec3d_mc_mpi_curv_23 calls halo
advec_prep_mpi calls advec_prep_mpi_23
potential_root_mpi_curv calls halo_pot, potential_root_mpi_curv
potential_workers_mpi calls halo_pot, potential_workers_mpi
advec3d_mc_mpi calls advec3d_mc_mpi_curv_23
fluid_adv calls rk2_prep_mpi, advec_prep_mpi, advec3d_mc_mpi
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics