halo_end – GEMINI3D
halo_end Interface
3 statements
Source File
public interface halo_end
Calls
Called by
Contents
Module Procedures
halo_end_23
Module Procedures
public interface halo_end_23()
Arguments
None
Call graph
halo_end calls halo_end_23
halo_end_23 calls halo_end_23, mpi_irecv, grid2id, mpi_waitall, mpi_isend
magcalc calls halo_end