mkdir – GEMINI3D
mkdir Interface
8 statements
Source File
interface
Calls
Called by
public module function mkdir(path) result(istat) Implementation →
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: path
Return Value integer
Call graph
mkdir calls mkdir
create_outdir_mag calls mkdir, create_outdir_mag
create_outdir_aur calls mkdir, create_outdir_aur
create_outdir calls mkdir, create_outdir
magcalc calls create_outdir_mag
gemini3d calls create_outdir