potential2D_fieldresolved – GEMINI3D
potential2D_fieldresolved Interface
34 statements
Source File
interface
Calls
Called by
public module function potential2D_fieldresolved(srcterm, sig0, sigP, Vminx1, Vmaxx1, Vminx3, Vmaxx3, x, flagdirich, perflag, it) Implementation →
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: srcterm
real(kind=wp), intent(in), dimension(:,:,:) :: sig0
real(kind=wp), intent(in), dimension(:,:,:) :: sigP
real(kind=wp), intent(in), dimension(:,:) :: Vminx1
real(kind=wp), intent(in), dimension(:,:) :: Vmaxx1
real(kind=wp), intent(in), dimension(:,:) :: Vminx3
real(kind=wp), intent(in), dimension(:,:) :: Vmaxx3
type(curvmesh), intent(in) :: x
integer, intent(in) :: flagdirich
logical, intent(in) :: perflag
integer, intent(in) :: it
Return Value real(kind=wp), dimension(size(sig0,1),1,size(sig0,3))
Call graph
potential2d_fieldresolved calls potential2d_fieldresolved, elliptic2d_cart
elliptic2d_cart calls elliptic2d_cart, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
potential_root_mpi_curv calls potential2d_fieldresolved, potential_root_mpi_curv
potential_root_mpi calls potential_root_mpi_curv
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics