potential_root_mpi – GEMINI3D
potential_root_mpi Interface
3 statements
Source File
private interface potential_root_mpi
Calls
Called by
Contents
Module Procedures
potential_root_mpi_curv
Module Procedures
private interface potential_root_mpi_curv()
Arguments
None
Call graph
potential_root_mpi calls potential_root_mpi_curv
potential_root_mpi_curv calls potential_root_mpi_curv, potential2d_polarization_periodic, gather_recv, halo_pot, bcast_send, potential2d_fieldresolved, potentialbcs2d, mpi_send, potentialbcs2d_fileinput, div3d, integral3d1_curv_alt, integral3d1, grad3d2, grad3d1, potential2d_polarization, potential3d_fieldresolved_decimate, grad3d3
potential2d_polarization_periodic calls potential2d_polarization_periodic, grad2d1_curv_alt, elliptic2d_polarization_periodic, grad2d3_curv_periodic
gather_recv calls gather_recv4d_23, gather_recv3d_23, gather_recv2d_23
halo_pot calls halo
bcast_send calls bcast_send1d_23, bcast_send2d_23, bcast_send4d_23, bcast_send3d_23
potential2d_fieldresolved calls potential2d_fieldresolved, elliptic2d_cart
potentialbcs2d_fileinput calls interp2, interp1, get_grid2, get_simsize2, date_filename, dateinc
div3d calls div3d_curv_23
integral3d1_curv_alt calls integral3d1_curv_alt
integral3d1 calls integral3d1_curv
grad3d2 calls grad3d2_curv_23
grad3d1 calls grad3d1_curv_23
potential2d_polarization calls potential2d_polarization, grad2d1_curv_alt, elliptic2d_polarization, grad2d3
potential3d_fieldresolved_decimate calls grad3d2, grad3d1, grad3d3, interp1, elliptic3d_cart
grad3d3 calls grad3d3_curv_23
interp2 calls interp2
gather_recv4d_23 calls gather_recv4d_23, mpi_recv, slabinds
gather_recv3d_23 calls gather_recv3d_23, mpi_recv, slabinds
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
grad3d3_curv_23 calls grad3d3_curv_23
gather_recv2d_23 calls gather_recv2d_23, mpi_recv, slabinds
get_grid2 calls get_grid2
elliptic3d_cart calls elliptic3d_cart, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
grad3d1_curv_23 calls grad3d1_curv_23
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
integral3d1_curv calls integral3d1_curv
get_simsize2 calls get_simsize2
grad3d2_curv_23 calls grad3d2_curv_23
date_filename calls utsec2filestem
dateinc calls day_wrap
halo calls halo_23
div3d_curv_23 calls div3d_curv_23
elliptic2d_cart calls elliptic2d_cart, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
grad2d1_curv_alt calls grad2d1_curv_alt_23
elliptic2d_polarization calls elliptic2d_polarization, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
grad2d3 calls grad2d3_curv_23
elliptic2d_polarization_periodic calls elliptic2d_polarization_periodic, mumps_exec, check_mumps_status, mumps_perm, quiet_mumps
day_wrap calls day_wrap, daysmonth
halo_23 calls halo_23, mpi_irecv, grid2id, mpi_isend, mpi_waitall
utsec2filestem calls day_wrap
slabinds calls id2grid
electrodynamics_curv calls potential_root_mpi
electrodynamics calls electrodynamics_curv
gemini3d calls electrodynamics