TRBDF23D – GEMINI3D
TRBDF23D Interface
3 statements
Source File
public interface TRBDF23D
Calls
Called by
Contents
Module Procedures
TRBDF23D_curv
Module Procedures
private function TRBDF23D_curv(f, A, B, C, D, E, dt, x)
SOLVE A 3D SEQUENCE OF 1D DIFFUSION PROBLEMS. GHOST CELLS ARE ACCOMODATED AS THEY PROVIDE A CONVENIENT MEMORY SPACE FOR BOUNDARY CONDITIONS.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(-1:,-1:,-1:) :: f
expected to include ghosts
real(kind=wp), intent(in), dimension(:,:,:) :: A
trimmed to grid size
real(kind=wp), intent(in), dimension(:,:,:) :: B
trimmed to grid size
real(kind=wp), intent(in), dimension(:,:,:) :: C
trimmed to grid size
real(kind=wp), intent(in), dimension(:,:,:) :: D
trimmed to grid size
real(kind=wp), intent(in), dimension(:,:,:) :: E
trimmed to grid size
real(kind=wp), intent(in) :: dt
type(curvmesh), intent(in) :: x
Return Value real(kind=wp), dimension(-1:size(f,1)-2,-1:size(f,2)-2,-1:size(f,3)-2)
Call graph
trbdf23d calls trbdf23d_curv
trbdf23d_curv calls trbdf21d
trbdf21d calls gbsv
gbsv calls dgbsv, sgbsv
fluid_adv calls trbdf23d