Gemini3D – GEMINI3D
Gemini3D Program
244 statements
Source File
Uses
iso_fortran_env
phys_consts
grid
mesh
io
mpimod
multifluid
neutral
potentialBCs_mumps
potential_comm
precipBCs_mod
temporal
timeutils
MAIN PROGRAM FOR GEMINI3D Need program statement for FORD stops with de facto "skip test" return code INITIALIZE MESSING PASSING VARIABLES, IDS ETC. READ FILE INPUT CHECK THE GRID SIZE AND ESTABLISH A PROCESS GRID
following grid_size these are in scope LOAD UP THE GRID STRUCTURE/MODULE VARS. FOR THIS SIMULATION read in a previously generated grid from filenames listed in input file
CREATE/PREP OUTPUT DIRECTORY AND OUTPUT SIMULATION SIZE AND GRID DATA ONLY THE ROOT PROCESS WRITES OUTPUT DATA ALLOCATE ARRAYS (AT THIS POINT ALL SIZES ARE SET FOR EACH PROCESS SUBGRID) allocate space for neutral perturbations in case they are used with this run ALLOCATE MEMORY FOR ROOT TO STORE CERTAIN VARS. OVER ENTIRE GRID ALLOCATE MEMORY FOR AURORAL EMISSIONS, IF CALCULATED LOAD ICS AND DISTRIBUTE TO WORKERS (REQUIRES GRAVITY FOR INITIAL GUESSING)
this assumes that the grid is defined s.t. the x1 direction corresponds to the magnetic field direction (hence zero B2 and B3).
INITIALIZE ELECTRODYNAMIC QUANTITIES FOR POLARIZATION CURRENT only root stores entire potential array INITIALIZE AURORAL EMISSION MAP
MAIN LOOP TIME STEP CALCULATION throttle how quickly we allow dt to increase hard-code these to zero for the first time step GET NEUTRAL PERTURBATIONS FROM ANOTHER MODEL this triggers the code to load the neutral frame correspdonding ot the beginning time of the simulation POTENTIAL SOLUTION UPDATE THE FLUID VARIABLES NOW OUR SOLUTION IS FULLY UPDATED SO UPDATE TIME VARIABLES TO MATCH... print every 10th time step to avoid extreme amounts of console printing OUTPUT close enough to warrant an output now... GLOW OUTPUT DEALLOCATE MAIN PROGRAM DATA DEALLOCATE MODULE VARIABLES (MAY HAPPEN AUTOMATICALLY IN F2003???) SHUT DOWN MPI
Calls
Contents
Variables
ierr ymd UTsec UTsec0 tdur activ tcfl Teinf potsolve flagperiodic flagoutput flagcap infile outdir indatsize indatgrid x ns vs1 vs2 vs3 Ts E1 E2 E3 J1 J2 J3 rhov2 rhov3 B1 B2 B3 rhom v1 v2 v3 nn Tn vn1 vn2 vn3 Phiall iver t dt dtprev tout dtout tstart tfin it isp dl1 dl2 dl3 flagdneu interptype dxn drhon dzn sourcemlat sourcemlon sourcedir dtneu flagprecfile dtprec precdir flagE0file dtE0 E0dir flagglow dtglow dtglowout tglowout nooutput argc argv lid2in lid3in date time dtscale
Variables
Type Attributes Name Initial
integer :: ierr
integer, dimension(3) :: ymd
VARIABLES READ IN FROM CONFIG.INI FILE year,month,day of simulation
real(kind=wp) :: UTsec
UT (s)
real(kind=wp) :: UTsec0
UT start time of simulation (s)
real(kind=wp) :: tdur
duration of simulation
real(kind=wp), dimension(3) :: activ
f10.7a,f10.7,ap
real(kind=wp) :: tcfl
target CFL number
real(kind=wp) :: Teinf
exospheric temperature
integer :: potsolve
what type of potential solve
integer :: flagperiodic
toggles whether or not the grid is treated as periodic in the x3 dimension (affects some of the message passing)
integer :: flagoutput
what type of output to do (1 - everything; 2 - avg'd parms.; 3 - ne only)
integer :: flagcap
internal capacitance?
character(len=:), allocatable :: infile
INPUT AND OUTPUT FILES command line argument input file
character(len=:), allocatable :: outdir
" " output directory
character(len=:), allocatable :: indatsize
grid size and data filenames
character(len=:), allocatable :: indatgrid
grid size and data filenames
type(curvmesh) :: x
GRID STRUCTURE structure containg grid locations, finite differences, etc.: see grid module for details
real(kind=wp), dimension(:,:,:,:), allocatable :: ns
STATE VARIABLES fluid state variables
real(kind=wp), dimension(:,:,:,:), allocatable :: vs1
STATE VARIABLES fluid state variables
real(kind=wp), dimension(:,:,:,:), allocatable :: vs2
STATE VARIABLES fluid state variables
real(kind=wp), dimension(:,:,:,:), allocatable :: vs3
STATE VARIABLES fluid state variables
real(kind=wp), dimension(:,:,:,:), allocatable :: Ts
STATE VARIABLES fluid state variables
real(kind=wp), dimension(:,:,:), allocatable :: E1
electrodynamic state variables
real(kind=wp), dimension(:,:,:), allocatable :: E2
electrodynamic state variables
real(kind=wp), dimension(:,:,:), allocatable :: E3
electrodynamic state variables
real(kind=wp), dimension(:,:,:), allocatable :: J1
electrodynamic state variables
real(kind=wp), dimension(:,:,:), allocatable :: J2
electrodynamic state variables
real(kind=wp), dimension(:,:,:), allocatable :: J3
electrodynamic state variables
real(kind=wp), dimension(:,:,:), allocatable :: rhov2
inductive state vars. (for future use - except for B1 which is used for the background field)
real(kind=wp), dimension(:,:,:), allocatable :: rhov3
inductive state vars. (for future use - except for B1 which is used for the background field)
real(kind=wp), dimension(:,:,:), allocatable :: B1
inductive state vars. (for future use - except for B1 which is used for the background field)
real(kind=wp), dimension(:,:,:), allocatable :: B2
inductive state vars. (for future use - except for B1 which is used for the background field)
real(kind=wp), dimension(:,:,:), allocatable :: B3
inductive state vars. (for future use - except for B1 which is used for the background field)
real(kind=wp), dimension(:,:,:), allocatable :: rhom
inductive auxiliary
real(kind=wp), dimension(:,:,:), allocatable :: v1
inductive auxiliary
real(kind=wp), dimension(:,:,:), allocatable :: v2
inductive auxiliary
real(kind=wp), dimension(:,:,:), allocatable :: v3
inductive auxiliary
real(kind=wp), dimension(:,:,:,:), allocatable :: nn
neutral density array
real(kind=wp), dimension(:,:,:), allocatable :: Tn
neutral temperature and velocities
real(kind=wp), dimension(:,:,:), allocatable :: vn1
neutral temperature and velocities
real(kind=wp), dimension(:,:,:), allocatable :: vn2
neutral temperature and velocities
real(kind=wp), dimension(:,:,:), allocatable :: vn3
neutral temperature and velocities
real(kind=wp), dimension(:,:,:), allocatable :: Phiall
full-grid potential solution. To store previous time step value
real(kind=wp), dimension(:,:,:), allocatable :: iver
integrated volume emission rate of aurora calculated by GLOW
real(kind=wp) :: t = 0._wp
time from beginning of simulation (s) and time step (s)
real(kind=wp) :: dt = 1e-6_wp
time from beginning of simulation (s) and time step (s)
real(kind=wp) :: dtprev
time from beginning of simulation (s) and time step (s)
real(kind=wp) :: tout
time for next output and time between outputs
real(kind=wp) :: dtout
time for next output and time between outputs
real(kind=wp) :: tstart
temp. vars. for measuring performance of code blocks
real(kind=wp) :: tfin
temp. vars. for measuring performance of code blocks
integer :: it
time and species loop indices
integer :: isp
time and species loop indices
real(kind=wp), allocatable :: dl1
real(kind=wp), allocatable :: dl2
real(kind=wp), allocatable :: dl3
integer :: flagdneu
toggles neutral perturbations (0 - none; 1 - file-based neutral inputs)
integer :: interptype
toggles whether the neutral input data are interpreted (0 - Cartesian; 1 - axisymmetric)
real(kind=wp) :: dxn
finite differences for the neutral input data in the horizontal and vertical directions
real(kind=wp) :: drhon
finite differences for the neutral input data in the horizontal and vertical directions
real(kind=wp) :: dzn
finite differences for the neutral input data in the horizontal and vertical directions
real(kind=wp) :: sourcemlat
mag. lat./long for the neutral source location
real(kind=wp) :: sourcemlon
mag. lat./long for the neutral source location
character(len=:), allocatable :: sourcedir
directory where neutral input data are located
real(kind=wp) :: dtneu
time interval [s] in between neutral inputs
integer :: flagprecfile
PRECIPITATION FILE INPUT VARIABLES flag toggling precipitation file input (0 - no; 1 - yes)
real(kind=wp) :: dtprec
time interval between precip. inputs
character(len=:), allocatable :: precdir
directory containing precip. input files
integer :: flagE0file
ELECTRIC FIELD FILE INPUT VARIABLES flag toggling electric field (potential BCs) file input (0 - no; 1 - yes)
real(kind=wp) :: dtE0
time interval between electric field file inputs
character(len=:), allocatable :: E0dir
directory containing electric field file input data
integer :: flagglow
GLOW MODULE INPUT VARIABLES flag toggling GLOW module run (include aurora) (0 - no; 1 - yes)
real(kind=wp) :: dtglow
time interval between GLOW runs (s)
real(kind=wp) :: dtglowout
time interval between GLOW auroral outputs (s)
real(kind=wp) :: tglowout
time for next GLOW output
logical :: nooutput = .false.
FOR HANDLING OUTPUT
integer :: argc
character(len=256) :: argv
integer :: lid2in
integer :: lid3in
character(len=10) :: date
character(len=10) :: time
real(kind=wp), parameter :: dtscale = 2d0
TO CONTROL THROTTLING OF TIME STEP
MAIN PROGRAM
Call graph
gemini3d calls input_plasma, make_precip_fileinput, mpibreakdown, make_dneu, clear_grid, neutral_atmos, clear_potential_fileinput, read_configfile, mpi_manualgrid, dt_comm, create_outdir, mpisetup, clear_precip_fileinput, output_plasma, electrodynamics, output_aur, read_grid, grid_size, clear_dneu, neutral_perturb, dateinc, mpigrid
input_plasma calls input_plasma, input_root_mpi, input_workers_mpi
mpibreakdown calls mpi_finalize
clear_grid calls clear_grav
neutral_atmos calls neutral_atmos, meters, doy_calc, gtd7
read_configfile calls read_configfile, assert_file_exists, check_ini_io, expanduser, check_nml_io, assert_directory_exists
mpi_manualgrid calls id2grid
dt_comm calls mpi_recv, dt_calc, mpi_send
create_outdir calls create_outdir, mkdir, realbits_log, gitlog, compiler_log, copyfile
mpisetup calls mpi_init, mpi_comm_size, mpi_comm_rank
output_plasma calls output_plasma, output_root_stream_mpi, output_workers_mpi
electrodynamics calls electrodynamics_curv
output_aur calls output_aur, output_aur_workers, output_aur_root
read_grid calls read_grid, read_grid_root, read_grid_workers
grid_size calls mpi_recv, get_simsize3, mpi_send
neutral_perturb calls neutral_perturb_axisymm, neutral_perturb_3d, neutral_perturb_cart
dateinc calls day_wrap
mpigrid calls id2grid
neutral_perturb_axisymm calls gridproj_dneu2d, timeinterp_dneu, spaceinterp_dneu2d, read_dneu2d
neutral_perturb_3d calls gridproj_dneu3d, spaceinterp_dneu3d, read_dneu3d, timeinterp_dneu
get_simsize3 calls get_simsize3, lx
day_wrap calls day_wrap, daysmonth
electrodynamics_curv calls potential_workers_mpi, potential_root_mpi, capacitance, conductivities
neutral_perturb_cart calls gridproj_dneu2d, timeinterp_dneu, spaceinterp_dneu2d, read_dneu2d
output_aur_workers calls output_aur_workers, gather_send
mkdir calls mkdir
output_root_stream_mpi calls output_root_stream_mpi, date_filename, gather_recv
gridproj_dneu2d calls mpi_recv, get_simsize3, mpi_send, clear_unitvecs
expanduser calls home
input_root_mpi calls input_root_mpi, get_simsize3, bcast_send, tmp
output_aur_root calls output_aur_root, date_filename, gather_recv
potential_workers_mpi calls potential_workers_mpi, mpi_recv, bcast_recv, gather_send, grad3d3, elliptic_workers, halo_pot, integral3d1_curv_alt, integral3d1, grad3d2, grad3d1, div3d
read_grid_root calls mpi_send, g2, bcast_send3d_x2i, bcast_send1d_2, get_grid3, g1, bcast_send, bcast_send3d_x3i, bcast_send1d_3, g3, bcast_send3d_ghost
gridproj_dneu3d calls mpi_recv, get_simsize3, mpi_send, clear_unitvecs, slabrange
doy_calc calls daysmonth
spaceinterp_dneu3d calls interp3
assert_directory_exists calls assert_directory_exists
read_dneu3d calls dateinc, mpi_recv, date_filename
input_workers_mpi calls bcast_recv
gtd7 calls sw, pma, glob7s, tn3, tn2, tgn3, tn1, densm, gts7, pdm, tgn2, tgn1, pavgm, glatf, vtst7
output_workers_mpi calls gather_send
copyfile calls copyfile
read_grid_workers calls mpi_recv, g2, bcast_recv1d_2, bcast_recv3d_x2i, bcast_recv, g1, bcast_recv3d_ghost, bcast_recv1d_3, bcast_recv3d_x3i, g3
spaceinterp_dneu2d calls interp2
potential_root_mpi calls potential_root_mpi_curv
conductivities calls maxwell_colln, coulomb_colln
read_dneu2d calls dateinc, mpi_recv, mpi_send, date_filename
glob7s calls sw, swc, apt, plg, t
interp2 calls interp2
bcast_recv1d_2 calls bcast_recv1d_23_2
bcast_send3d_x2i calls bcast_send3d_x2i_23
densm calls splini, splint, xs, amax1, spline, zeta, ys
potential_root_mpi_curv calls potential_root_mpi_curv, mpi_send, bcast_send, grad3d3, halo_pot, integral3d1_curv_alt, integral3d1, grad3d2, grad3d1, gather_recv, div3d, potential2d_polarization_periodic, potential3d_fieldresolved_decimate, potentialbcs2d, potential2d_fieldresolved, potentialbcs2d_fileinput, potential2d_polarization
bcast_recv3d_x2i calls bcast_recv3d_x2i_23
gts7 calls sw, pma, glob7s, tn1, pdm, tgn1, vtst7, pt, alog, ccor, mt, alpha, ptl, densu, zn1, dnet, scalh, altl, ptm, amod, ps, pd, globe7, ccor2, pdl
bcast_send1d_2 calls bcast_send1d_23_2
get_grid3 calls get_grid3, htmp
bcast_recv calls bcast_recv2d_23, bcast_recv4d_23, bcast_recv3d_23, bcast_recv1d_23
bcast_recv3d_ghost calls bcast_recv3d_ghost_23
bcast_send calls bcast_send1d_23, bcast_send2d_23, bcast_send4d_23, bcast_send3d_23
bcast_send3d_x3i calls bcast_send3d_x3i_23
gather_send calls gather_send4d_23, gather_send2d_23, gather_send3d_23
bcast_send1d_3 calls bcast_send1d_23_3
bcast_recv1d_3 calls bcast_recv1d_23_3
bcast_recv3d_x3i calls bcast_recv3d_x3i_23
date_filename calls utsec2filestem
vtst7 calls sw, glatl, stll, swc, swl, fl, fal, secl, apl, gll, iydl, swcl
bcast_send3d_ghost calls bcast_send3d_ghost_23
bcast_recv1d_23_3 calls bcast_recv1d_23_3, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
bcast_recv3d_x2i_23 calls bcast_recv3d_x2i_23, mpi_recv
splini calls amin1
densu calls splini, splint, xs, amax1, spline, zeta, ys
dnet calls alog
bcast_send1d_23_3 calls bcast_send1d_23_3, id2grid
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
bcast_send1d_23_2 calls bcast_send1d_23_2, id2grid
bcast_send3d_x2i_23 calls bcast_send3d_x2i_23, mpi_send, slabinds
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_recv3d_x3i_23 calls bcast_recv3d_x3i_23, mpi_recv
grad3d3 calls grad3d3_curv_23
bcast_recv1d_23_2 calls bcast_recv1d_23_2, mpi_recv
spline calls u
bcast_recv3d_ghost_23 calls bcast_recv3d_ghost_23, mpi_recv
elliptic_workers calls check_mumps_status, quiet_mumps, mumps_exec
halo_pot calls halo
gather_send4d_23 calls gather_send4d_23, mpi_send
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
integral3d1_curv_alt calls integral3d1_curv_alt
integral3d1 calls integral3d1_curv
gather_send2d_23 calls gather_send2d_23, mpi_send
grad3d2 calls grad3d2_curv_23
bcast_send3d_ghost_23 calls bcast_send3d_ghost_23, mpi_send, slabinds
gather_send3d_23 calls gather_send3d_23, mpi_send
bcast_send3d_x3i_23 calls bcast_send3d_x3i_23, mpi_send, slabinds
grad3d1 calls grad3d1_curv_23
globe7 calls sw, swc, apt, plg, t, sumex, sg0, g0
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
gather_recv calls gather_recv4d_23, gather_recv3d_23, gather_recv2d_23
div3d calls div3d_curv_23
utsec2filestem calls day_wrap
gather_recv4d_23 calls gather_recv4d_23, mpi_recv, slabinds
potential2d_polarization_periodic calls potential2d_polarization_periodic, grad2d1_curv_alt, elliptic2d_polarization_periodic, grad2d3_curv_periodic
gather_recv3d_23 calls gather_recv3d_23, mpi_recv, slabinds
grad3d3_curv_23 calls grad3d3_curv_23
gather_recv2d_23 calls gather_recv2d_23, mpi_recv, slabinds
potential3d_fieldresolved_decimate calls grad3d3, grad3d2, grad3d1, interp1, elliptic3d_cart
div3d_curv_23 calls div3d_curv_23
potential2d_fieldresolved calls potential2d_fieldresolved, elliptic2d_cart
grad3d1_curv_23 calls grad3d1_curv_23
integral3d1_curv calls integral3d1_curv
grad3d2_curv_23 calls grad3d2_curv_23
potentialbcs2d_fileinput calls dateinc, interp2, date_filename, interp1, get_grid2, get_simsize2
halo calls halo_23
potential2d_polarization calls potential2d_polarization, grad2d3, grad2d1_curv_alt, elliptic2d_polarization
halo_23 calls halo_23, mpi_irecv, grid2id, mpi_isend, mpi_waitall
elliptic3d_cart calls elliptic3d_cart, check_mumps_status, quiet_mumps, mumps_exec, mumps_perm
slabinds calls id2grid
get_grid2 calls get_grid2
get_simsize2 calls get_simsize2
grad2d3 calls grad2d3_curv_23
grad2d1_curv_alt calls grad2d1_curv_alt_23
elliptic2d_polarization calls elliptic2d_polarization, check_mumps_status, quiet_mumps, mumps_exec, mumps_perm
elliptic2d_cart calls elliptic2d_cart, check_mumps_status, quiet_mumps, mumps_exec, mumps_perm
elliptic2d_polarization_periodic calls elliptic2d_polarization_periodic, check_mumps_status, quiet_mumps, mumps_exec, mumps_perm