MagCalc – GEMINI3D
MagCalc Program
373 statements
Source File
Uses
iso_fortran_env
ieee_arithmetic
phys_consts
grid
mesh
timeutils
io
mpimod
Need program statement for FORD THIS IS THE MAIN PROGRAM FOR COMPUTING MAGNETIC FIELDS FROM OUTPUT FROM A SIMULATIONS DONE BY GEMINI3D. THIS PROGRAM VERY MUCH MIRRORS THE SETUP OF THE MAIN GEMINI.F90 CODE.
INITIALIZE MESSING PASSING VARIABLES, IDS ETC. CHECK THE GRID SIZE AND ESTABLISH A PROCESS GRID LOAD UP THE GRID STRUCTURE/MODULE VARS. FOR THIS SIMULATION - THIS ALSO PERMUTES DIMENSIONS OF 2D GRID, IF NEEDED read in a previously generated grid from filename listed in input file, distribute subgrids to individual workers a 2D simulation was done, which changes how the integrations go... this file contains the field points at which we are computing magnetic perturbations, it will be copied into the output directory
the integrations are being treated as Cartesian so flatten out the local spherical coordinates into cartesian, as well GET END VOLUMES SO THE INTEGRALS ARE 'COMPLETE' need to define the differential volume on the edge of this x3-slab in
COMPUTE NEEDED PROJECTIONS fourth dimension of unit vectors is the 3 Cartesian components of each vector DEALLOCATE GRID MODULE VARIABLES TO SAVE MEMORY (PROGRAM DOESN'T ACTUALLY NEED THESE ONCE X,Y,Z CREATED STORAGE FOR MAGNETIC FIELD CALCULATIONS latter is cell centered hence -1 in size, max is needed to prevent zero sized array only used by root, but I think workers need to have space allocated for this
MAIN LOOP FIXME: MAY BE MISSING A CORNER POINT HERE??? NO I THINK IT'S OKAY BASED ON SOME SQUARES I DREW, haha...
DO WE NEED TO CHECK HERE FOR DIV BY ZERO??? ALSO IN 2D WE KNOW THAT WE ARE ONLY DIVIDED IN THE 3 DIMENSION SO THERE IS NO NEED TO WORRY ABOUT ADDING A 'TOP' ETC.
without dim= input it just sums everything which is what we want
without dim= input it just sums everything which is what we want DEALLOCATE MAIN PROGRAM DATA SHUT DOWN MPI
Calls
Contents
Variables
ymd UTsec UTsec0 tdur activ tcfl Teinf potsolve flagperiodic flagoutput flagcap infile outdir indatsize indatgrid fieldpointfile x J1 J2 J3 t dt tout dtout tstart tfin it isp flag2D xp yp zp xf yf zf r theta phi dV ipoints lpoints proj_e1er proj_e2er proj_e3er proj_e1etheta proj_e2etheta proj_e3etheta proj_e1ephi proj_e2ephi proj_e3ephi Jx Jy Jz Rx Ry Rz Rcubed integrand integrandavg alt Br Btheta Bphi Brall Bthetaall Bphiall Jxend Jyend Jzend Rxend Ryend Rzend Rcubedend dVend integrandend integrandavgend Jxtop Jytop Jztop Rxtop Rytop Rztop Rcubedtop dVtop integrandtop integrandavgtop ix1 ix2 ix3 rmean thetamean flagdneu interptype dxn drhon dzn sourcemlat sourcemlon sourcedir dtneu flagprecfile dtprec precdir flagE0file dtE0 E0dir flagglow dtglow dtglowout lid2in lid3in argc ierr argv file_exists R3min Rmin
Variables
Type Attributes Name Initial
integer, dimension(3) :: ymd
VARIABLES READ IN FROM CONFIG.DAT FILE year,month,day of simulation
real(kind=wp) :: UTsec
UT (s)
real(kind=wp) :: UTsec0
UT start time of simulation (s)
real(kind=wp) :: tdur
duration of simulation
real(kind=wp), dimension(3) :: activ
f10.7a,f10.7,ap
real(kind=wp) :: tcfl
target CFL number
real(kind=wp) :: Teinf
exospheric temperature
integer :: potsolve
what type of potential solve
integer :: flagperiodic
toggles whether or not the grid is treated as periodic in the x3 dimension (affects some of the message passing)
integer :: flagoutput
what type of output to do (1 - everything; 2 - avg'd parms.; 3 - ne only)
integer :: flagcap
internal capacitance?
character(len=:), allocatable :: infile
INPUT AND OUTPUT FILES
character(len=:), allocatable :: outdir
character(len=:), allocatable :: indatsize
character(len=:), allocatable :: indatgrid
character(len=:), allocatable :: fieldpointfile
GRID STRUCTURE
type(curvmesh) :: x
real(kind=wp), dimension(:,:,:), allocatable :: J1
real(kind=wp), dimension(:,:,:), allocatable :: J2
real(kind=wp), dimension(:,:,:), allocatable :: J3
real(kind=wp) :: t = 0._wp
real(kind=wp) :: dt
real(kind=wp) :: tout
real(kind=wp) :: dtout
real(kind=wp) :: tstart
real(kind=wp) :: tfin
integer :: it
integer :: isp
integer :: flag2D
real(kind=wp), dimension(:,:,:), allocatable :: xp
real(kind=wp), dimension(:,:,:), allocatable :: yp
real(kind=wp), dimension(:,:,:), allocatable :: zp
real(kind=wp), dimension(:), allocatable :: xf
real(kind=wp), dimension(:), allocatable :: yf
real(kind=wp), dimension(:), allocatable :: zf
real(kind=wp), dimension(:), allocatable :: r
real(kind=wp), dimension(:), allocatable :: theta
real(kind=wp), dimension(:), allocatable :: phi
real(kind=wp), dimension(:,:,:), allocatable :: dV
integer :: ipoints
integer :: lpoints
real(kind=wp), dimension(:,:,:), allocatable :: proj_e1er
real(kind=wp), dimension(:,:,:), allocatable :: proj_e2er
real(kind=wp), dimension(:,:,:), allocatable :: proj_e3er
real(kind=wp), dimension(:,:,:), allocatable :: proj_e1etheta
real(kind=wp), dimension(:,:,:), allocatable :: proj_e2etheta
real(kind=wp), dimension(:,:,:), allocatable :: proj_e3etheta
real(kind=wp), dimension(:,:,:), allocatable :: proj_e1ephi
real(kind=wp), dimension(:,:,:), allocatable :: proj_e2ephi
real(kind=wp), dimension(:,:,:), allocatable :: proj_e3ephi
real(kind=wp), dimension(:,:,:), allocatable :: Jx
real(kind=wp), dimension(:,:,:), allocatable :: Jy
real(kind=wp), dimension(:,:,:), allocatable :: Jz
real(kind=wp), dimension(:,:,:), allocatable :: Rx
real(kind=wp), dimension(:,:,:), allocatable :: Ry
real(kind=wp), dimension(:,:,:), allocatable :: Rz
real(kind=wp), dimension(:,:,:), allocatable :: Rcubed
real(kind=wp), dimension(:,:,:), allocatable :: integrand
real(kind=wp), dimension(:,:,:), allocatable :: integrandavg
real(kind=wp), dimension(:,:,:), allocatable :: alt
real(kind=wp), dimension(:), allocatable :: Br
real(kind=wp), dimension(:), allocatable :: Btheta
real(kind=wp), dimension(:), allocatable :: Bphi
real(kind=wp), dimension(:), allocatable :: Brall
real(kind=wp), dimension(:), allocatable :: Bthetaall
real(kind=wp), dimension(:), allocatable :: Bphiall
real(kind=wp), dimension(:,:), allocatable :: Jxend
real(kind=wp), dimension(:,:), allocatable :: Jyend
real(kind=wp), dimension(:,:), allocatable :: Jzend
real(kind=wp), dimension(:,:), allocatable :: Rxend
real(kind=wp), dimension(:,:), allocatable :: Ryend
real(kind=wp), dimension(:,:), allocatable :: Rzend
real(kind=wp), dimension(:,:), allocatable :: Rcubedend
real(kind=wp), dimension(:,:), allocatable :: dVend
real(kind=wp), dimension(:,:), allocatable :: integrandend
real(kind=wp), dimension(:,:), allocatable :: integrandavgend
real(kind=wp), dimension(:,:), allocatable :: Jxtop
real(kind=wp), dimension(:,:), allocatable :: Jytop
real(kind=wp), dimension(:,:), allocatable :: Jztop
real(kind=wp), dimension(:,:), allocatable :: Rxtop
real(kind=wp), dimension(:,:), allocatable :: Rytop
real(kind=wp), dimension(:,:), allocatable :: Rztop
real(kind=wp), dimension(:,:), allocatable :: Rcubedtop
real(kind=wp), dimension(:,:), allocatable :: dVtop
real(kind=wp), dimension(:,:), allocatable :: integrandtop
real(kind=wp), dimension(:,:), allocatable :: integrandavgtop
integer :: ix1
integer :: ix2
integer :: ix3
real(kind=wp) :: rmean
real(kind=wp) :: thetamean
integer :: flagdneu
integer :: interptype
real(kind=wp) :: dxn
real(kind=wp) :: drhon
real(kind=wp) :: dzn
real(kind=wp) :: sourcemlat
real(kind=wp) :: sourcemlon
character(len=:), allocatable :: sourcedir
real(kind=wp) :: dtneu
integer :: flagprecfile
real(kind=wp) :: dtprec
character(len=:), allocatable :: precdir
ELECTRIC FIELD FILE INPUT VARIABLES (UNUSED)
integer :: flagE0file
real(kind=wp) :: dtE0
character(len=:), allocatable :: E0dir
GLOW MODULE INPUT VARIABLES
integer :: flagglow
real(kind=wp) :: dtglow
real(kind=wp) :: dtglowout
FOR SPECIFYING THE PROCESS GRID
integer :: lid2in
FOR HANDLING INPUT
integer :: lid3in
FOR HANDLING INPUT
integer :: argc
integer :: ierr
character(len=256) :: argv
logical :: file_exists
REGULATOR FOR 1/R^3
real(kind=wp), parameter :: R3min = 1d9
real(kind=wp), parameter :: Rmin = 5d3
## MAIN PROGRAM
Call graph
magcalc calls halo_end, mpi_manualgrid, output_magfields, mpigrid, clear_grid, mpisetup, input_plasma_currents, dateinc, mpibreakdown, mpi_reduce, read_grid, read_configfile, create_outdir_mag, grid_size
halo_end calls halo_end_23
mpi_manualgrid calls id2grid
output_magfields calls output_magfields, date_filename
mpigrid calls id2grid
clear_grid calls clear_grav
mpisetup calls mpi_comm_rank, mpi_init, mpi_comm_size
input_plasma_currents calls input_plasma_currents, input_root_currents, input_workers_currents
dateinc calls day_wrap
mpibreakdown calls mpi_finalize
read_grid calls read_grid, read_grid_root, read_grid_workers
read_configfile calls read_configfile, assert_file_exists, check_nml_io, assert_directory_exists, check_ini_io, expanduser
create_outdir_mag calls create_outdir_mag, mkdir, copyfile
grid_size calls mpi_recv, mpi_send, get_simsize3
day_wrap calls day_wrap, daysmonth
get_simsize3 calls get_simsize3, lx
halo_end_23 calls halo_end_23, mpi_irecv, mpi_waitall, grid2id, mpi_isend
input_root_currents calls input_root_currents, date_filename, bcast_send
mkdir calls mkdir
read_grid_root calls mpi_send, g2, bcast_send3d_x2i, bcast_send1d_2, get_grid3, g1, bcast_send, bcast_send3d_x3i, bcast_send1d_3, g3, bcast_send3d_ghost
read_grid_workers calls mpi_recv, g2, bcast_recv1d_2, bcast_recv3d_x2i, bcast_recv, g1, bcast_recv3d_ghost, bcast_recv1d_3, bcast_recv3d_x3i, g3
assert_directory_exists calls assert_directory_exists
date_filename calls utsec2filestem
expanduser calls home
copyfile calls copyfile
input_workers_currents calls bcast_recv
bcast_recv1d_2 calls bcast_recv1d_23_2
bcast_send3d_x2i calls bcast_send3d_x2i_23
bcast_recv3d_x2i calls bcast_recv3d_x2i_23
utsec2filestem calls day_wrap
bcast_send1d_2 calls bcast_send1d_23_2
get_grid3 calls get_grid3, htmp
bcast_recv calls bcast_recv2d_23, bcast_recv4d_23, bcast_recv3d_23, bcast_recv1d_23
bcast_recv3d_ghost calls bcast_recv3d_ghost_23
bcast_send calls bcast_send1d_23, bcast_send2d_23, bcast_send4d_23, bcast_send3d_23
bcast_send3d_x3i calls bcast_send3d_x3i_23
bcast_send1d_3 calls bcast_send1d_23_3
bcast_recv1d_3 calls bcast_recv1d_23_3
bcast_recv3d_x3i calls bcast_recv3d_x3i_23
bcast_send3d_ghost calls bcast_send3d_ghost_23
bcast_recv1d_23_3 calls bcast_recv1d_23_3, mpi_recv
bcast_recv2d_23 calls bcast_recv2d_23, mpi_recv
bcast_recv3d_x2i_23 calls bcast_recv3d_x2i_23, mpi_recv
bcast_send1d_23_3 calls bcast_send1d_23_3, id2grid
bcast_recv4d_23 calls bcast_recv4d_23, mpi_recv
bcast_send2d_23 calls bcast_send2d_23, mpi_send, slabinds
bcast_recv3d_23 calls bcast_recv3d_23, mpi_recv
bcast_send1d_23_2 calls bcast_send1d_23_2, id2grid
bcast_send3d_x2i_23 calls bcast_send3d_x2i_23, mpi_send, slabinds
bcast_recv3d_x3i_23 calls bcast_recv3d_x3i_23, mpi_recv
bcast_recv1d_23_2 calls bcast_recv1d_23_2, mpi_recv
bcast_recv3d_ghost_23 calls bcast_recv3d_ghost_23, mpi_recv
bcast_send4d_23 calls bcast_send4d_23, mpi_send, slabinds
bcast_send3d_ghost_23 calls bcast_send3d_ghost_23, mpi_send, slabinds
bcast_send3d_x3i_23 calls bcast_send3d_x3i_23, mpi_send, slabinds
bcast_send3d_23 calls bcast_send3d_23, mpi_send, slabinds
slabinds calls id2grid