MHD1D_shock – GEMINI3D
MHD1D_shock Program
123 statements
Source File
Uses
advec
Calls
Contents
Variables
method npts tcfl pi amu kb gammap mu0 stride dx1i x1 rhom rhou1 rhou2 rhou3 B1 B2 B3 rhoeps u1 u2 u3 x1i v1i dx1 lx1 it ix1 u t dt dtout tdur xi toutnext Q p grad1B1u3 rhoepshalf sourceterm du1full grad1u1 vA vsnd Ti
Functions
derivative
Subroutines
writearray
Variables
Type Attributes Name Initial
integer, parameter :: method = 1
integer, parameter :: npts = 1001
real(kind=wp), parameter :: tcfl = 0.75
real(kind=wp), parameter :: pi = 3.14
real(kind=wp), parameter :: amu = 1.67e-27
real(kind=wp), parameter :: kb = 1.38e-23
real(kind=wp), parameter :: gammap = 5.0/3.0
real(kind=wp), parameter :: mu0 = 4.0*pi*1e-7
real(kind=wp), parameter :: stride = 2e3
real(kind=wp), dimension(npts) :: dx1i
real(kind=wp), dimension(-1:npts+2) :: x1
real(kind=wp), dimension(-1:npts+2) :: rhom
real(kind=wp), dimension(-1:npts+2) :: rhou1
real(kind=wp), dimension(-1:npts+2) :: rhou2
real(kind=wp), dimension(-1:npts+2) :: rhou3
real(kind=wp), dimension(-1:npts+2) :: B1
real(kind=wp), dimension(-1:npts+2) :: B2
real(kind=wp), dimension(-1:npts+2) :: B3
real(kind=wp), dimension(-1:npts+2) :: rhoeps
real(kind=wp), dimension(-1:npts+2) :: u1
real(kind=wp), dimension(-1:npts+2) :: u2
real(kind=wp), dimension(-1:npts+2) :: u3
real(kind=wp), dimension(npts+1) :: x1i
real(kind=wp), dimension(npts+1) :: v1i
real(kind=wp), dimension(0:npts+2) :: dx1
integer :: lx1
integer :: it
integer :: ix1
integer :: u
real(kind=wp) :: t = 0
real(kind=wp) :: dt = 1e-6
real(kind=wp) :: dtout = 5
real(kind=wp) :: tdur = 55
real(kind=wp) :: xi = 2
real(kind=wp) :: toutnext
real(kind=wp), dimension(npts) :: Q
real(kind=wp), dimension(npts) :: p
real(kind=wp), dimension(npts) :: grad1B1u3
real(kind=wp), dimension(npts) :: rhoepshalf
real(kind=wp), dimension(npts) :: sourceterm
real(kind=wp), dimension(npts) :: du1full
real(kind=wp), dimension(npts) :: grad1u1
real(kind=wp), dimension(npts) :: vA
real(kind=wp), dimension(npts) :: vsnd
real(kind=wp) :: Ti = 8000
Functions
function derivative(f, dx)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: f
real(kind=wp), intent(in), dimension(:) :: dx
Return Value real(kind=wp), dimension(1:size(f))
Subroutines
subroutine writearray(fileunit, array)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fileunit
real(kind=wp), intent(in), dimension(:) :: array
Call graph
mhd1d_shock calls writearray, advec1d_mc, derivative
advec1d_mc calls minmod