test_fang – GEMINI3D
test_fang Program
85 statements
Source File
Uses
iso_fortran_env
phys_consts
ionrate
Need program statement for FORD Reproduces data of: * Figure 3 in https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2008JA013384 * Figure 2 in Fang 2010
Calls
Contents
Variables
i argc Q0_erg f107 f107a Ap glat glon UTsec altrange a alt_km E0_keV Qtot08 Qtot10 doy massden_gcm3 meanmass_g
Subroutines
parse_arg
Variables
Type Attributes Name Initial
integer :: i
integer :: argc
real(kind=wp) :: Q0_erg
real(kind=wp) :: f107
real(kind=wp) :: f107a
real(kind=wp) :: Ap
real(kind=wp) :: glat
real(kind=wp) :: glon
real(kind=wp) :: UTsec
real(kind=wp) :: altrange(3)
real(kind=wp) :: a
real(kind=wp), allocatable :: alt_km(:)
real(kind=wp), allocatable :: E0_keV(:)
real(kind=wp), allocatable :: Qtot08(:,:)
real(kind=wp), allocatable :: Qtot10(:,:)
integer :: doy
real(kind=wp) :: massden_gcm3
real(kind=wp) :: meanmass_g
Subroutines
subroutine parse_arg(iarg, val)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iarg
class(*), intent(out) :: val
Call graph
test_fang calls ionization_fang2010, parse_arg, ionization_fang2008
ionization_fang2010 calls meters, gravity_accel, tselec, fang2010
ionization_fang2008 calls meters, gravity_accel, fang2008, tselec
tselec calls sw, sav, swc, svv, amod