test_potential2d – GEMINI3D
test_potential2d Program
109 statements
Source File
Uses
mpi
phys_consts
PDEelliptic
h5fortran
Need program statement for FORD SOLVE LAPLACE'S EQUATION IN 2D USING PDEelliptic, mumps-based libraries
Set things up to give debug output Set up grid and compute differences needed for solution of PDE Define boundary conditions for this problem Make the call to PDE elliptic solver library, note the separate calls for root vs. workers Also have root compute an analytical solution and test against numerical
Calls
Contents
Variables
hout lx1 lx2 lx3 ix1 ix2 ix3 x1 x2 x3 x1i x2i x3i dx1 dx2 dx3 dx1i dx2i dx3i Vminx2 Vmaxx2 Vminx3 Vmaxx3 Vminx22 Vmaxx22 Vminx32 Vmaxx32 tstart tfin ierr myid lid Phi Phi2squeeze Phitrue errorMUMPS errorMUMPS2 Phi2 Phi0 v2 v3 A Ap App B C D A2 Ap2 srcterm srcterm2 perflag it dt gridflag flagdirich outfile
Variables
Type Attributes Name Initial
type(hdf5_file) :: hout
integer, parameter :: lx1 = 256
integer, parameter :: lx2 = 256
integer, parameter :: lx3 = 256
integer :: ix1
integer :: ix2
integer :: ix3
real(kind=wp), dimension(-1:lx1+2) :: x1
real(kind=wp), dimension(-1:lx2+2) :: x2
real(kind=wp), dimension(-1:lx3+2) :: x3
real(kind=wp), dimension(1:lx1+1) :: x1i
real(kind=wp), dimension(1:lx2+2) :: x2i
real(kind=wp), dimension(1:lx3+2) :: x3i
real(kind=wp), dimension(0:lx1+2) :: dx1
real(kind=wp), dimension(0:lx2+2) :: dx2
real(kind=wp), dimension(0:lx3+2) :: dx3
real(kind=wp), dimension(1:lx1) :: dx1i
real(kind=wp), dimension(1:lx2) :: dx2i
real(kind=wp), dimension(1:lx3) :: dx3i
real(kind=wp), dimension(lx3) :: Vminx2
real(kind=wp), dimension(lx3) :: Vmaxx2
real(kind=wp), dimension(lx2) :: Vminx3
real(kind=wp), dimension(lx2) :: Vmaxx3
real(kind=wp), dimension(1,lx3) :: Vminx22
real(kind=wp), dimension(1,lx3) :: Vmaxx22
real(kind=wp), dimension(lx2,1) :: Vminx32
real(kind=wp), dimension(lx2,1) :: Vmaxx32
real(kind=wp) :: tstart
real(kind=wp) :: tfin
integer :: ierr
integer :: myid
integer :: lid
real(kind=wp), dimension(lx2,lx3) :: Phi
real(kind=wp), dimension(lx2,lx3) :: Phi2squeeze
real(kind=wp), dimension(lx2,lx3) :: Phitrue
real(kind=wp), dimension(lx2,lx3) :: errorMUMPS
real(kind=wp), dimension(lx2,lx3) :: errorMUMPS2
real(kind=wp), dimension(lx2,1,lx3) :: Phi2
real(kind=wp), dimension(lx2,lx3) :: Phi0 = 1
real(kind=wp), dimension(lx2,lx3) :: v2 = 1
real(kind=wp), dimension(lx2,lx3) :: v3 = 1
real(kind=wp), dimension(lx2,lx3) :: A = 1
real(kind=wp), dimension(lx2,lx3) :: Ap = 1
real(kind=wp), dimension(lx2,lx3) :: App = 0
real(kind=wp), dimension(lx2,lx3) :: B = 0
real(kind=wp), dimension(lx2,lx3) :: C = 0
real(kind=wp), dimension(lx2,lx3) :: D = 0
real(kind=wp), dimension(lx2,1,lx3) :: A2 = 1
real(kind=wp), dimension(lx2,1,lx3) :: Ap2 = 1
real(kind=wp), dimension(lx2,lx3) :: srcterm = 0
real(kind=wp), dimension(lx2,1,lx3) :: srcterm2 = 0
logical :: perflag = .false.
integer :: it = 1
real(kind=wp) :: dt = 1
integer :: gridflag = 1
integer :: flagdirich = 1
character(len=*), parameter :: outfile = 'test_potential2d.h5'
mpi starting
Call graph
test_potential2d calls mpi_comm_rank, elliptic_workers, mpi_finalize, mpi_init, elliptic2d_cart, elliptic2d_polarization, mpi_comm_size
elliptic_workers calls mumps_exec, check_mumps_status, quiet_mumps
elliptic2d_cart calls elliptic2d_cart, mumps_exec, check_mumps_status, quiet_mumps, mumps_perm
elliptic2d_polarization calls elliptic2d_polarization, mumps_exec, check_mumps_status, quiet_mumps, mumps_perm