test_dayrollover – GEMINI3D
test_dayrollover Program
90 statements
Source File
Uses
iso_fortran_env
phys_consts
timeutils
test day rollover leap year tests
day rollover checks date rollover tests multi-day rollover
Calls
Contents
Variables
ymd year month day dtsec UTsec
Variables
Type Attributes Name Initial
integer :: ymd(3)
integer :: year
integer :: month
integer :: day
real(kind=wp) :: dtsec
real(kind=wp) :: UTsec
Call graph
test_dayrollover calls day_wrap, dateinc, doy_calc
day_wrap calls day_wrap, daysmonth
dateinc calls day_wrap
doy_calc calls daysmonth