test_potential3D – GEMINI3D
test_potential3D Program
328 statements
Source File
Uses
mpi
Need program statement for FORD
Calls
Contents
Variables
mumps_par ierr npts1 npts2 npts3 lk lent ix1 ix2 ix3 lx1 lx2 lx3 iPhi ient ir ic M b dx1 Vminx1 Vmaxx1 Vminx2 Vmaxx2 Vminx3 Vmaxx3 Mfull tstart tfin
Derived Types
DMUMPS_STRUC
Subroutines
writearray write2Darray
Variables
Type Attributes Name Initial
type(DMUMPS_STRUC) :: mumps_par
integer :: ierr
integer, parameter :: npts1 = 256
integer, parameter :: npts2 = 256
integer, parameter :: npts3 = 12
integer, parameter :: lk = npts1*npts2*npts3
integer :: lent
integer :: ix1
integer :: ix2
integer :: ix3
integer :: lx1
integer :: lx2
integer :: lx3
integer :: iPhi
integer :: ient
integer, dimension(:), allocatable :: ir
integer, dimension(:), allocatable :: ic
real(kind=8), dimension(:), allocatable :: M
real(kind=8), dimension(:), allocatable :: b
real(kind=8) :: dx1
real(kind=8), dimension(npts2,npts3) :: Vminx1
real(kind=8), dimension(npts2,npts3) :: Vmaxx1
real(kind=8), dimension(npts1,npts3) :: Vminx2
real(kind=8), dimension(npts1,npts3) :: Vmaxx2
real(kind=8), dimension(npts1,npts2) :: Vminx3
real(kind=8), dimension(npts1,npts2) :: Vmaxx3
real(kind=8), dimension(:,:), allocatable :: Mfull
real(kind=8) :: tstart
real(kind=8) :: tfin
Derived Types
type, sequence :: DMUMPS_STRUC
Components
Type Visibility Attributes Name Initial
integer, public :: COMM
integer, public :: SYM
integer, public :: PAR
integer, public :: JOB
integer, public :: N
integer, public :: NZ
integer(kind=8), public :: NNZ
double precision, public, DIMENSION(:), POINTER :: A
integer, public, DIMENSION(:), POINTER :: IRN
integer, public, DIMENSION(:), POINTER :: JCN
double precision, public, DIMENSION(:), POINTER :: COLSCA
double precision, public, DIMENSION(:), POINTER :: ROWSCA
double precision, public, DIMENSION(:), POINTER :: pad0
integer, public :: NZ_loc
integer, public :: pad1
integer(kind=8), public :: NNZ_loc
integer, public, DIMENSION(:), POINTER :: IRN_loc
integer, public, DIMENSION(:), POINTER :: JCN_loc
double precision, public, DIMENSION(:), POINTER :: A_loc
double precision, public, DIMENSION(:), POINTER :: pad2
integer, public :: NELT
integer, public :: pad3
integer, public, DIMENSION(:), POINTER :: ELTPTR
integer, public, DIMENSION(:), POINTER :: ELTVAR
double precision, public, DIMENSION(:), POINTER :: A_ELT
double precision, public, DIMENSION(:), POINTER :: pad4
integer, public, DIMENSION(:), POINTER :: PERM_IN
double precision, public, DIMENSION(:), POINTER :: RHS
double precision, public, DIMENSION(:), POINTER :: REDRHS
double precision, public, DIMENSION(:), POINTER :: RHS_SPARSE
double precision, public, DIMENSION(:), POINTER :: SOL_loc
double precision, public, DIMENSION(:), POINTER :: RHS_loc
integer, public, DIMENSION(:), POINTER :: IRHS_SPARSE
integer, public, DIMENSION(:), POINTER :: IRHS_PTR
integer, public, DIMENSION(:), POINTER :: ISOL_loc
integer, public, DIMENSION(:), POINTER :: IRHS_loc
integer, public :: LRHS
integer, public :: NRHS
integer, public :: NZ_RHS
integer, public :: Nloc_RHS
integer, public :: LRHS_loc
integer, public :: LREDRHS
integer, public :: LSOL_loc
integer, public :: pad5
integer, public :: ICNTL(60)
integer, public :: INFO(80)
integer, public :: INFOG(80)
double precision, public :: COST_SUBTREES
double precision, public :: CNTL(15)
double precision, public :: RINFO(40)
double precision, public :: RINFOG(40)
integer, public :: METIS_OPTIONS(40)
integer, public, DIMENSION(:), POINTER :: SYM_PERM
integer, public, DIMENSION(:), POINTER :: UNS_PERM
integer, public :: NPROW
integer, public :: NPCOL
integer, public :: MBLOCK
integer, public :: NBLOCK
integer, public :: SCHUR_MLOC
integer, public :: SCHUR_NLOC
integer, public :: SCHUR_LLD
integer, public :: SIZE_SCHUR
double precision, public, DIMENSION(:), POINTER :: SCHUR
double precision, public, DIMENSION(:), POINTER :: SCHUR_CINTERFACE
integer, public, DIMENSION(:), POINTER :: LISTVAR_SCHUR
integer, public, DIMENSION(:), POINTER :: MAPPING
character(len=30), public :: VERSION_NUMBER
character(len=255), public :: OOC_TMPDIR
character(len=63), public :: OOC_PREFIX
character(len=255), public :: WRITE_PROBLEM
character(len=255), public :: SAVE_DIR
character(len=255), public :: SAVE_PREFIX
character(len=7), public :: pad8
integer(kind=8), public :: KEEP8(150)
integer(kind=8), public :: MAX_SURF_MASTER
integer, public :: INST_Number
integer, public :: COMM_NODES
integer, public :: MYID_NODES
integer, public :: COMM_LOAD
integer, public :: MYID
integer, public :: NPROCS
integer, public :: NSLAVES
integer, public :: ASS_IRECV
integer, public :: LBUFR
integer, public :: LBUFR_BYTES
integer, public, DIMENSION(:), POINTER :: BUFR
integer, public, DIMENSION(:), POINTER :: IS
integer, public, DIMENSION(:), POINTER :: IS1
integer, public :: MAXIS1
integer, public :: Deficiency
integer, public :: KEEP(500)
integer, public :: LNA
integer, public :: NBSA
integer, public, POINTER, DIMENSION(:) :: STEP
integer, public, POINTER, DIMENSION(:) :: NE_STEPS
integer, public, POINTER, DIMENSION(:) :: ND_STEPS
integer, public, POINTER, DIMENSION(:) :: Step2node
integer, public, POINTER, DIMENSION(:) :: FRERE_STEPS
integer, public, POINTER, DIMENSION(:) :: DAD_STEPS
integer, public, POINTER, DIMENSION(:) :: FILS
integer, public, POINTER, DIMENSION(:) :: FRTPTR
integer, public, POINTER, DIMENSION(:) :: FRTELT
integer(kind=8), public, POINTER, DIMENSION(:) :: PTRAR
integer, public, POINTER, DIMENSION(:) :: NA
integer, public, POINTER, DIMENSION(:) :: PROCNODE_STEPS
integer, public, DIMENSION(:), POINTER :: PTLUST_S
integer(kind=8), public, DIMENSION(:), POINTER :: PTRFAC
double precision, public, DIMENSION(:), POINTER :: S
integer, public, DIMENSION(:), POINTER :: PROCNODE
integer, public, DIMENSION(:), POINTER :: INTARR
double precision, public, DIMENSION(:), POINTER :: DBLARR
integer, public :: NELT_loc
integer, public :: LELTVAR
integer, public, DIMENSION(:), POINTER :: ELTPROC
integer, public, DIMENSION(:,:), POINTER :: CANDIDATES
integer, public, DIMENSION(:), POINTER :: ISTEP_TO_INIV2
integer, public, DIMENSION(:), POINTER :: FUTURE_NIV2
integer, public, DIMENSION(:,:), POINTER :: TAB_POS_IN_PERE
logical, public, DIMENSION(:), POINTER :: I_AM_CAND
integer, public, DIMENSION(:), POINTER :: MEM_DIST
integer, public, DIMENSION(:), POINTER :: POSINRHSCOMP_ROW
logical, public :: POSINRHSCOMP_COL_ALLOC
logical, public :: pad11
integer, public, DIMENSION(:), POINTER :: POSINRHSCOMP_COL
double precision, public, DIMENSION(:), POINTER :: RHSCOMP
double precision, public, DIMENSION(:), POINTER :: MEM_SUBTREE
double precision, public, DIMENSION(:), POINTER :: COST_TRAV
integer, public, DIMENSION(:), POINTER :: MY_ROOT_SBTR
integer, public, DIMENSION(:), POINTER :: MY_FIRST_LEAF
integer, public, DIMENSION(:), POINTER :: MY_NB_LEAF
integer, public, DIMENSION(:), POINTER :: DEPTH_FIRST
integer, public, DIMENSION(:), POINTER :: DEPTH_FIRST_SEQ
integer, public, DIMENSION(:), POINTER :: SBTR_ID
integer, public, DIMENSION(:), POINTER :: SCHED_DEP
integer, public, DIMENSION(:), POINTER :: SCHED_GRP
integer, public, DIMENSION(:), POINTER :: SCHED_SBTR
integer, public, DIMENSION(:), POINTER :: CROIX_MANU
double precision, public, DIMENSION(:), POINTER :: WK_USER
integer, public :: NBSA_LOCAL
integer, public :: LWK_USER
double precision, public :: DKEEP(230)
double precision, public, DIMENSION(:), POINTER :: CB_SON_SIZE
integer, public :: INSTANCE_NUMBER
integer, public :: OOC_MAX_NB_NODES_FOR_ZONE
integer, public, DIMENSION(:,:), POINTER :: OOC_INODE_SEQUENCE
integer(kind=8), public, DIMENSION(:,:), POINTER :: OOC_SIZE_OF_BLOCK
integer(kind=8), public, DIMENSION(:,:), POINTER :: OOC_VADDR
integer, public, DIMENSION(:), POINTER :: OOC_TOTAL_NB_NODES
integer, public, DIMENSION(:), POINTER :: OOC_NB_FILES
integer, public :: OOC_NB_FILE_TYPE
integer, public :: pad12
integer, public, DIMENSION(:), POINTER :: OOC_FILE_NAME_LENGTH
character, public, DIMENSION(:,:), POINTER :: OOC_FILE_NAMES
integer, public, DIMENSION(:), POINTER :: PIVNUL_LIST
integer, public, DIMENSION(:,:), POINTER :: SUP_PROC
integer, public, DIMENSION(:,:), POINTER :: pad14
integer, public, DIMENSION(:), POINTER :: IPTR_WORKING
integer, public, DIMENSION(:), POINTER :: WORKING
type(DMUMPS_ROOT_STRUC), public :: root
integer, public, POINTER, DIMENSION(:) :: LRGROUPS
integer, public :: NBGRP
integer, public :: pad13
character, public, DIMENSION(:), POINTER :: FDM_F_ENCODING
character, public, DIMENSION(:), POINTER :: BLRARRAY_ENCODING
integer, public :: LPOOL_AFTER_L0_OMP
integer, public :: LPOOL_BEFORE_L0_OMP
integer, public :: L_PHYS_L0_OMP
integer, public :: L_VIRT_L0_OMP
integer, public :: LL0_OMP_MAPPING
integer, public :: pad15
integer(kind=8), public :: THREAD_LA
integer, public, DIMENSION(:), POINTER :: IPOOL_BEFORE_L0_OMP
integer, public, DIMENSION(:), POINTER :: IPOOL_AFTER_L0_OMP
integer, public, DIMENSION(:), POINTER :: PHYS_L0_OMP
integer, public, DIMENSION(:), POINTER :: VIRT_L0_OMP
integer, public, DIMENSION(:), POINTER :: PERM_L0_OMP
integer, public, DIMENSION(:), POINTER :: PTR_LEAFS_L0_OMP
integer, public, DIMENSION(:), POINTER :: L0_OMP_MAPPING
integer, public, DIMENSION(:), POINTER :: MPITOOMP_PROCS_MAP
double precision, public, DIMENSION(:), POINTER :: SINGULAR_VALUES
integer, public :: NB_SINGULAR_VALUES
logical, public :: ASSOCIATED_OOC_FILES
Subroutines
subroutine writearray(fileunit, array)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fileunit
real(kind=8), intent(in), dimension(:) :: array
subroutine write2Darray(fileunit, array)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fileunit
real(kind=8), intent(in), dimension(:,:) :: array
Call graph
test_potential3d calls mpi_finalize, dmumps, mpi_init, write2darray, writearray