test_formats – GEMINI3D
test_formats Program
76 statements
Source File
Uses
iso_fortran_env
phys_consts
timeutils
This tests various text output formats. It necessarily requires visual inspection, or run from an enclosing program with Regex, such as a Python program configured to test as desired. Increment time tests
Calls
Contents
Variables
fn tmp UTsec dtinc ymd i
Variables
Type Attributes Name Initial
character(len=:), allocatable :: fn
character(len=25) :: tmp
real(kind=wp) :: UTsec
real(kind=wp) :: dtinc
integer :: ymd(3)
integer :: i
Call graph
test_formats calls utsec2filestem, dateinc
utsec2filestem calls day_wrap
dateinc calls day_wrap
day_wrap calls day_wrap, daysmonth