test_sza – GEMINI3D
test_sza Program
12 statements
Source File
Uses
phys_consts
timeutils
test day rollover
Calls
Contents
Variables
pi
Variables
Type Attributes Name Initial
real(kind=wp), parameter :: pi = 4._wp*atan(1._wp)
Call graph
test_sza calls sza
sza calls doy_calc
doy_calc calls daysmonth