name: ci_debug_build
env:
  CI: true

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - ".github/workflows/ci_debug_build.yml"
  pull_request:
    paths:
      - "**.f90"
      - "**.F90"
      - ".github/workflows/ci_debug_build.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: |
        pip install -e .[tests]
        pip install meson==0.53.0
    - name: Install prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build pkg-config gfortran liblapack-dev libscalapack-openmpi-dev libmumps-dev libopenmpi-dev openmpi-bin libhdf5-dev octave
    - run: meson setup build --buildtype=debug -Dhdf5=disabled
      env:
        FC: gfortran
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: LinuxDebug_Meson_Configlog
        path: build/meson-logs/meson-log.txt

    - run: pytest
    - run: ninja -C build
    - run: meson test -C build --suite unit -v
    - run: meson test -C build --suite 2d_fang -v
    - run: meson test -C build --suite 2d_glow -v
# CI is too slow for 3d_glow
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Debug_Testlog
        path: build/meson-logs/testlog.txt
